### ISSUE TITLE
crash dumping svfg

### ISSUE THREAD

**Issue by dtzWill** [SVF-tools/SVF#101]
Maybe related to issue of same name ( #98 ), but creating a new one because this issue is mostly an attempt to prevent another instance where I'm sitting on a patch (recent UAF fixes, #100 and sibling commit) that might be useful to folks.  Any lack of sharing was because I haven't had time to do due diligence in terms of investigating things more completely....

Anyway I would feel bad if this was the cause of something like #98 and I didn't at least forward it :).

This patch has been part of my build for a good while in order to stop crashing when dumping the SVFG in my usage:

https://github.com/dtzWill/nur-packages/blob/master/pkgs/svf/svfg-crash-fix.patch

Hope this helps, close or modify the change as you see fit! Thanks again for SVF!

**Comment by yuleisui** [comment]
Many thanks Will for sharing this with us:)

#98 has been fixed, the crash is due to the default checker is not specified.
