### ISSUE TITLE
struct equality in SVF

### ISSUE THREAD

**Issue by tregua87** [SVF-tools/SVF#1013]
I am struggling with multiple struct definition in LLVM. For instance, you can find LLVM modules containing two types `%struct.tiff.97*` and `%struct.tiff*`.  In the source code, both types refer to the same `tiff*` struct. However, when linking different modules, LLVM treats them separately and assigns them different names. This is an already known [issue](https://lowlevelbits.org/type-equality-in-llvm/) of LLVM.

Does SVF have an ad-hoc struct comparison method?
I browsed the code but I did not find anything that seems related to this problem.
Although, SVF seems to handle struct equality correctly. 

So, where is the trick? :)

**Comment by yuleisui** [comment]
This won't affect the correctness of SVF's field-sensitive analysis. Those types though different in names, when performing offset-based analysis, the generated field objects (GepObjPN) refer to the existing ones if they have already been generated during the analysis.

Struct A{
int a1;
int a2;
}

Struct B{
int b1;
int b2;
}
A* o1 = new A;
B* o2 = (B)A;

Though names are different, their structs are equivalent. Here o2.b1 and o1.a1 refer to the same field object.

**Comment by tregua87** [comment]
I see, so you confirm SVF does not have a struct equality mechanism, but the field-sensitive analysis is correct as long as the fields are the same.

**Comment by yuleisui** [comment]
Yes, no need for struct equivalent detection if the field-sensitive analysis is in place.

**Comment by tregua87** [comment]
Thanks :) that's enough.
