### ISSUE TITLE
Question: how to retrieve LLVMBasicBlock from ICFGNode

### ISSUE THREAD

**Issue by NICE994** [SVF-tools/SVF#1023]
Hi,

What is the intended way to get a **LLVMBasicBlock** from an ICFGNode in the icfg?
I find there is a way to get SVFBasicBlock from LLVMBasicBlock by `inline SVFBasicBlock* getSVFBasicBlock(const BasicBlock* bb) const`
I can get the SVFBasicBlock via `const SVFBasicBlock *svfbb = icfg->getICFGNode(id)->getBB();` but then I get stuck to retrieve the **LLVMBasicBlock**.
Maybe I missed something...

**Comment by yuleisui** [comment]
It is encouraged to use SVF's internal data structure. You can retrieve LLVM's BasicBlock via `getLLVMValue(SVFValue*)` and cast it to BasicBlock.  (https://github.com/SVF-tools/SVF/blob/983c7d2d65e6895f88e636a8a849d0006d7bcf94/svf-llvm/include/SVF-LLVM/LLVMModule.h#L188)
