### ISSUE TITLE
Possible dereference of invalid iterator?

### ISSUE THREAD

**Issue by xudon9** [SVF-tools/SVF#1035]
It is possible that, when `globals` is empty, this would trigger an erroneous behavior?

https://github.com/SVF-tools/SVF/blob/30cf19fbb7df37bac680d05743f81af9c3d39b2d/svf-llvm/lib/LLVMModule.cpp#L804

And I see that the following lines are searching for a global that `hasInitializer`. If such a global does not exist, should the `*globals.begin()` in `rep` be used afterward?

**Comment by yuleisui** [comment]
Your observation is correct, please go ahead fix this null dereference when the globals set is empty (unlikely in llvm bc, but could be in json file system)
