### ISSUE TITLE
About Static Analysis Course

### ISSUE THREAD

**Issue by xiaoyuwang0** [SVF-tools/SVF#1049]
Where can I find Static Analysis Course and I didn't find it in SVF-Teaching.

**Comment by yuleisui** [comment]
https://github.com/SVF-tools/SVF-Teaching

**Comment by xiaoyuwang0** [comment]
> https://github.com/SVF-tools/SVF-Teaching

https://github.com/SVF-tools/Teaching-Static-Analysis-AI
It shows a 404 error

**Comment by yuleisui** [comment]
This one is still under development.

**Comment by xiaoyuwang0** [comment]
> This one is still under development.

Okay.
