### ISSUE TITLE
Missing header file

### ISSUE THREAD

**Issue by xiaoyuwang0** [SVF-tools/SVF#1051]
/SVF/svf/include/Util/ExtAPI.h

#include "Util/config.h"

I didn't find it

I can build SVF but VScode keeps reporting errors

**Comment by yuleisui** [comment]
This file is generated by [.config.in](https://github.com/SVF-tools/SVF/blob/master/.config.in) after finishing building SVF.

**Comment by xiaoyuwang0** [comment]
Okay.
