### ISSUE TITLE
Cannot build SVFG with scalar variables anymore

### ISSUE THREAD

**Issue by jjang3** [SVF-tools/SVF#1062]
Hello,

It was stated in https://github.com/SVF-tools/SVF/issues/45#issuecomment-385227406 where, at that time, SVF did not capture def-use chains of scalars, but I have looked into https://github.com/SVF-tools/SVF/wiki/Write-a-source-sink-analyzer which provided with an example which allowed users to generate an SVFG with scalar variables using the command:
```
PAGBuilder builder;
SaberSVFGBuilder memSSA;
PAG* pag = builder.build(module);
AndersenWaveDiff* ander = AndersenWaveDiff::createAndersenWaveDiff(pag);
SVFG* svfg =  memSSA.buildPTROnlySVFG(ander);    /// memSSA.buildFullSVFGWithoutOPT(ander) to build SVFG with scalar variables.
```
However, my current version of SVF (with the commit id of `9658ef412010fb59ff4b1094a375c451ffee4f5f`, using the older version for personal reasons), at the moment, does not allow me to use the function `buildFullSVFGWithoutOPT(ander)`. I looked through `SaberSVFGBuilder.h`, and it seems like this function is removed.

Are there any alternative functions that I could use? Or what would be a good way to generate the def-use chain of scalar values? Any suggestions or insights would be appreciated.

**Comment by yuleisui** [comment]
You can use buildFullSVFG.

**Comment by jjang3** [comment]
Oh, I didn't realize that now everything is combined, thank you for your quick and prompt response!
