### ISSUE TITLE
Does saber support kernel space memory leak detection?

### ISSUE THREAD

**Issue by tr4v3ler** [SVF-tools/SVF#1077]
Does saber support kernel space memory leak detection? What do I need to do if I want to use Saber for memory detection for kernel modules?

**Comment by yuleisui** [comment]
It should be fine as long as the kernel models can be compiled into llvm bc files

**Comment by tr4v3ler** [comment]
> It should be fine as long as the kernel models can be compiled into llvm bc files
Yes, I have generated the llvm bitcodes for the kernel modules. I would like to confirm if Saber can recognize kmalloc, kfree, etc.
