### ISSUE TITLE
MTA module does not detect fork information

### ISSUE THREAD

**Issue by xiaoyuwang0** [SVF-tools/SVF#1088]
```
#include <iostream>
#include <thread>
void foo()
{
    std::cout << "main fork foo\n";
}
int main()
{
    std::thread th1(foo);
    th1.join();
    return 0;
}
```
I use `tcg->getNumOfForksite()` and `tcg->getNumOfJoinsite()` ,But the results are all 0.

**Comment by xiaoyuwang0** [comment]
And this program has a large ICFG,  `FunctionSet().size()` is 60.
That's Why?

**Comment by yuleisui** [comment]
MTA only supports phread. You may wish to modify the MTA’s ForkAPI to identify Cpp forks

**Comment by xiaoyuwang0** [comment]
> MTA only supports phread. You may wish to modify the MTA’s ForkAPI to identify Cpp forks

Yeah, the test result of this program is correct
```
#include <stdio.h>
#include <pthread.h>

void *myfunc(void *args)
{
    printf("hello\n");
    return NULL;
}
int main()
{
    pthread_t pt;
    pthread_create(&pt, NULL, myfunc, NULL);
    pthread_join(pt, NULL);
    return 0;
}
```
