### ISSUE TITLE
About SVFValue's sourceLoc

### ISSUE THREAD

**Issue by xiaoyuwang0** [SVF-tools/SVF#1095]
I output the sourceLoc of SVFValue, but the output of SVFFunction,SVFBB,SVFInst are all empty.
That's Why?

**Comment by yuleisui** [comment]
Have you tried their ‘toString()’ methods

**Comment by yuleisui** [comment]
You can use getSourceLoc

**Comment by xiaoyuwang0** [comment]
> You can use getSourceLoc

I tried it, but it output all empty

**Comment by xiaoyuwang0** [comment]
```
{ basic block:   } //BB->getSourceLoc()
//Inst->getSourceLoc()





{ basic block:   }


{ basic block:   }


{ basic block:   }





```

**Comment by yuleisui** [comment]
Need to compile source code with its debug information. Add -g when compiling

**Comment by xiaoyuwang0** [comment]
That's work for me. Thanks very much!

**Comment by xiaoyuwang0** [comment]
> Need to compile source code with its debug information. Add -g when compiling

That's work for me. Thanks very much!
