### ISSUE TITLE
Assertion failed with SVF::VFG::connectCallerAndCallee

### ISSUE THREAD

**Issue by sfu2** [SVF-tools/SVF#1097]
**Build Info**
docker build from commit 84a9ac60cc7df21fd8209b1249fcbb7952356b93 (with LLVM 14.0.0 in `build.sh`)

**Reproduce**
```bash
$ docker build -t svf .
$ docker run -it --rm -v ./redis-server.bc:/redis-server.bc svf saber /redis-server.bc
# Summaries of varies analyses
# ....
saber: /home/SVF-tools/SVF/svf/lib/Graphs/VFG.cpp:992: virtual void SVF::VFG::connectCallerAndCallee(const SVF::CallICFGNode*, const SVF::SVFFunction*, SVF::VFG::VFGEdgeSetTy&): Assertion `funArgIt == funArgEit && "function has more arguments than call site"' failed.
```
Expect Memory Leak Detection Results, but it ends with the above error.

Please see the attachment for `redis-server.bc`. Compiled with Redis version 7.0.8. It's generated using [gllvm](https://github.com/SRI-CSL/gllvm).
[redis-server.zip](https://github.com/SVF-tools/SVF/files/11521951/redis-server.zip)

**Comment by yuleisui** [comment]
@shuangxiangkan it looks like we don't have this assertion before. Can you check whether it is caused by your recent ExtAPI?

**Comment by yuleisui** [comment]
@jumormt could you also run saber to see which commit introduce this assertion?

**Comment by jumormt** [comment]
Running `wpa -ander -svfg redis-server.bc` triggers the same assertion. The assertion triggers when updating indirect calls. I will take a deeper look into this issue.

**Comment by yuleisui** [comment]
What is the callee function for this indirect call at this assertion?

**Comment by yuleisui** [comment]
It looks like this function has variant arguments otherwise, it should not trigger this assertion. 

https://github.com/SVF-tools/SVF/blob/84a9ac60cc7df21fd8209b1249fcbb7952356b93/svf/lib/MemoryModel/PointerAnalysis.cpp#L413

we can fix this assertion error using the above matcharg method.
