### ISSUE TITLE
Support for C++ virtual methods with AddressSanitizer

### ISSUE THREAD

**Issue by acidghost** [SVF-tools/SVF#1114]
I'm running the Andersen pointer analysis on [poppler](https://gitlab.freedesktop.org/poppler/poppler/-/tree/1d23101ccebe14261c6afc024ea14f29d209e760) and it fails this assertion
https://github.com/SVF-tools/SVF/blob/6d52d36cf9ec48584b167ba028fe9f79721f674c/svf-llvm/lib/CHGBuilder.cpp#L102

Apparently it finds a vtable that does not have the expected format. Indeed (one of) the offending global variables looks like:
```
@_ZTV16AnnotCalloutLine = hidden constant { { [4 x i8*] }, [32 x i8] } { { [4 x i8*] } { [4 x i8*] [i8* null, i8* bitcast ({ { i8*, i8* }, [16 x i8] }* @_ZTI16AnnotCalloutLine to i8*), i8* bitcast (void (%class.AnnotCalloutLine*)* @_ZN16A
nnotCalloutLineD1Ev to i8*), i8* bitcast (void (%class.AnnotCalloutLine*)* @_ZN16AnnotCalloutLineD0Ev to i8*)] }, [32 x i8] zeroinitializer }, align 32, !type !67155
```
Note the type `{ { [4 x i8*] }, [32 x i8] }` instead of `{ [4 x i8*] }`.

I'm using LLVM 15 (w/o opaque pointers) and AddressSanitizer.

I was able to make a minimal reproducer (https://godbolt.org/z/x6T711aYh) and the issue seems to be the use of virtual methods and AddressSanitizer. The additional "padding" might be the [redzones added to global variables by AddressSanitizer](https://github.com/llvm/llvm-project/blob/8dfdcc7b7bf66834a761bd8de445840ef68e4d1a/llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp#L2187-L2189).

Using `-mllvm -asan-globals=0` solves the issue with poppler, but disables AddressSanitizer for global variables.

I could write a PR to fix this. What do you think is the best solution?

**Comment by yuleisui** [comment]
Thanks for the finding. Yes, please go ahead with a PR.

**Comment by acidghost** [comment]
@yuleisui do you have suggestions on how to fix this?

**Comment by yuleisui** [comment]
We could add an exclusive condition for `isValVtbl` for the addressSan's padding?
