### ISSUE TITLE
Assertion failure on files with external function with mismatched signature

### ISSUE THREAD

**Issue by acidghost** [SVF-tools/SVF#1118]
Configuring a project with CMake that uses the [CheckFunctionExists](https://cmake.org/cmake/help/latest/module/CheckFunctionExists.html) module tries to compile [this C file](https://github.com/Kitware/CMake/blob/722c801da774a45a3245fd7abe5f87eb5066632f/Modules/CheckFunctionExists.c).

Steps to reproduce:
- I store that file as `test.c`
- compile it with: `clang -Wall -std=c99 -D_DEFAULT_SOURCE -DCHECK_FUNCTION_EXISTS=strtok_r -emit-llvm -c test.c -Xclang -no-opaque-pointers`; this is similar as what CMake does, minus `-emit-llvm` and disabling opaque pointers
- use Andersen's PTA (i.e. `wpa -ander -stat=false test.o`)
- assertion failure `The operand should be a pointer type!`: https://github.com/SVF-tools/SVF/blob/d047e7edd605d93c06f29f68d344df0622e9cbc6/svf-llvm/lib/SVFIRExtAPI.cpp#L114

I think the issue comes from the function being declared with signature [`char strtok_r(void)`](https://github.com/Kitware/CMake/blob/722c801da774a45a3245fd7abe5f87eb5066632f/Modules/CheckFunctionExists.c#L6-L7) and SVF expecting a different signature https://github.com/SVF-tools/SVF/blob/d047e7edd605d93c06f29f68d344df0622e9cbc6/svf/include/Util/ExtAPI.json#L4458-L4467

I'm using LLVM 15.0.7, let me know if you need more info.

**Comment by acidghost** [comment]
I forgot to add that I'm pretty sure the problem was not happening on commit 984e7593778478cb55f4f1cbef1fe9ad6b023a01 and I'm now using commit d047e7edd605d93c06f29f68d344df0622e9cbc6.

**Comment by yuleisui** [comment]
@shuangxiangkan can you check this?

**Comment by shuangxiangkan** [comment]
strtok_r() is a string handling function in the C standard library, as defined in ExtAPI.json. However, it is not present in test.o. If you wish to use your own strtok_r(), you can configure it in ExtAPI.json to replace the previous strtok_r()'s side-effect. For example:
```
"strtok_r": {
      "return": "i8",
      "arguments": "()",
      "type": "EFT_NOOP",
      "overwrite_app_function": 0
}
```

**Comment by acidghost** [comment]
The CMake module verifies that the function `strtok_r` from the standard library is present by verifying it can link against it. I have no control over it. I'm not trying to re-define `strtok_r`, hence updating `ExtAPI.json` is not a solution.

**Comment by yuleisui** [comment]
> The CMake module verifies that the function `strtok_r` from the standard library is present by verifying it can link against it. I have no control over it. I'm not trying to re-define `strtok_r`, hence updating `ExtAPI.json` is not a solution.

Please check whether this pr fixed the issue or not https://github.com/SVF-tools/SVF/pull/1119

**Comment by acidghost** [comment]
It seems the issue is fixed now. Thanks!
