### ISSUE TITLE
SVF with rust analyzing

### ISSUE THREAD

**Issue by UNI20171384** [SVF-tools/SVF#1135]
Hi,

I'm working on analyzing the Rust LLVM-IR but in version 2.4 of SVF, I think it cannot transform Rust LLVM-IR to SVF module

So is there any version that can handle all the Rust LLVM-IR for SVF analyzing ?

**Comment by yuleisui** [comment]
What do you mean SVF 2.4 can’t analyse rust? As long as rust can be lowered to llvm ir, svf should be able to analyse

**Comment by UNI20171384** [comment]
In Rust LLVM-IR, there is main function such as 

define internal void @_ZN5testr4main17hed28a1d737de6524E() unnamed_addr #1 {
start:
; call testr::foo
  %_a = call i32 @_ZN5testr3foo17h906272c36ad05becE()
  br label %bb1

bb1:                                              ; preds = %start
  ret void
}

But when I iterate SVFmodule , I cannot get the _ZN5testr4main17hed28a1d737de6524E() function

I can get this function when I iterate llvmModule from
 LLVMModuleSet *ModSet = LLVMModuleSet::getLLVMModuleSet();
 Module *llvmModule = ModSet->getMainLLVMModule();

**Comment by UNI20171384** [comment]
Thank you for your very quick response!

And, I'm really sorry for the confusion. SVF-2.4 version can handle Rust LLVM-IR

Above question was not problem

Thank you
