### ISSUE TITLE
SVFVar can only have unique definition

### ISSUE THREAD

**Issue by zu1k** [SVF-tools/SVF#1145]
I got `SVFVar can only have unique definition` error when build SVFG or VFG after Andersen's pointer analysis.

LLVM: 14.0.0
SVF: latest master branch with `llvmToString` call commented https://github.com/SVF-tools/SVF/issues/1144#issuecomment-1626358938 

BC file: [xmllint_svf_master_llvm_14.zip](https://github.com/SVF-tools/SVF/files/11988277/xmllint_svf_master_llvm_14.zip)

```
# wpa -ander -svfg  ./xmllint.bc

..... some stats output

wpa: /home/SVF-tools/SVF/svf/include/Graphs/VFG.h:417: void SVF::VFG::setDef(const PAGNode*, const SVF::VFGNode*): Assertion `(it->second == node->getId()) && "a SVFVar can only have unique definition "' failed
```

**Comment by yuleisui** [comment]
Thanks for reporting. Could you post the ToString value/contents of the PAGNode and VFGNode?

**Comment by zu1k** [comment]
```
PAGNode: ValVar ID: 179296
Const 

VFGNode: IntraPHIVFGNode ID: 233452 PAGNode: [179296 = PHI(33, 44, )]    Const
``

**Comment by yuleisui** [comment]
Need to know LLVM values of these two.

**Comment by zu1k** [comment]
> Need to know LLVM values of these two.

How to do this in `VFG.h`?

```
/// Given a PAGNode, set/get its def VFG node (definition of top level pointers)
//@{
inline void setDef(const PAGNode* pagNode, const VFGNode* node)
{
    PAGNodeToDefMapTy::iterator it = PAGNodeToDefMap.find(pagNode);
    if(it == PAGNodeToDefMap.end())
    {
        PAGNodeToDefMap[pagNode] = node->getId();
        assert(hasVFGNode(node->getId()) && "not in the map!!");
    }
    else
    {
        if (it->second != node->getId()) {
            std::cout << std::endl << "SVFVar can only have unique definition" << std::endl;
            std::cout << "PAGNode: " << pagNode->toString() << std::endl;
            std::cout << "VFGNode: " << node->toString() << std::endl;
            
            // ? get LLVM Value

        }
        // assert((it->second == node->getId()) && "a SVFVar can only have unique definition ");
    }
}
```

**Comment by zu1k** [comment]
> ```
> PAGNode: ValVar ID: 179296
> Const 
> 
> VFGNode: IntraPHIVFGNode ID: 233452 PAGNode: [179296 = PHI(33, 44, )]    Const
> ```

I did a count for the bc file I uploaded above and this is the only one that triggers this assert.

**Comment by zu1k** [comment]
> Need to know LLVM values of these two.

I'm sorry I'm not quite sure how to implement this.

In my own code I can get it by including "SVF-LLVM/LLVMUtil.h", but here I'm not quite sure if other steps are needed, maybe also modifying the CMakeLists?

**Comment by yuleisui** [comment]
Wait until @xudon9's new patch, it will print llvm values via toString().

**Comment by xudon9** [comment]
https://github.com/SVF-tools/SVF/pull/1147 should fix this.

**Comment by yuleisui** [comment]
@zu1k try latest SVF again and post the time difference vs SVF-2.4

**Comment by zu1k** [comment]
> @zu1k try latest SVF again and post the time difference vs SVF-2.4

https://github.com/SVF-tools/SVF/issues/1144#issuecomment-1627570731

This issue has been fixed, thank you for your prompt response and contribution!
