### ISSUE TITLE
GetPts and GetRevPts

### ISSUE THREAD

**Issue by UNI20171384** [SVF-tools/SVF#1149]
Hello,

I'm curious about GetPts and GetRevPts function that if I want to get all the related variables from "pointer" can I get all the related variables from using GetPts and GetRevPts functions?

For example, if I use GetPts("pointer"), I can get all the memory allocation that a "pointer" can points to. And If I get all the pointers from GetRevPts("memory") I might get all the pointers that can point to that memory.

So by using GetPts and GetRevPts, can I get all the related (direct and indirect) variables from a pointer ?

And I want to know how getRevPts function works, does it find all the pointers by traversing SVFG graph from memory allocation ?

Thank you

**Comment by yuleisui** [comment]
Your understanding is correct. GetRevPts of an object is collected during pointer analysis.

To get related variables of a pointer or object, you will need to traverse on PAG.

**Comment by UNI20171384** [comment]
Thank you very much
