### ISSUE TITLE
SVF can be implemented in LLVM Pass ?

### ISSUE THREAD

**Issue by UNI20171384** [SVF-tools/SVF#1154]
I want to make SVF(2.4version) implement in LLVM pass 

Is there any way?

**Comment by yuleisui** [comment]
Unfortunately, older version of SVF is no longer maintained.

**Comment by UNI20171384** [comment]
Then newest version of SVF can be transferred to LLVM pass ?

**Comment by yuleisui** [comment]
SVF is pretty standalone in its current form.. You may wish to modify the code to add some pass-related code.
