### ISSUE TITLE
The way to get PAG node from instruction

### ISSUE THREAD

**Issue by UNI20171384** [SVF-tools/SVF#1159]
From SVF 2.4 version, there is only some APIs that we can get PAGNode from NodeID or LLVM-Address Taken Value.

But I want to get PAGNode from special instruction such as %0 = load i32*, ... 

Is there any way ? 

Thank you

**Comment by yuleisui** [comment]
You will need to use retrieve SVFValue first and then get corresponding PAGNode 
https://github.com/SVF-tools/SVF/blob/be87f7863578244cad5ebe507b613ac62b358b01/svf-llvm/include/SVF-LLVM/LLVMModule.h#L186

**Comment by UNI20171384** [comment]
But what if the instruction is like "%11 = load i8, i8* %10"

Then can't we get SVFValue from such %11 value ?

**Comment by yuleisui** [comment]
Yes, you can through the API ‘getSVFValue’.

**Comment by UNI20171384** [comment]
Thank you, but is API 'getSVFValue' not supported in SVF 2.4 version ?

**Comment by yuleisui** [comment]
You can have a look though.

**Comment by UNI20171384** [comment]
Thank you so much!
