### ISSUE TITLE
Does the latest SVF not support the array-sensitive pointer analysis?

### ISSUE THREAD

**Issue by Luweicai** [SVF-tools/SVF#1162]
I want to use an array-sensitive pointer analysis in SVF. Based on the issue mentioned by someone earlier, I think that enabling the array-sensitive option is -locMM. However, the latest SVF does not have such an option. Does this mean that the SVF no longer supports array-sensitive pointer analysis?

**Comment by yuleisui** [comment]
The locMM has been removed a while ago. It does not support in current SVF.

**Comment by Luweicai** [comment]
Got, thank you for your reply.
