### ISSUE TITLE
Plan to upgrade to LLVM 14/15?

### ISSUE THREAD

**Issue by yiansu** [SVF-tools/SVF#1176]
Is there any plan to upgrade SVF to LLVM 14 or LLVM 15, or is it already in progress?

SVF uses typed pointers, and based on the discussion in #1034 and [LLVM Opaque Pointers](https://llvm.org/docs/OpaquePointers.html#version-support), the typed pointer is the default for LLVM 14 and is still fully supported in LLVM 15.

**Comment by yuleisui** [comment]
It is on our list. The opaque pointer change will not be too much in the current SVF framework, but we need some spared manpower to do this. You could also play around to change the typed pointer starting from ‘getElementType ‘and here https://github.com/SVF-tools/SVF/blob/7c39cf463514a639a42ef15e6f42c9332b1b4606/svf-llvm/include/SVF-LLVM/LLVMUtil.h#L122

**Comment by junwha0511** [comment]
Why don't we just recommend the users to build LLVM without opaque pointer? 
we can build LLVM15 without opaque pointer by add cmake flag` -DCLANG_ENABLE_OPAQUE_POINTERS=OFF`

**Comment by yuleisui** [comment]
Thanks for the input and it is a good interim solution

**Comment by acidghost** [comment]
Also passing `-Xclang -no-opaque-pointers` to `clang` works with LLVM 15.

**Comment by yiansu** [comment]
@yuleisui Thanks very much for the reply! May I kindly ask about the expected timeline for the upgrade (say LLVM 14)? Our group is planning on upgrading our infrastructure, of which one project relies on SVF, so we can plan accordingly.

**Comment by yuleisui** [comment]
SVF already supports LLVM 14.

**Comment by yiansu** [comment]
Oh I see the latest tag is for LLVM 14. Thanks!
