### ISSUE TITLE
issues with location in the defect report

### ISSUE THREAD

**Issue by tianxinghe** [SVF-tools/SVF#1178]
I notice that in the previous version, saber was able to report locations, but it can not report locations anymore.
i wonder if I omit some important options?
![截图 2023-08-29 02-00-59](https://github.com/SVF-tools/SVF/assets/26410605/59931413-0716-4535-a26c-c0333eedd632)

**Comment by yuleisui** [comment]
You will need to compile your C code with debug option -g 

clang -c -g -emit-llvm ..

**Comment by tianxinghe** [comment]
> You will need to compile your C code with debug option -g
> 
> clang -c -g -emit-llvm ..

Thanks! It works.
