### ISSUE TITLE
SVFG issue: Missing OutEdge ? 

### ISSUE THREAD

**Issue by van-ema** [SVF-tools/SVF#1187]
I am traversing the SVFG. The interesting part of the LLVM IR is: 

```
%32 = invoke fastcc align 4 dereferenceable(4) i32* @"_ZN81_$$LT$I$GT$$GT$5index17h2492a45d212dafdfE"(%"alloc::vec::Vec<i32>"* noalias nonnull readonly align 8 dereferenceable(24) %2, i64 %30)
          to label %35 unwind label %33, !dbg !586
33:                                               ; preds = %31, %29
 ...
35:                                               ; preds = %31
  %36 = load i32, i32* %32, align 4, !dbg !586
```
While traversing, at some point I reach the `SVFNode` mapping to `%32` 

```
ActualINSVFGNode ID: 151094 at callsite:    %32 = invoke fastcc align 4 dereferenceable(4) i32* @"_ZN81_$LT$alloc..vec..Vec$LT$T$C$A$GT$$u20$as$u20$core..ops..index..Index$LT$I$GT$$GT$5index17h2492a45d212dafdfE"(%"alloc::vec::Vec<i32>"* noalias nonnull readonly align 8 dereferenceable(24) %2, i64 %30)
          to label %35 unwind label %33, !dbg !497 { "ln": 8, "cl": 16, "fl": "src/main.rs" } {fun: main}CSMU(98V_2)
pts{109163 }
```

I take the OutEdges and I reach the nodes

```
FormalINSVFGNode ID: 132466 {fun: _ZN81_$LT$alloc..vec..Vec$LT$T$C$A$GT$$u20$as$u20$core..ops..index..Index$LT$I$GT$$GT$5index17h2492a45d212dafdfE}140V_1 = ENCHI(MR_140V_1)
pts{109162 109163 }

FormalOUTSVFGNode ID: 136583 {fun: _ZN81_$LT$alloc..vec..Vec$LT$T$C$A$GT$$u20$as$u20$core..ops..index..Index$LT$I$GT$$GT$5index17h2492a45d212dafdfE}RETMU(140V_1)
pts{109162 109163 }
```

From there I can't see any OutEdge. Shouldn't I be able to reach  `%36` ?
Also, the above `SVFGNode`s do not contain any LLVM value while I would expect them to contain the CallBase. The called function of ` %32` contains several ` extractvalue` instructions. Is that the problem since `extractvalue`  is not supported yet? 
Thanks for the technical support. 

EDIT: I just tried to dump the svfg indeed the node is there:

```
Node0x27547450 [shape=record,color=yellow,penwidth=2,label="{ActualRetVFGNode ID: 82685 CS[\{ \"ln\": 8, \"cl\": 16, \"fl\": \"src/main.rs\" \}]ValVar ID: 2911\n   %32 = invoke fastcc align 4 dereferenceable(4) i32* @\"_ZN81_$LT$alloc..vec..Vec$LT$T$C$A$GT$$u20$as$u20$core..ops..index..Index$LT$I$GT$$GT$5index17h2492a45d212dafdfE\"(%\"alloc::vec::Vec\<i32\>\"* noalias nonnull readonly align 8 dereferenceable(24) %2, i64 %30)\n          to label %35 unwind label %33
Node0x27547450 -> Node0x26458460[style=solid];
Node0x26458460 [shape=record,color=red,label="{LoadVFGNode ID: 35098 LoadStmt: [Var2917 \<-- Var2911]  \n   %36 = load i32, i32* %32, align 4,
```

Any idea why I don't see it while I traverse?

**Comment by yuleisui** [comment]
Are you using Saber's SVFG or an SVFG built with "-ander -svfg" option? For Saber's one, the pointer operand of a load instruction does not have an incoming edge, in order to trace memory flows from a store to a load. For the latter case, it should have a direct value-flow from %32 to %36.

`extractvalue ` is not supported yet.

**Comment by van-ema** [comment]
I used` wpa -ander -type -dump-vfg -svfg swap.ll`. 
In my pass I build the SVFG with: 
```
  MSet = SVF::LLVMModuleSet::getLLVMModuleSet();
  SVFM = MSet->buildSVFModule(Module);
  IRB = new SVF::SVFIRBuilder(SVFM);
  PAG = IRB->build();
  _pta = AndersenWaveDiff::createAndersenWaveDiff(PAG);
  SVFGBuilder svfBuilder;
  _svfg = svfBuilder.buildFullSVFG(_pta);
  _svfg->dump("svfg.dat");
```
and the edge is in the dump. However if I traverse the graph, the edge is not there.

**Comment by yuleisui** [comment]
You may wish to have a look at the dumped SVFG whether the edge is there.

**Comment by van-ema** [comment]
Thanks for you reply. This issue is related to https://github.com/SVF-tools/SVF/issues/126
Function call at %32 contains `extractvalue` instructions and the graph does not link the argument `%2%` to the return value. I can reach the load from the second argument that does not go through the `extractvalue` instruction.
