### ISSUE TITLE
Connect global edges when analyzing libraries as well

### ISSUE THREAD

**Issue by timmyyuan** [SVF-tools/SVF#1189]
I found that SVF connects global edges when analyzing the main function. Is it possible to add global edges when analyzing libraries as well? I'm not sure if simple changes in `connectGlobalToProgEntry` make sense.

**Comment by yuleisui** [comment]
It does not seem to make sense for lib functions/variables treated as globals

**Comment by timmyyuan** [comment]
Sorry, I'm not sure I exactly get what you mean. Let me explain it in more detail. I want to do some pointer analysis related to constant strings. However, in LLVM IR, constant strings are all stored in global variables.  I can't seem to get the correct alias results If SVF doesn't connect `StoreVFGNode`s (for constant strings) to `FormalINSVFGNode`s at the beginning of the function. In contrast, If the analyzed function is the `main` function, the alias result will be correct. So I‘m wondering if it is possible to add these edges for each function or specified functions.

**Comment by yuleisui** [comment]
You can do it if those functions do not have callers.

**Comment by timmyyuan** [comment]
Thank you for pointing that out. I'm curious what the side effects would be if these functions had callers? Will this result in incorrectly oriented flow?

**Comment by yuleisui** [comment]
Can have spurious flows as those functions may or may not be called by third party libs.

**Comment by timmyyuan** [comment]
Many thanks!
