### ISSUE TITLE
Support for indirect call

### ISSUE THREAD

**Issue by llooFlashooll** [SVF-tools/SVF#1197]
I am currently studying SVF and really appreciate it. However, I cannot find any detailed document about the indirect call support in SVF apart from some issues.
I'm wondering whether SVF supports indirect calls, and to what extent does SVF support indirect calls? How is it written in the source code? Compared to this work https://github.com/umnsec/mlta, how are they similar or different?
If you could give me some advice and guidance, I'd be very grateful!

**Comment by llooFlashooll** [comment]
Any remark or did I raise a good question lol?

**Comment by yuleisui** [comment]
SVF supports indirect call resolution by using pointer analysis results. The points-to targets of a function pointer are resolved at an indirect callsite to connect callsite to its callees, with function signatures matching also enabled. I am not too sure about the implementation you are referring to, but I believe the type based approach can be used to complements the pointer analysis based methods.

**Comment by llooFlashooll** [comment]
Dear Prof. Yulei, thanks for your reply! That helps a lot.
