### ISSUE TITLE
Ignore specific instructions building the SVFG?

### ISSUE THREAD

**Issue by van-ema** [SVF-tools/SVF#1239]
I want to use SVF at link-time during LTO on a module instrumented at compile-time with SanitizerCoverage.
However, building the SVFG is really slow (it didn't terminate after 3 days). 
I think the reason is because of sancov instrumentation.   
Is it possible to skip certain instructions (in my case sancov instrumentation) when building the svfg? 
I would appreciate if you could point me out to any code I would have to look at.

**Comment by yuleisui** [comment]
Analyzing large bcs is time-consuming. How large is your bc? When you said generation of SVFG, which phase of SVF costs more time, is that pointer analysis or memory SSA construction or SVFG generation? 

The following is a simple way to generate SVFG, before that you will need to conduct pointer analysis and then memSSA.
https://github.com/SVF-tools/SVF/blob/1f99ca0dcefd0a7ffee441caaa85410946f4b0d3/svf/lib/WPA/WPAPass.cpp#L117-L123

**Comment by yuleisui** [comment]
If you think without SanitizerCoverage, SVF can generate SVFG, my suggestion is to do a pre-pass to remove sancov instrumentation before feeding the bc to SVF.

**Comment by van-ema** [comment]
The bc is around 200MB.
I'm indeed first running pointer analysis and then I use `buildFullSVFG` as in th code you've shown. 
iIt hangs forever. I will now try to build with Debug option to se what's happining.

There is any reason why it is not practicable to blacklist instructions in SVFG building? 
I do not want to remove sancov instrumentation but I could move it after SVF analysis in case.
Thanks for your help!
