### ISSUE TITLE
Get "points-by" information in DDA query

### ISSUE THREAD

**Issue by Qcloud1223** [SVF-tools/SVF#1248]
Hello,

SVF is a really nice and practical project and I enjoy using it. I'm using the following test program:

```c
// multi-ptr.cc
int glb;

int main()
{
    int *a, *b, *c;
    a = &glb;
    b = &glb;
    c = &glb;

    /* Only a and b is stored */
    *a = 1;
    *b = 2;

    return 0;
}
```

I used the following command to generate ConsG. (BTW, `-fdaa` does not seem to affect anything according to code)

```
dvf -stat=false -cxt -fdaa -dump-constraint-graph multi-ptr.bc
```
![multi-ptr](https://github.com/SVF-tools/SVF/assets/46517840/abc11021-05d5-4be3-b41c-66a7a9cc683a)

And I use the following command to query the SVFG:

```
$ dvf -stat=false -cxt -fdaa -query=26 -print-query-pts multi-ptr.bc
// represent `*a = 1`
##<> Source Loc: { "ln": 11, "cl": 6, "fl": "multi-ptr.cc" }
Ptr 26          PointsTo: { 6 }
!!Target NodeID 6        [<glb> Source Loc: { Glob "ln": 1, "fl": "multi-ptr.cc" }] 

$ dvf -stat=false -cxt -fdaa -query=28 -print-query-pts multi-ptr.bc
// represent `*b = 2`
##<> Source Loc: { "ln": 12, "cl": 6, "fl": "multi-ptr.cc" }
Ptr 28          PointsTo: { 6 }
!!Target NodeID 6        [<glb> Source Loc: { Glob "ln": 1, "fl": "multi-ptr.cc" }]
```

I'm wondering if there is an existing API to query "points-by" information. In this case, I'm interested in all references to `Ptr 6` ( corresponds to `glb` in source), so I can get something like `Ptr 6     PointsBy: {26 28}`, without having to use `-query=all` and filter the results. Thank you!

**Comment by yuleisui** [comment]
“dvf” works on SVFG but not the constraint graph, you may wish to dump SVFG. There is no “fdda” option, where did you find this?

For your case, there is no API to query points to by in dvf, but you could try to query the pointers aliased with a object determined by the Andersen’s analysis.

**Comment by Qcloud1223** [comment]
Thanks for your fast reply! I really appreciate it.

> “dvf” works on SVFG but not the constraint graph, you may wish to dump SVFG.

Yes, I also dumped SVFG. But I think the reason `dvf` can dump constraint graph is that it depends on the result of pre-analysis?

> There is no “fdda” option, where did you find this?

https://github.com/SVF-tools/SVF/blob/master/svf-llvm/tools/DDA/dda.cpp#L60
Those options in `dda.cpp` do not seem to actually affect anything.

> For your case, there is no API to query points to by in dvf, but you could try to query the pointers aliased with a object determined by the Andersen’s analysis.

To be clear, I want to perform flow-sensitive analysis and want to make queries about several top-level pointers. In this case I want to know the exact location and context where `glb` is read or modified. 

I have read SUPA paper and some of the source code of DDA, and believe that `dvf` is what I need (please correct me if I'm wrong).  So currently my solution is to make queries to all pointers and filter the results, which is dumb.

**Comment by Qcloud1223** [comment]
Reading #752 solving most of my questions. Thank you again for your time and reply!
