### ISSUE TITLE
Divergent Results and Loading Concerns in buildSVFModule Methods

### ISSUE THREAD

**Issue by rycbar77** [SVF-tools/SVF#1257]
I'm currently working on a pass within the project, and I've encountered divergent points-to analysis results using two different methods of `buildSVFModule`.

The method `SVFModule* LLVMModuleSet::buildSVFModule(const std::vector<std::string> &moduleNameVec)` functions correctly, but its post-analysis instrumentation poses challenges for me. Consequently, I've explored an alternative approach using `SVFModule* LLVMModuleSet::buildSVFModule(Module &mod)`. Unfortunately, this alternative method is not yielding the expected results. Upon further investigation, I discovered that the `SVFModule* LLVMModuleSet::buildSVFModule(Module &mod)` method fails to load `extapi.bc`.

To address this issue, I've identified two potential solutions. The first involves linking `extapi.bc` with my bitcode files. However, this approach leads to the failure of the compiled bitcode file during execution. The second solution involves making slight modifications to the SVF source code to ensure that `buildSVFModule(Module &mod)` inherently loads `extapi.bc`.

I'm unsure whether the omission of `extapi.bc` loading in the `buildSVFModule(Module &mod)` method is intentional or accidental. Moreover, I'm seeking clarification on the intended usage of this method and whether there's a recommended way to address the issue.

**Comment by yuleisui** [comment]
I believe extAPI.bc is loaded when building SVF Module: https://github.com/SVF-tools/SVF/blob/d470e6f67c47d566e8878a8cc8f3d7d72102bef3/svf-llvm/lib/LLVMModule.cpp#L531

**Comment by rycbar77** [comment]
I see the method `loadExtAPIModules` called when using nameVec as the param, but I couldn't find any usages when using llvm Module. Did I miss anything?
https://github.com/SVF-tools/SVF/blob/d470e6f67c47d566e8878a8cc8f3d7d72102bef3/svf-llvm/lib/LLVMModule.cpp#L80

**Comment by yuleisui** [comment]
I see. @shuangxiangkan will update the code soon.

**Comment by yuleisui** [comment]
@rycbar77 could you try this fix?

https://github.com/SVF-tools/SVF/commit/1bbb7341a33a3e8e18bd31bd88873940a12096d3

**Comment by rycbar77** [comment]
I've tested it in my project, and it's working perfectly. Thanks for the prompt response!
