### ISSUE TITLE
Set Option in a programmable way

### ISSUE THREAD

**Issue by Qcloud1223** [SVF-tools/SVF#1259]
Hi,

If I understand it correctly, for those options already exists in `svf/lib/Util/Options.cpp`, SVF only allow users to set them from command line (they have `const` qualifier), and eventually `parseOptions` will do the job.

But there might be cases where the users want to do that programmably, e.g., decide path for `write-ander` according to input bitcode name and do not bother to type that again in CLI.

I see that `svf/include/Util/CommandLine.h` has a private member `getOption` which looks up the options map and feed it to `parseOptions`. Would it be reasonable to set this interface `public` and allow user to directly look up the options map and modify the options?

**Comment by Qcloud1223** [comment]
> Would it be reasonable to set this interface public and allow user to directly look up the options map and modify the options?

I tried but this failed my program in a way I cannot understand.

Meanwhile, I saw in `svf/lib/Util/Options.cpp` that there is only `DetectPWC` option without `const` qualifier, and can later be modified by `Option::setValue`. This interface is useful and I wonder why only this option can use it. Making all path-related options (`Read/WriteAnder`, `Read/WriteSVFG`) non-`const` makes sense to me.

**Comment by yuleisui** [comment]
You could submit a pull request for andersen’s read/write options

**Comment by yuleisui** [comment]
You patch should also change DetectPWC to be constant if there is no changes during analysis.

**Comment by Qcloud1223** [comment]
I see. Thank you!
