### ISSUE TITLE
Using extapi to overwrite C++ functions

### ISSUE THREAD

**Issue by Qcloud1223** [SVF-tools/SVF#1277]
Hello,

I'm exploring the use of extapi, especially using `OVERWRITE` annotation to clobber the implementation of original bitcode file, mainly to reduce size of PAG and consequently, execution time.

As the users can only write those `OVERWRITE` functions in `extapi.c`, I'm wondering how we can overwrite a C++ function.
C has no `namespace` or `class` keyword, making it impossible to define functions that are exactly the same as definitions in original `app module`.

However, I found SVF only checks the function name when performing the clobbering, ignoring arguments and return type. Thanks to this, I can directly define a function using the mangled name, in `extapi.c`. SVF does not complain about this and runs without problems for now (most likely due to test cases too weak).

So here are my problems:

1. Is it safe to only match name in `extapi.c`? If not, I'm afraid `extapi.c` cannot do it right since C can never provide a way to correctly support the use of `namespace` and `class`.
2. Is overwriting C++ functions officially supported in SVF? If so, how can I do that?

Thanks.

**Comment by yuleisui** [comment]
I think we not only check function names but only arguments and return type. @shuangxiangkan could you confirm?

For C++ functions, could you overwrite the mangled function whose name contains argument and namespace information.

**Comment by shuangxiangkan** [comment]
Currently, extapi only matches the name.

1. For C++ functions, I think matching only the name should be safe because even if the C++ function names are the same, if the parameters and return values are different, the mangled names will also be different.
2. I think you can write a file `extapi.cpp`, compile it into `extapi.ll` yourself, and replace the default `extapi.ll` generated from `extapi.c`.

extapi mainly implements the overwrite of functions through the `@llvm.global.annotations `global variable in the `.ll` file. If the “`OVERWRITE`” string can correctly map to the function you want to overwrite, then function `overwrite` can be achieved. However, this feature has not been thoroughly tested yet, you can try it first, and later when there is time, I will test the C++ functions in extapi

**Comment by Qcloud1223** [comment]
Hi Shuangxiang,

Thanks for your reply!

> For C++ functions, I think matching only the name should be safe because even if the C++ function names are the same, if the parameters and return values are different, the mangled names will also be different.

Indeed, matching name alone is enough for associating definition in `extapi module` with declaration `app module`. C does not allow symbols with the same name, while C++ has names mangled. However, it's unclear to me that what will happen when their return types or argument list mismatch, since I'm not an expert in SVF. Will it affect the result of points-to analysis and SVFG construction?

> I think you can write a file extapi.cpp, compile it into extapi.ll yourself, and replace the default extapi.ll generated from extapi.c.

I am on my way to achieve this, but it is quite tedious when writing extapi in c++. 

For example:

```c++
void someClass::foo() {} // will not work since `some_class` is not complete type
class someClass { void foo();};
void someClass::foo() {} // works fine
```

This forces people to scan twice when they have a large list of functions to overwrite, and some of them are members of the same class. The first pass needs to gather all member functions in the same class, and the second pass must generate a definition for each class, and then member function definition. This is way more complex than C. I'm wondering if there is a better way for a large list of functions.

**Comment by yuleisui** [comment]
@Qcloud1223 thanks for reporting it. Would you be able to help make a pull request to fix it with matched arguments and return types?

**Comment by Qcloud1223** [comment]
@yuleisui I would be more than willing to do that! Hopefully I could have time to read into more details of SVF recently.

**Comment by Qcloud1223** [comment]
>However, it's unclear to me that what will happen when their return types or argument list mismatch

One thing just came to me: SVFG construction should be wrong if the **number** of argument mismatch? I think that will cause a mismatch in `FormalIn` and `ActualIn` nodes.

**Comment by yuleisui** [comment]
C is fine and application is fine. Only C++ and lib code, you could have a test on C and work for matching arguments and return types for C first.

**Comment by yuleisui** [comment]
Could you check whether this pull request will fix your matching arguments issue? @Qcloud1223

**Comment by yuleisui** [comment]
> Could you check whether this pull request will fix your matching arguments issue? @Qcloud1223

@Qcloud1223 could you test and confirm?

**Comment by Qcloud1223** [comment]
This patch works for me in some quick tests. Will test it on some large bitcodes when I have time.

Thanks for your effort!
