### ISSUE TITLE
Get FormalParm for FormalIN nodes in SVFG

### ISSUE THREAD

**Issue by Qcloud1223** [SVF-tools/SVF#1288]
Hello,

My use case is to get PTS of a specific function argument (and its specific field if it is pointer to `struct`). It might have no direct calls, so I can only use `Formal*` nodes to solve it.

First, I can get `FormalIN` nodes for this function using `svfg->getFormalINSVFGNodes`. This function returns a node set that composes of all `FormalIN` nodes for every argument. Then I can retrieve the PTS of each node. 
However, it seems to contain no information on the argument index as `FormalParm` does, and thus I do not know which argument that PTS is for.

So my question is that, as the title suggests, whether there is a way to get `FormalIN` nodes corresponding to `FormalParm` node (or the opposite)?

**Comment by yuleisui** [comment]
FormalIN nodes are "invisible" which are indirectly passed via global variables or multi-dereferencing of a pointer argument. Therefore, it does not have a correspondence to a FormalParm.

**Comment by Qcloud1223** [comment]
Thanks for your reply!

Then can you give some insights on how to find the PTS of function arguments? I can't come out with a way since `FormalIN` does not correspond to `FormalParm`, and `FormalParm` is a VFG node which does not have `MRVer`.

**Comment by yuleisui** [comment]
You can get the SVFVar for the FormalParm node and retrieve the pts of that var

**Comment by Qcloud1223** [comment]
Did not think of that. Thank you very much!
