### ISSUE TITLE
Heap allocated structure has unexpected element number

### ISSUE THREAD

**Issue by Qcloud1223** [SVF-tools/SVF#1289]
Hello,

I'm testing SVF with structures on heap using this simple code snippet:

```c++
struct myStruct
{
    int a;
    double b;
    char c;
};

void foo(myStruct *ms)
{
    ms->a = 1;
    ms->b = 2;
    ms->c = 3;
}

int main()
{
    myStruct *ms = new myStruct;
    foo(ms);

    return 0;
}
```

And I'm using the following code to retrieve arguments of `foo`:

```c++
// F is pointing at `foo`
const auto &fpNodes = icfg->getFunEntryICFGNode(F)->getFormalParms();
// get the PTS argument is pointing to, should contain exactly one element
const auto &pts = ander->getPts(fpNodes[0]->getId());
// get the PAG node of struct definition
const auto &structFIObj = SVFUtil::dyn_cast<FIObjVar>(pag->getGNode(*pts.begin()));
// get the memory object of this struct, and get number of element
// should return 3
auto numFields = structFIObj->getMemObj()->getNumOfElements();
```

However, `numFields` returns 512, which is the default element number of `MemObj`.

In contrast, when switching `ms` from heap to stack, **it returns correct number of fields**.

---
I did some further inspection into SVF, and found the location where type information is initialized:

https://github.com/SVF-tools/SVF/blob/af2bdc8036b59cd205b70c7e72dc521a90e91328/svf-llvm/lib/SymbolTableBuilder.cpp#L841-L855

It assigns maximum field offset, i.e., 512, to every heap object, which seems to be the cause of this problem.

I'm wondering if this is the expected behavior or not. If so, how can I correctly get the number of elements for heap struct objects?

Thank you very much.

**Comment by yuleisui** [comment]
Have a try whether this pr will fix the problem. https://github.com/SVF-tools/SVF/pull/1290

**Comment by Qcloud1223** [comment]
Thank you very much for your quick reply! I really appreciate it.

This patch resolves the problem in this unit test. However, I found the problem persisted in a more complex bitcode.

Specifically, it does not step in the branch here:

https://github.com/SVF-tools/SVF/blob/af2bdc8036b59cd205b70c7e72dc521a90e91328/svf-llvm/lib/LLVMUtil.cpp#L356-L360

since `val->getNumUses()` is 2.

I disassemble the bitcode and found it's because the call to `_Znwm` (or `new`) has two uses: `bitcast` and `_ZdlPv` (or `delete`). Here is the .ll file (starting from call to `new`): 

```LLVM
%28 = call noalias nonnull dereferenceable(288) i8* @_Znwm(i64 288) #87, !dbg !550039, !heapallocsite !12680
; the first use  
%29 = bitcast i8* %28 to %"struct.snort::Packet.646"*, !dbg !550039
  invoke void @_ZN5snort6PacketC1Eb(%"struct.snort::Packet.646"* nonnull dereferenceable(283) %29, i1 zeroext true)
          to label %30 unwind label %33, !dbg !550040

30:                                               ; preds = %24
  call void @llvm.dbg.value(metadata %"struct.snort::Packet.646"* %29, metadata !549990, metadata !DIExpression()), !dbg !549991
  %31 = load i1 (%"struct.snort::Packet.646"*)*, i1 (%"struct.snort::Packet.646"*)** @_ZL9main_hook, align 8, !dbg !550041, !tbaa !269387
  %32 = call zeroext i1 %31(%"struct.snort::Packet.646"* nonnull %29), !dbg !550041
  br i1 %32, label %35, label %36, !dbg !550043

33:                                               ; preds = %24
  %34 = landingpad { i8*, i32 }
          cleanup, !dbg !550044
  ; the second use
  call void @_ZdlPv(i8* nonnull %28) #86, !dbg !550039
  resume { i8*, i32 } %34, !dbg !550039

35:                                               ; preds = %30, %1
  br label %36, !dbg !550045

36:                                               ; preds = %30, %35
  %37 = phi i1 [ true, %35 ], [ false, %30 ], !dbg !549991
  ret i1 %37, !dbg !550046
```

I'm wondering if the limitation on `val->getNumUses()` can be omitted since the first use of heap allocation tends to always be `bitcast`.

**Comment by yuleisui** [comment]
That is a good observation. How about only one cast instruction rather than one use? Could you help fix this by modifying the if condition and/or the if branch body?

**Comment by Qcloud1223** [comment]
I did more survey on this. It turns out that normally allocating and deallocating objects from heap compiles to `bitcast` to different value like:

```LLVM
%10 = call noalias noundef nonnull i8* @_Znwm(i64 noundef 24) #6, !dbg !51, !heapallocsite !12
%11 = bitcast i8* %10 to %struct.myStruct*, !dbg !51
...
%16 = bitcast %struct.myStruct* %13 to i8*, !dbg !55
  call void @_ZdlPv(i8* noundef %16) #7, !dbg !55
```

But when compiled with higher optimization levels, the second `bitcast` is optimized out, so there will be more than one `use` of return value of `new`, like below:

```LLVM
%5 = tail call noalias noundef nonnull dereferenceable(24) i8* @_Znwm(i64 noundef 24) #7, !dbg !54, !heapallocsite !11
%6 = bitcast i8* %5 to %struct.myStruct*, !dbg !54
...
tail call void @_ZdlPv(i8* noundef nonnull %5) #8, !dbg !65
```

I use the following workaround to address such situation:

```c++
if (IT->getBitWidth() == 8 && val->getNumUses() >= 1)
{
      const Value *latestUse = nullptr;
      for (const auto &it : val->uses()) {
          if (SVFUtil::isa<BitCastInst>(it.getUser()))
              latestUse = it.getUser();
      }
      return latestUse;
}
```

The reason to do this is that `uses()` seems to appear in reverse order, and `Use` does not has `operator--` or reverse operator. So I just traverse the use list and record the latest `bitcast`. Since there always seems to a `bitcast` right after call to `new`, this approach should be able to find that one.

**Comment by yuleisui** [comment]
Condition "val->getNumUses() >= 1" could be removed and the name "getUniqueUseViaCastInst" could be renamed to "getFirstUseViaCastInst". Could you submit a patch?

**Comment by Qcloud1223** [comment]
Could you please check #1293 ?

I also make sure the `bitcast` found is exactly the first use, which conform to behavior in eariler version.

**Comment by yuleisui** [comment]
Looks good to me. Will merge after the CI.
