### ISSUE TITLE
getFilePath in ExtAPI.cpp will cause segmentation fault.

### ISSUE THREAD

**Issue by sinotca529** [SVF-tools/SVF#1299]
Hi.

I found a bug in ExtAPI.cpp.
In `getFilePath`, the return value of `getenv` is not checked.
So, when the environment value `SVF_DIR` is not set, it will cause segmentation fault.

https://github.com/SVF-tools/SVF/blob/90a071572d92de5fa3a6940d7d4a115f124f00c0/svf/lib/Util/ExtAPI.cpp#L100

I suggest the following modification to address this issue:

```cpp
char const* svfdir = getenv("SVF_DIR");
if (svfdir)
   bcFilePath = svfdir;
```

Thanks.

**Comment by yuleisui** [comment]
Thanks for reporting, could you make a pull request to fix this?

**Comment by sinotca529** [comment]
I have made PR (#1300) and it passed tests.
Please check it.
