### ISSUE TITLE
How to handle C++ external libraries

### ISSUE THREAD

**Issue by ZcoderL** [SVF-tools/SVF#1313]
I have found that after using C++ containers (such as vectors, maps, etc.), the SVFG graph becomes particularly complex, which is difficult for me to traverse the graph. Is there a good way to handle it?

**Comment by yuleisui** [comment]
You may wish to have a look at this: https://github.com/SVF-tools/Simplified-STL

**Comment by ZcoderL** [comment]
Thank you for your prompt reply. It has been very helpful to me
