### ISSUE TITLE
Is there a block-level ICFG in SVF?

### ISSUE THREAD

**Issue by Qcloud1223** [SVF-tools/SVF#1331]
Hi, I want to traverse all basic blocks of a function as well as its sub-procedures, and check if a block is dominator of another. Currently I'm using ICFG, but 1) it's instruction-level so it's too inefficient 2) still need to get to basic block to get dominator info.

I've looked at the implementation of `CFBasicBlockG`, and it really looks like a block-level ICFG. 
However, it confuses me to see `CFBasicBlockNode` contains a vector of `ICFGNode`, instead of `SVFBasicBlock`. I found that it's intentional in #1227, which remove `getSVFBasicBlock` for `CFBasicBlockNode`, but `getFunction` remains. Does that mean a `CFBasicBlockNode` can contain instructions across multiple blocks?

Did I miss something or misunderstanding what this graph is for?

Thank you!

**Comment by yuleisui** [comment]
@jumormt could you help answer this question?

**Comment by jumormt** [comment]
The cfbasicblocknode does not contain instructions across basic blocks. If a basicblock does not contain a call instruction, it is represented as a single cfbasicblocknode. Otherwise, the basicblock is split by each call in the block and each call basicblock connects to its callee.

**Comment by Qcloud1223** [comment]
Oh, that makes sense. I thought `br` is the only instruction that causes control flow to move to another block. Indeed `CFBasicBlockNode` should not contain a whole basic block.

Thank you very much for your reply!
