### ISSUE TITLE
crash with opaque pointers

### ISSUE THREAD

**Issue by void0red** [SVF-tools/SVF#1354]
svf-ex: /llvm-project-14.0.6.src/llvm/lib/IR/Type.cpp:748: static llvm::PointerType* llvm::PointerType::get(llvm::LLVMContext&, unsigned int): Assertion `CImpl->getOpaquePointers() && "Can only create opaque pointers in opaque pointer mode"' failed.

**Comment by void0red** [comment]
set CFLAGS="-mllvm -opaque-pointers" **may** works when generates llvm14 ir. (but I failed when compiling target project)
ref: https://releases.llvm.org/14.0.0/docs/OpaquePointers.html

**Comment by void0red** [comment]
Which llvm version should I use? llvm 13 in README?

**Comment by jumormt** [comment]
Opaque pointer is now supported with llvm version 16 (14/15 opaque pointer bc should also work). You can have a try.

**Comment by void0red** [comment]
It works now, nice job.
