### ISSUE TITLE
Broken Link in License

### ISSUE THREAD

**Issue by davis-matthew** [SVF-tools/SVF#136]
SVF/LICENSE.TXT refers to https://github.com/unsw-corg/SVF/blob/gh-pages/Contributors.txt as the place to find contributors to the SVF project, however this link seems to be outdated (the website no longer works). Perhaps linking to https://github.com/SVF-tools/SVF/graphs/contributors instead would be good although this includes all contributors instead of just main contributors.

**Comment by yuleisui** [comment]
Just fixed https://github.com/SVF-tools/SVF/commit/688efd2e0b8c682f3b747f64dbde1d65b49c182a
Thanks
