### ISSUE TITLE
SVF Tool Integration Interface

### ISSUE THREAD

**Issue by davis-matthew** [SVF-tools/SVF#137]
I'm trying to use SVF in a Static Thread Sharing Analysis project of mine, and I'd like to use the data without having SVF output and then reinterpret it. I mainly looked for something quite simple (getThreads(), getMethods(), getStatements(), etc.), so I may have missed something built-in. 

In the event that this functionality is not built-in however, I assume that an interface must have been made already. Rather than have everyone individually re-code or have to create a custom version of SVF for each project that uses something similar, is there a public version I should know about?

For reference my project is fairly general and requires data of all Threads, Methods, 
Memory Allocation Statements, and Method Call Statements. It would use this information along with the PAG generated by the SVF tool.

**Comment by yuleisui** [comment]
Hi Matthew,

It would be helpful if you could take a look at MTA, SVF's multithreaded analysis module:
https://github.com/SVF-tools/SVF/blob/master/lib/MTA/MTA.cpp#L119

It consists of may-happen-in-parallel (MHP) and lock analysis implementations, which may be of interest to you.
