### ISSUE TITLE
How to get type information for PAG node

### ISSUE THREAD

**Issue by YantingChi** [SVF-tools/SVF#1375]
Hi,
   Thanks for providing such a useful tool. 
   I am just curious if I can fetch type information for each PAG node. From my understanding PAG node (SVF IR) is translated from LLVM IR with general type information (SVFType*) annotated,  and for the top-level nodes, I can dump the corresponding LLVM IR for each node. However, I don't know how to get more detailed type information (i.e. llvm::type) for each PAG node(not only struct but like struct A). Is there any way I can achieve that or any source file I can look into? Or if it is not realized in the original SVF, is there any way I can add detailed type information to the PAG node?
   
   Thanks in advance!

**Comment by yuleisui** [comment]
You can first retrieve the SVFValue of an node and then get the type of that value.

**Comment by YantingChi** [comment]
Hi,
   I tried to retrieve the SVFValue of a node and get the type in the last week. However, I can only get type like this
   enum SVFTyKind 
    {
        SVFTy,
        SVFPointerTy,
        SVFIntegerTy,
        SVFFunctionTy,
        SVFStructTy,
        SVFArrayTy,
        SVFOtherTy,
    };
But not concrete types like what struct or what pointer ( like this node is of type struct A and the other node is of type struct B, I want to distinguish the two different struct types.) Is there any way I can directly achieve that or somehow add detailed type information to the PAG node?

**Comment by yuleisui** [comment]
You could do SVFType::toString()

**Comment by YantingChi** [comment]
Oh I see and the problem is solved! Thanks a bunch
