### ISSUE TITLE
ModRef Analysis and Context sensitivity

### ISSUE THREAD

**Issue by venkyjntu-git** [SVF-tools/SVF#139]
I was trying the following example
#include "aliascheck.h"
int **p,**q,**r;
int *x,*y,*z,*w,*v;
int a,b,c;
void f(){
 *p=y;
}
void g() {
   p=&w;
   y=&c;
    f();
   v=w;
 MUSTALIAS(v,y);
}
main() {
  p=&x;
  y=&b;
   f();
  z=x;
MUSTALIAS(z,y);
}

modified SVF code to get the points-to Info at MUSTALIAS call, 
main
z points to {c,b} 
y points to {b}
g
v points to {c,b} 
y points to {c}
why the result is context insensitive?ran wpa with fspta option.
May I know the portion of code containing CFL reachability?

**Comment by yuleisui** [comment]
`fspta' option supports flow-sensitive but context-insensitive points-to analysis.

Please see https://github.com/SVF-tools/SUPA to obtain the demand-driven points-to analysis implementation which supports context-sensitivity.

**Comment by venkyjntu-git** [comment]
Thank you,
Is there any option in SVF to get context sensitivity, 
isn't that the Interprocedural SSA is expected to differentiate the use of 'w' in g() and use of 'x' in main().
