### ISSUE TITLE
LLVM assertion: "Initializer type must match GlobalVariable type"

### ISSUE THREAD

**Issue by 251** [SVF-tools/SVF#1406]
Hi,

I updated to LLVM 15 (with assertions enabled) and whatever I run ends up in an assertion, e.g.:

```C
int main(void) {}
```

```bash
$ wpa -ander -svfg -dump-icfg test.bc
wpa: /llvm/lib/IR/Globals.cpp:471: void llvm::GlobalVariable::setInitializer(llvm::Constant*): Assertion `InitVal->getType() == getValueType() && "Initializer type must match GlobalVariable type"' failed.
```

I attached gdb and the issue seems to be that:
https://github.com/SVF-tools/SVF/blob/fa0d081299fd2ace031469a630f00904ba1ee42f/svf-llvm/lib/LLVMUtil.cpp#L511C1-L511C33
causes a type mismatch: `newCA` (`InitVal` in LLVM) has type `[0 x { ptr, ptr, ptr, i32, ptr }] zeroinitializer` whereas `glob` has the type `[217 x { ptr, ptr, ptr, i32, ptr }]` (the annotation array).

**Comment by yuleisui** [comment]
@shuangxiangkan could you take a look at this case?

**Comment by shuangxiangkan** [comment]
@251 Could you upload the bc file?

**Comment by 251** [comment]
Sure: [test.zip](https://github.com/SVF-tools/SVF/files/14612966/test.zip). But keep in mind that assertions in LLVM have to be enabled, for distribution packages this is typically not the case.

**Comment by JanWichelmann** [comment]
I ran into the same problem today. I managed to fix it by reverting [this change](https://github.com/SVF-tools/SVF/commit/f24a89d47859feecdfe90db4aee49112e7d25e74#diff-b1e592dbba2d9e90d30f29e77e77b7f7834bab7c758ae9520431f74dad13c5a4L508), i.e., I replaced

```c++
glob->setInitializer(newCA);
```

by
```c++
auto globName = glob->getName();
glob->setName("llvm.global.annotations_old");

GlobalVariable *newGlob = new GlobalVariable(*module, annotationsType, glob->isConstant(), glob->getLinkage(), newCA, globName, glob, glob->getThreadLocalMode());
newGlob->setSection(glob->getSection());
newGlob->setAlignment(glob->getAlign());

glob->replaceAllUsesWith(newGlob);
glob->eraseFromParent();
```
in svf-llvm/lib/LLVMUtil.cpp.

**Comment by JanWichelmann** [comment]
Works for me, thank you!
