### ISSUE TITLE
Andersen Analysis on Small program 

### ISSUE THREAD

**Issue by venkyjntu-git** [SVF-tools/SVF#143]
We ran a small test program using (-ander) the Andersen implementation
int **p,*x,*y,a;
   p=&x;
   p=&y;
   *p=&a;
  NOALIAS(x,y);  // It is giving Success
Is it  not flow-insensitive method should consider x and y as MAYALIAS

**Comment by yuleisui** [comment]
In your case, `x` and `y` do not point to anything.

**Comment by venkyjntu-git** [comment]
Even after adding x=&b,y=&b after declaration
It is giving success.
x and y should be MAYALIAS  for flow-insensitive implementation

**Comment by yuleisui** [comment]
Can you give me the full code example and llvm ir? I suspect that it might caused by llvm's partial SSA form.

**Comment by venkyjntu-git** [comment]
Yes, It is due to llvm partial SSA (mem2reg and mergereturn) resolved
