### ISSUE TITLE
Faced a crash on saber

### ISSUE THREAD

**Issue by tangken333** [SVF-tools/SVF#1437]
Faced a crash while running the saber for a llvm-15 IR.
![1713363119605](https://github.com/SVF-tools/SVF/assets/39759109/2a98e65c-f5f7-400a-853d-2e1958e8ae00)

The IR file is attached.
[Uploading zkevm_circuits-039281c79cc41144.ll.zip…]()

**Comment by yuleisui** [comment]
Are you using the latest SVF? If so, please use llvm-16 to compile your bc.

**Comment by tangken333** [comment]
Thanks for the reply! Maybe I can not change the bc, is there any LLVM-15 version for SVF that I can use?

**Comment by yuleisui** [comment]
SVF-1.9 works for llvm-14

**Comment by tangken333** [comment]
Dear Sir,

I used the LLVM-16 to build my IR again but still faced this problem. It seems that it is not a version problem. I upload my bc here. Thanks!
[zkevm_circuits-8a1cfd59e298339f.ll.zip](https://github.com/SVF-tools/SVF/files/15138079/zkevm_circuits-8a1cfd59e298339f.ll.zip)

**Comment by yuleisui** [comment]
@jumormt you could take a look at this? It might because of missing a pag edge during svfir builder

**Comment by tangken333** [comment]
> The bug is caused by trying connecting a direct value-flow from an integer to pointer (int2ptr instruction) when building a PTR only value flow graph. The source PAGNode (integer) does not have a definition on PTROnly SVFG, which raises the assertion. A possible solution is to check whether the source and destination PAG Node are both pointers when constructing PTROnly SVFG. @yuleisui @tangken333

Thanks for your help! I will try it again.
