### ISSUE TITLE
Querying WPAPass APIs using LLVM Value* and CallInst*

### ISSUE THREAD

**Issue by yiansu** [SVF-tools/SVF#1455]
Hello, our lab's codebase relies on two sets of APIs from SVF-1.8: `WPAPass::alias` and `WPAPass::getModRefInfo`.

Recently, we decided to upgrade to SVF-2.9, but it failed because of the change in the function signatures of these two APIs.
1) `alias`: we used to query alias results by passing two `llvm::Value*` but now it requires two `SVF::SVFValue*`.
2) `getModRefInfo`: we used to query by passing `llvm::CallInst*` but now it requires `SVF::CallSite`.

For the first problem, I found an API to get the corresponding `SVFValue*` using an LLVM `Value*` (please confirm my understanding is correct).
```
SVFValue* svfVal = LLVMModuleSet::getLLVMModuleSet()->getSVFValue(llvmVal);
```

But I'm not sure about the second change. Are there any APIs I can use to get a corresponding `CallSite` from an LLVM `CallInst *`?

Thanks!

**Comment by yuleisui** [comment]
You could take a look at the Callsite class. It should accept any call instructions.

**Comment by Johanmyst** [comment]
Maybe I misunderstand, but why wouldn't doing this be possible?

```
llvm::Value *llvm_val = <...>;
SVF::SVFValue *svf_val = SVF::LLVMModuleSet::getLLVMModuleSet()->getSVFValue(llvm_val);
if (svf_val && SVF::SVFUtil::isCallSite(svf_val)) {
    SVF::CallSite call_site = SVF::SVFUtil::getSVFCallSite(svf_val);
}
```

**Comment by yuleisui** [comment]
> Maybe I misunderstand, but why wouldn't doing this be possible?
> 
> ```
> llvm::Value *llvm_val = <...>;
> SVF::SVFValue *svf_val = SVF::LLVMModuleSet::getLLVMModuleSet()->getSVFValue(llvm_val);
> if (svf_val && SVF::SVFUtil::isCallSite(svf_val)) {
>     SVF::CallSite call_site = SVF::SVFUtil::getSVFCallSite(svf_val);
> }
> ```

It looks good to me.

**Comment by yiansu** [comment]
It works, thanks!
