### ISSUE TITLE
It seems PTA results of -sfrander have some pts-elements missing compared with -nander?

### ISSUE THREAD

**Issue by zhaosiying12138** [SVF-tools/SVF#1458]
Hi Prof. Sui, I recently study your paper: Fast and precise handling of positive weight cycles for field-sensitive pointer analysis, I also study the implementation of AndersenSCD.cpp and AndersenSFR.cpp.
However, it seems to print inconsistent results while analysising the code illustrated as follows.
```
#include <stdlib.h>

typedef struct {
    int f1;
    int f2;
    int f3;
    int f4;
    int f5;
    int f6;
    int f7;
} aggr;

void *f(int s)
{
    return malloc(s);
}

int main()
{
    aggr o;
    aggr **p, *a;
    int **q, *b;
    p = (aggr **)f(sizeof(aggr *));
    q = (int **)f(sizeof(int *));
    *p = &o;
    a = *p;
    b = &a->f3;
    *q = b;

    return 0;
}
```
And I run commands as follows,
```
clang -S -c -Xclang -disable-O0-optnone -fno-discard-value-names -emit-llvm pwc_test.c -g -o pwc_test.ll
opt -S -p=mem2reg pwc_test.ll -o pwc_test.ll
wpa -nander -stat=false -print-pts -print-field -dump-pag -dump-constraint-graph pwc_test.ll
wpa -sfrander -stat=false -print-pts -print-field -dump-pag -dump-constraint-graph pwc_test.ll
```

The results shows differently between with "-nander" and "-sfrander", and I think the "-sfrander" result is incomplete.
![image](https://github.com/SVF-tools/SVF/assets/32027697/e9daad8e-2801-40c0-9ec3-3722ab1e1cdd)
![image](https://github.com/SVF-tools/SVF/assets/32027697/aec19d24-6335-4dfb-a1c4-76e702558c52)
![image](https://github.com/SVF-tools/SVF/assets/32027697/67419b27-65cf-48ad-a1e6-77bbd1464722)
   
I did some spurious research, and I think the implementation of SFR-Anderson has bugs, see this [link](https://www.zhihu.com/question/655711135/answer/3495364204).
Would you please confirm if it is a bug or the results meet our expectation?

**Comment by yuleisui** [comment]
Thanks for reporting!

https://github.com/SVF-tools/SVF/pull/1479

Would this pull fix the issue? Please check and let us know.

**Comment by zhaosiying12138** [comment]
Yes, it works. Thank you and kisslune very much.
