### ISSUE TITLE
Unknown command line arguement

### ISSUE THREAD

**Issue by ycaibb** [SVF-tools/SVF#146]
Hi, When I follow the simple C program example and type `wpa -type -dump-icfg swap.opt`, it shows unkonwn command line arguement '-dump-icfg'. And I continue to search by wpa -help, there seems no "-dump-icfg' command. Please help. Thank you very much.

**Comment by yuleisui** [comment]
Could you please pull the lastest version and recompile? We have just merged this new functionality to the public repo of SVF an hour ago.
