### ISSUE TITLE
Incorrect alias result using -sfrander

### ISSUE THREAD

**Issue by yiansu** [SVF-tools/SVF#1475]
Hello, we found that the following program (test.cpp) has the incorrect alias result using `-sfrander`. But correct with other Andersen-based pointer analysis (`-nander`, `-sander` and `-ander`).

```C++
#include <aliascheck.h>
#include <stdio.h>
#include <stdlib.h>

typedef struct _N {
  int v;
  _N *next;
} N;

int main (int argc, char *argv[]) {
  N *firstNode = (N *)malloc(sizeof(N));
  firstNode->v = argc;

  N *lastNode = (N *)malloc(sizeof(N));
  lastNode->v = argc;

  firstNode->next = lastNode;
  lastNode->next = nullptr;

  N *tmp = firstNode;
  N *n = tmp->next;

  while (tmp != lastNode) {
    MAYALIAS(&(tmp->next), &(firstNode->next));
    tmp = n;
    n = tmp->next;
  }

  return 0;
}
```

### How to reproduce the bug
1. run `clang -c -emit-llvm -g test.cpp -o test.bc`
2. run `wpa -sfrander -stat=false test.bc`

**Comment by yuleisui** [comment]
Thanks for reporting this. @kisslune could you take a look at this implementation?

**Comment by yuleisui** [comment]
Would this pull request fix the issue? @yiansu 
https://github.com/SVF-tools/SVF/pull/1479

**Comment by yiansu** [comment]
Our test results show the bug is fixed. Thanks for the quick fix!
