### ISSUE TITLE
Questions about overflow detection

### ISSUE THREAD

**Issue by ZcoderL** [SVF-tools/SVF#1487]
Hello, I have read your abstract execution paper published in ICSE'24.
Then use the `ae` in SVF to detect several small software in the paper:`YAJL`、`MP4v2`、`RIOT`， I found that none of them achieved the effect of completing the detection in just a few seconds as stated in the paper. May I ask where the problem lies with me?
The command is as follows:
`ae -icfg-merge-adjnodes -overflow xxx.bc`
Test results:
![image](https://github.com/SVF-tools/SVF/assets/47477662/d013d8e3-aa1d-4e4e-9582-5fd4f5830286)
![image](https://github.com/SVF-tools/SVF/assets/47477662/120da03c-e462-41ab-ac6d-f6d90ab15670)

BC file:
[ae.zip](https://github.com/user-attachments/files/15830907/ae.zip)

**Comment by yuleisui** [comment]
It is suggested that you refer to the artifact for the AE implementation to reproduce the paper's results. The current version in SVF is unoptimised, and we are developing follow-up works, which will be released in due course.

**Comment by ZcoderL** [comment]
Thanks.I get it.

**Comment by grandnew** [comment]
@yuleisui Hi, where is the artifact? Is this one: https://zenodo.org/records/10578637 ?
I cannot pull the docker image now:
```
$ docker pull icseartifact/sae
Using default tag: latest
Error response from daemon: pull access denied for icseartifact/sae, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by grandnew** [comment]
@ZcoderL Hi, have you downloaded the artifact? Could you please help me? This is my email: lazyxero@gmail.com

**Comment by fouzhe** [comment]
@yuleisui Hi, where is the artifact? Is this one: https://zenodo.org/records/10578637 ?
I cannot pull the docker image now:
```
$ docker pull icseartifact/sae
Using default tag: latest
Error response from daemon: pull access denied for icseartifact/sae, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

@ZcoderL Hi, have you downloaded the artifact? Could you please help me? This is my email: fouzhe15@gmail.com
