### ISSUE TITLE
Successor of BranchStmt can be confused

### ISSUE THREAD

**Issue by LeoneChen** [SVF-tools/SVF#1490]
I've added one line `if(p == q) return;` to `example.c` in [SVF-example](https://github.com/SVF-tools/SVF-example/blob/master/example.c), code becomes like below.

```c
void swap(char **p, char **q){
  if(p == q) return;
  char* t = *p; 
       *p = *q; 
       *q = t;
}
int main(){
      char a1, b1; 
      char *a = &a1;
      char *b = &b1;
      swap(&a,&b);
}
```
But in the corresponding icfg, `Successor 1` points to `ICFGNode 36` instead of `ICFGNode 12`. `ICFGNode 36` seems to be a useless node because it is a debug instruction, but in icfg, it does not update `Successor 1` pointing to `ICFGNode 12`. When we use `BranchStmt::getSuccessor(1)`, it also points to `ICFGNode 36`, so this is not a dot dump problem.

```shell
IntraICFGNode36 {fun: swap{ "ln": 3, "cl": 9, "fl": "example.c" }}
   call void @llvm.dbg.declare(metadata ptr %t, metadata !27, metadata !DIExpression()), !dbg !28 { "ln": 3, "cl": 9, "fl": "example.c" }
```

![1718794422993](https://github.com/SVF-tools/SVF/assets/35480440/452cd2c1-96fd-4b93-89a5-25378c94f725)

**Comment by yuleisui** [comment]
This is a good finding, could you help fix this @jumormt @bjjwwang

**Comment by yuleisui** [comment]
@LeoneChen could you also have a look at the SVF codebase to see why the successor is not consistent?

**Comment by LeoneChen** [comment]
I think we should use non-intrinsic instructions as successor instructions, so the patch could be like [this](https://github.com/LeoneChen/SVF/commit/330f814aa27320e5ac8f302b59b2a20ed060063d), but I added two `assert` and I'm not sure what to do when there are only intrinsic instructions in the successor basic block. Maybe still use intrinsic instructions as successor?

**Comment by yuleisui** [comment]
Pls make a pull request, thanks

**Comment by LeoneChen** [comment]
PR https://github.com/SVF-tools/SVF/pull/1491

**Comment by yuleisui** [comment]
I have a better fix here to make it consistent with ICFGBuilder: https://github.com/SVF-tools/SVF/pull/1492

Could you run your bc file and see whether the bug is fixed?

**Comment by yuleisui** [comment]
@LeoneChen could you confirm my pull request and I would like to fix this issue soon.

**Comment by LeoneChen** [comment]
ok, let me see

**Comment by LeoneChen** [comment]
> @LeoneChen could you confirm my pull request and I would like to fix this issue soon.

Hello, this PR works for me

**Comment by yuleisui** [comment]
> > @LeoneChen could you confirm my pull request and I would like to fix this issue soon.
> 
> Hello, this PR works for me

Thanks!
