### ISSUE TITLE
Question about branchID？

### ISSUE THREAD

**Issue by liushengahn** [SVF-tools/SVF#1493]
Hello, I have recently started working with SVF and would like to use it to write my own analyzer. When I try to get the basic blocks that are control-dependent on another block using CDGBuilder::get_svfdependentOnMap(), I noticed that the map Map<const SVFBasicBlock*, Map<const SVFBasicBlock*, Set<s32_t>>> _svfdependentOnMap uses a Set<s32_t>. I was wondering why this is the case. I would have thought this is usually true or false, and the use of a set might be due to the presence of switch instructions?

https://github.com/SVF-tools/SVF/blob/c82e4e0132a668cd02e7b517ad075ea5cf576994/svf-llvm/lib/ICFGBuilder.cpp#L125
Additionally, I have another question. In the code I referenced, it states that branchID <= 2 can take on three values: 0, 1, and 2. Normally, a Br instruction should only have two outcomes, right? In what situation would a value of 2 appear?

Thank you, I look forward to your response.

**Comment by yuleisui** [comment]
@jumormt could you take a look at the `CDGBuilder::get_svfdependentOnMap()`?

For `branchID ` that is a good finding, it should be 0 and 1 only. Could you make a pull request to fix this?

**Comment by liushengahn** [comment]
I would like to ask another question: Does SVF provide an API to check if two nodes are reachable in the ICFG? And is there an API to trace back and find the set of all nodes that can reach a given node in the SCFG?

**Comment by yuleisui** [comment]
> I would like to ask another question: Does SVF provide an API to check if two nodes are reachable in the ICFG? And is there an API to trace back and find the set of all nodes that can reach a given node in the SCFG?

Slide 4 here: https://github.com/SVF-tools/Software-Security-Analysis/blob/slides/2.lab-control-flow.pdf

**Comment by liushengahn** [comment]
> > I would like to ask another question: Does SVF provide an API to check if two nodes are reachable in the ICFG? And is there an API to trace back and find the set of all nodes that can reach a given node in the SCFG?
> 
> Slide 4 here: https://github.com/SVF-tools/Software-Security-Analysis/blob/slides/2.lab-control-flow.pdf

Thank you, I'll take a look.

**Comment by yuleisui** [comment]
> > I would like to ask another question: Does SVF provide an API to check if two nodes are reachable in the ICFG? And is there an API to trace back and find the set of all nodes that can reach a given node in the SCFG?
> 
> Slide 4 here: https://github.com/SVF-tools/Software-Security-Analysis/blob/slides/2.lab-control-flow.pdf

This is a context-sensitive algorithm and the context insensitive one on slide 54 here https://github.com/SVF-tools/Software-Security-Analysis/blob/slides/2.SVFIR-control-flows.pdf

**Comment by liushengahn** [comment]
Great!

**Comment by jumormt** [comment]
> Hello, I have recently started working with SVF and would like to use it to write my own analyzer. When I try to get the basic blocks that are control-dependent on another block using CDGBuilder::get_svfdependentOnMap(), I noticed that the map Map<const SVFBasicBlock*, Map<const SVFBasicBlock*, Set<s32_t>>> _svfdependentOnMap uses a Set<s32_t>. I was wondering why this is the case. I would have thought this is usually true or false, and the use of a set might be due to the presence of switch instructions?
> 
> https://github.com/SVF-tools/SVF/blob/c82e4e0132a668cd02e7b517ad075ea5cf576994/svf-llvm/lib/ICFGBuilder.cpp#L125
> 
> 
> Additionally, I have another question. In the code I referenced, it states that branchID <= 2 can take on three values: 0, 1, and 2. Normally, a Br instruction should only have two outcomes, right? In what situation would a value of 2 appear?
> Thank you, I look forward to your response.

You are right. The control dependence should consider both branch and switch cases. That's why we need a set of branch ID to handle potential multiple branches stemming from switch instruction.

**Comment by jumormt** [comment]
> I would like to ask an additional question: Does SVF provide an API to check if one node in the ICFG is reachable from another node? And in the SCFG, is there an API to find the set of all nodes that can reach a given node?

@liushengahn SVF does not provide a direct API to query the reachability of two nodes, meaning that you need to write a control flow reachability solver yourself depending on your requirements, for example, context sensitivity.

**Comment by liushengahn** [comment]
thank you
