### ISSUE TITLE
What are the meaning of the colored edges in a svfg?

### ISSUE THREAD

**Issue by KelvinChung2000** [SVF-tools/SVF#1495]
The wiki documentation has mentioned what each of the colored boxes means but has not mentioned what the colored and style of edges do. To me, they do not seem to have any meaning. Is that true?

**Comment by yuleisui** [comment]
Call and return edges do have colours and direct indirect edges are solid and dashed arrows as here:
https://github.com/SVF-tools/SVF/blob/master/svf/lib/Graphs/SVFG.cpp#L1068-L1090

**Comment by KelvinChung2000** [comment]
Thanks for the clarification.
