### ISSUE TITLE
SVF crashes while writing results of Andersen analysis

### ISSUE THREAD

**Issue by HolmesSherlock** [SVF-tools/SVF#150]
While writing Andersen analysis result to a file, SVF hits the assertion and crashes.

```
$ ./wpa -ander -write-ander=write_ander.txt test.bc

Storing pointer analysis results to 'write_ander.txt'...wpa: svf/include/MemoryModel/GenericGraph.h:338: GenericGraph<NodeTy, EdgeTy>::NodeType* GenericGraph<NodeTy, EdgeTy>::getGNode(NodeID) const [with NodeTy = PAGNode; EdgeTy = PAGEdge; GenericGraph<NodeTy, EdgeTy>::NodeType = PAGNode; NodeID = unsigned int]: Assertion `it != IDToNodeMap.end() && "Node not found!"' failed.
Aborted (core dumped)
```

In `PointerAnalysis.cpp:writeToFile()`, when SVF tries to write PAG offset nodes to the file, there are 163 total nodes in the test case (attached). However, the last one has a large `nodeID` (`720000`) which looks like a junk value. Further down in `GepObjPN *gepObjPN = SVFUtil::dyn_cast<GepObjPN>(pag->getPAGNode(i))`, it fails to find the node when the index (`162`) is used to retrieve the node instead of the `nodeID` (`720000`). Upon further investigation, I noticed the node in question is inserted in the PAG during `WPASolver.h:solve()` call.

The source code and the bitcode of the offending test case are attached.

[test.zip](https://github.com/SVF-tools/SVF/files/3636738/test.zip)

**Comment by yuleisui** [comment]
The "write-ander" option has not been used very often after introducing a few more field-sensitive analysis in SVF. The indices of all the GepObjPNs have been put into a separate range zone from normal object nodes as observed by you, however, the "write-ander" has not been changed accordingly. 

The crash has been fixed : https://github.com/SVF-tools/SVF/commit/c80293ca6862caa40450c88cb82fd2f67531f676

Thanks for pointing this out!

Please let me know any question.

**Comment by HolmesSherlock** [comment]
Thanks @yuleisui. A nit-pick is, looks like `NodeID firstGepObjNode = 0;` can be safely removed now.

**Comment by yuleisui** [comment]
Good pick. Fixed
