### ISSUE TITLE
Filed sensitivity on nested struct

### ISSUE THREAD

**Issue by FFGGSSJJ** [SVF-tools/SVF#1502]
Hi! I am wondering if SVF's filed-sensitive pointer analysis currently works on nested struct? For instance, given the following example:
```cpp
/* A */ 
class ClassA {
public:
    ClassA(int i): _B(i){};
    ClassB& getB();
private:
    ClassB _B;
    int _a;
};

/* B */
class ClassB{
public:
    ClassB(int i): _C(i){};
    ClassC& getC();
private:
    ClassC _C;

};

/* C */
class ClassC{
public:
    ClassC(int i);
    void fooC();
private:
    int _c;

};

int main(){
    ClassA a(1);
    a.getB().getC().fooC();
}
```

I have tested on this example and it turns out that the field sensitivity only works for the first level. There will be GepObj for a._B and a._a, but the nested members in a._B will all point to the GepObj of a._B. 

I have tried to read the source code to figure out the idea but I barely get it. Can you suggest if it is possible to make the nested struct also points to different GepObj? Thank you!

**Comment by yuleisui** [comment]
I am not sure whether this is due to C++ APIs. Would you make this a C code and try to see the field-sensitivity in nested structs? You could send us a c file for me to have a look and better to add a MAYALIAS stub function (like https://github.com/SVF-tools/Test-Suite/blob/8ae1178f5dea12a83dee539e114a7e045494414d/src/basic_c_tests/struct-assignment-direct.c#L21).

**Comment by FFGGSSJJ** [comment]
> I am not sure whether this is due to C++ APIs. Would you make this a C code and try to see the field-sensitivity in nested structs? You could send us a c file for me to have a look and better to add a MAYALIAS stub function (like https://github.com/SVF-tools/Test-Suite/blob/8ae1178f5dea12a83dee539e114a7e045494414d/src/basic_c_tests/struct-assignment-direct.c#L21).

Thank you for your reply. I rewrite it in both C and C++, and it turns out that it is because I am using Class instance instead of Class pointer in the nested member fields. It seems that the nested struct is being flattened, i.e. there will be a FIObj for a with GepObj for _a, _b and _c. I attached the example for it. Do you think if it is possible to avoid this behavior?
[classes.cpp.txt](https://github.com/user-attachments/files/16332365/classes.cpp.txt)

**Comment by yuleisui** [comment]
I didn't get your point. For a C test, Is SVF's result correct or not for a nested struct?

**Comment by FFGGSSJJ** [comment]
> I didn't get your point. For a C test, Is SVF's result correct or not for a nested struct?

Sorry for the ambiguity. I conducted tests in C with the following 2 formats:
1. I use pointer for nested structs. In this case, SVF works fine and will generate correct results.
```cpp
struct structA {
    structB* _B;
    int _a;
};

int main() {
    structB b;
    structA a;

    a._B = &b;
    a._a = 1;
    a._B->_b = 1;
    a._B->_b++;
}
```
2. I didn't use pointer for nested structs. In this case, I found that _B in structA seems to be flattened as there will be a GepObj generated for a._B._b whose base object is the FIObj for a. 
```cpp
struct structA {
    structB _B;
    int _a;
};

int main() {
    structB b;
    structA a;

    a._B = b;
    a._a = 1;
    a._B._b = 1;
    a._B._b++;
}
```
As I am interested in distinguishing the access to nested field members in second case, I wonder if there is any way to avoid this flattening?

**Comment by yuleisui** [comment]
Did SVF’s pointer analysis produce correct results for both cases ?

**Comment by FFGGSSJJ** [comment]
> Did SVF’s pointer analysis produce correct results for both cases ?

Yea I think for pointer analysis it is correct.

**Comment by yuleisui** [comment]
Nested structs are flattened for points-to analysis but you could use this API to get the original element types: https://github.com/SVF-tools/SVF/blob/410517866a17e821fe5b6dcbdbc5f99b83b5823d/svf/lib/SVFIR/SymbolTableInfo.cpp#L205

**Comment by FFGGSSJJ** [comment]
> Nested structs are flattened for points-to analysis but you could use this API to get the original element types:
> 
> https://github.com/SVF-tools/SVF/blob/410517866a17e821fe5b6dcbdbc5f99b83b5823d/svf/lib/SVFIR/SymbolTableInfo.cpp#L205

Thank you for your reply. I am currently using the following code and I wonder if it is a reasonable way to use it?
```cpp
auto* flatternTy = gepNode->getType()->toString();
auto* baseNode = pag_->getGNode(gepNode->getBaseNode());
auto* originalTy = pag_->getSymbolInfo()->getOriginalElemType(baseNode->getType(), gepNode->getConstantFieldIdx());
if (ty)
     SVFUtil::outs() << originalTy->toString();
```

**Comment by FFGGSSJJ** [comment]
Sorry for bothering again. I conducted some more tests with following code:
```cpp
typedef struct structC {
    int _c;
    int _d;
} structC;

typedef struct structB {
    structC _C;
    int _b;
} structB;

typedef struct structA {
    structB _B;
    int _a;
} structA;

int main() {
    structC c;
    structB b;
    structA a;

    b._C = c;
    a._B = b;
    a._B._C._c++;
    a._B._C._d++;
}
```
And I checked the points to set of a few pointers in PAG and I found the following:
![pag](https://github.com/user-attachments/assets/c000b899-11d0-4f8b-9ff3-929cc7fe1dae)

This part of PAG corresponds to the last 2 lines of code in the example. I can understand why the green points to a different GepObj, but the red circle confused me. Why does the red circle contain all these pointers? Could you maybe explain a little about how the flatten works in SVF? Thank you!

**Comment by FFGGSSJJ** [comment]
I think I have got the idea, which should be related to how C/C++ pointers work. I will close the issue and thank you! :)
