### ISSUE TITLE
SVF gives wrong result when encountering different namespaces

### ISSUE THREAD

**Issue by zz-fz-john** [SVF-tools/SVF#1503]
I want to get call graph using the comand that is "wpa -ander -dump-callgraph testSVF.ll",this file has two different namespace ,here is the code
```

#include <iostream>
//#include <pthread.h>
//#include <stdio.h>
#include "CFeventSingleThread.h"
namespace AP_HAL {
    class Semaphore;
}



class AP_HAL::Semaphore {
public:

    Semaphore() {}

    // do not allow copying
    Semaphore(const Semaphore &other) = delete;
    Semaphore &operator=(const Semaphore&) = delete;
    
    virtual bool give() = 0;
    virtual ~Semaphore(void) {}
};



class WithSemaphore {
public:
    WithSemaphore(AP_HAL::Semaphore *mtx, uint32_t line);
    WithSemaphore(AP_HAL::Semaphore &mtx, uint32_t line);

    ~WithSemaphore();
private:
    AP_HAL::Semaphore &_mtx;
};
/*
  implement WithSemaphore class for WITH_SEMAPHORE() support
 */
WithSemaphore::WithSemaphore(AP_HAL::Semaphore *mtx, uint32_t line) :
    WithSemaphore(*mtx, line)
{}

WithSemaphore::WithSemaphore(AP_HAL::Semaphore &mtx, uint32_t line) :
    _mtx(mtx)
{

    _mtx.give();

}

WithSemaphore::~WithSemaphore()
{
    _mtx.give();
}
namespace Linux {

class Semaphore : public AP_HAL::Semaphore {
public:
    Semaphore();
    bool give() override;

};

}
using namespace Linux;
bool Semaphore::give()
{
    return true;
}
int main(){
    Semaphore mutext;
  WithSemaphore a=WithSemaphore(&mutext,1);
}
```
the generated call-graph is :
![image](https://github.com/user-attachments/assets/1413822b-b110-4a4d-857b-cccef8e5f9a1)
 I think there should be an edge between WithSemaphore and Linux::Semaphore::give().
May be SVF has some problem in handling namespace

**Comment by yuleisui** [comment]
Thanks for reporting. This looks to be a good case. Could you pls make this test as small as possible for us to debug and figure the issue.

**Comment by zz-fz-john** [comment]
> Thanks for reporting. This looks to be a good case. Could you pls make this test as small as possible for us to debug and figure the issue.

Of  course!here is the testSVF.cpp
```

#include <iostream>
using namespace std;
namespace AP_HAL {
    class Semaphore;
}
class AP_HAL::Semaphore {
public:
        virtual int give() = 0;
};
class WithSemaphore {
public:
    WithSemaphore(AP_HAL::Semaphore &mtx, uint32_t line);
private:
    AP_HAL::Semaphore &_mtx;
};
WithSemaphore::WithSemaphore(AP_HAL::Semaphore &mtx, uint32_t line) :
    _mtx(mtx)
{

    int a =_mtx.give();
    cout<<a<<endl;

}
namespace Linux {

class Semaphore : public AP_HAL::Semaphore {
public:
    Semaphore(){
        ;
    }
    int give() override;

};

}
using namespace Linux;

int Linux::Semaphore::give()
{
    return 2;
}


int main(){
    Semaphore mutext;
  WithSemaphore a=WithSemaphore(mutext,1);
}

```
there is another question,when I use SVF2.6 based on LLVM-13.0 and command "wpa -ander -v-call-cha -dump-callgraph testSVF.ll.",the result seem to be true.
and if I run analysis without option "-v-call-cha",the result still be true.
here is the call-graph generated by SVF2.6
![2024-07-23 20-58-16屏幕截图](https://github.com/user-attachments/assets/3e74e6ca-21fe-45c7-9a4a-bd39f5f024d4)
But when I used SVF3.0 based on LLVM-16.0 and command "wpa -ander -v-call-cha -dump-callgraph testSVF.ll.",the result seem to be wrong.
here is the call-graph generated by svf3.0
![image](https://github.com/user-attachments/assets/e68f9c09-a895-4ded-b2f0-656c77c75e75)

**Comment by zz-fz-john** [comment]
I think mey be is the object type reference processing have some problem ,because llvm-13.0 didn't use  opaque pointers,but in ir genertated by llvm-16.0,there are lots of ptr instead of "class xxx *".I will try my best to find about the reason and fix it .

**Comment by yuleisui** [comment]
@jumormt this looks to be the issue in object type inference

**Comment by zz-fz-john** [comment]
I recently discovered that the cause of this bug seems not to be due to namespaces.I removed the namespace for all classes ,but svf3.0 still give me a wrong result.
Here is the code without using namespace 
```

#include <iostream>
using namespace std;
// namespace AP_HAL {
//     class Semaphore1;
// }
class Semaphore1 {
public:
        int a =0;
        ~Semaphore1(){}
        virtual int give() {
            ;
        }
};

//namespace Linux {

class Semaphore : public Semaphore1 {
public:
    int c=0;
    Semaphore(){
        ;
    }
    int give() ;

};

//}
//using namespace Linux;

int Semaphore::give()
{
    return 2;
}
class WithSemaphore {
public:
    int b=0;
    WithSemaphore(Semaphore1 *mtx, uint32_t line);
private:
    Semaphore1 *_mtx;
};
WithSemaphore::WithSemaphore(Semaphore1 *mtx, uint32_t line) :
    _mtx(mtx)
{

    int a =mtx->give();
    cout<<a<<endl;

}

int main(){
    Semaphore1 mutext=Semaphore();
  WithSemaphore *a=new WithSemaphore(&mutext,1);
}

```
Here is the callgraph.
[testSVF.zip](https://github.com/user-attachments/files/16517559/testSVF.zip)

**Comment by jumormt** [comment]
Yep, I believe the namespace is fine. This bug is related to the object type inference for c++ indirect call which is a little bit complicated regarding this case because the function `give' is a dynamic (indirect) call residing in the constructor of the class `WithSemaphore`. If you inspect its ir, you will find it challenging to identify the precise type inference site that indicates the correct type of the object that `mtx` points to. I'll try to find a solution and get you back once I figure it out.

**Comment by jumormt** [comment]
Hi @zz-fz-john Can you test PR #1514 which should be able to fix this issue and connect the indirect call edge? We conservatively collect class names in the parameters, which should be fine because we will do type matching when constructing CHG. Let me know if you encounter any other problems.

**Comment by jumormt** [comment]
Here is the call graph:
![graphviz (7)](https://github.com/user-attachments/assets/2a4842f8-2ba8-40ad-bc79-39eee6973bb3)

**Comment by zz-fz-john** [comment]
> Hi @zz-fz-john Can you test PR #1514 which should be able to fix this issue and connect the indirect call edge? We conservatively collect class names in the parameters, which should be fine because we will do type matching when constructing CHG. Let me know if you encounter any other problems.

Thank you for fixing this bug. If you use the patch, there will be no problem when processing the namespace. However, if the namespace is not used, there will still be missing edges.
here is the test code：
```

#include <iostream>
using namespace std;
// namespace AP_HAL {
//     class Semaphore1;
// }
class Semaphore_father {
public:
        int a =0;
        ~Semaphore_father(){}
        virtual int give()=0;
};

//namespace Linux {

class Semaphore : public Semaphore_father {
public:
    int c=0;
    Semaphore(){
        ;
    }
    int give() ;

};

//}
//using namespace Linux;

int Semaphore::give()
{
    return 2;
}
class WithSemaphore {
public:
    int b=0;
    WithSemaphore(Semaphore_father &mtx, uint32_t line);
private:
    Semaphore_father &_mtx;
};
WithSemaphore::WithSemaphore(Semaphore_father &mtx, uint32_t line) :
    _mtx(mtx)
{

    int a =mtx.give();
    cout<<a<<endl;

}

int main(){
    Semaphore mutext;
  WithSemaphore a= WithSemaphore(mutext,1);
}

```

There is still no edge from WithSemaphore::WithSemaphore(Semaphore_father &mtx, uint32_t line) to Semaphore::give() in the generated call-graph
here is the call graph:
![2024-08-15 14-02-16屏幕截图](https://github.com/user-attachments/assets/92ee59cd-390a-44d3-9d2e-ac5c56dd071a)

**Comment by jumormt** [comment]
@zz-fz-john It works fine on my side. Here's the callgraph:
![callgraph](https://github.com/user-attachments/assets/6d7188be-1b06-4482-9022-c5a6126abe72)

**Comment by jumormt** [comment]
> @zz-fz-john It works fine on my side. Here's the callgraph: ![callgraph](https://private-user-images.githubusercontent.com/44386076/358143556-6d7188be-1b06-4482-9022-c5a6126abe72.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDQ4MjEsIm5iZiI6MTcyMzcwNDUyMSwicGF0aCI6Ii80NDM4NjA3Ni8zNTgxNDM1NTYtNmQ3MTg4YmUtMWIwNi00NDgyLTkwMjItYzVhNjEyNmFiZTcyLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA2NDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjM2M1ODQ2ZmQ4NmJmNzhjZDI1ZGQxYzY5YzIyMDJmZmE1ZTRjMTkyNWM3MTE4M2Y3YzY0OThhMzQ0ZWE4NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ffaRq-v2y7jsGzHmELYOd5vtktbB4SoBE19bM5Yrcvo)

The command is simply `wpa -ander -dump-callgraph /path/to/your/bc`

**Comment by zz-fz-john** [comment]
> > Hi @zz-fz-john Can you test PR #1514 which should be able to fix this issue and connect the indirect call edge? We conservatively collect class names in the parameters, which should be fine because we will do type matching when constructing CHG. Let me know if you encounter any other problems.
> 
> Thank you for fixing this bug. If you use the patch, there will be no problem when processing the namespace. However, if the namespace is not used, there will still be missing edges. here is the test code：
> 
> ```
> 
> #include <iostream>
> using namespace std;
> // namespace AP_HAL {
> //     class Semaphore1;
> // }
> class Semaphore_father {
> public:
>         int a =0;
>         ~Semaphore_father(){}
>         virtual int give()=0;
> };
> 
> //namespace Linux {
> 
> class Semaphore : public Semaphore_father {
> public:
>     int c=0;
>     Semaphore(){
>         ;
>     }
>     int give() ;
> 
> };
> 
> //}
> //using namespace Linux;
> 
> int Semaphore::give()
> {
>     return 2;
> }
> class WithSemaphore {
> public:
>     int b=0;
>     WithSemaphore(Semaphore_father &mtx, uint32_t line);
> private:
>     Semaphore_father &_mtx;
> };
> WithSemaphore::WithSemaphore(Semaphore_father &mtx, uint32_t line) :
>     _mtx(mtx)
> {
> 
>     int a =mtx.give();
>     cout<<a<<endl;
> 
> }
> 
> int main(){
>     Semaphore mutext;
>   WithSemaphore a= WithSemaphore(mutext,1);
> }
> ```
> 
> There is still no edge from WithSemaphore::WithSemaphore(Semaphore_father &mtx, uint32_t line) to Semaphore::give() in the generated call-graph here is the call graph: ![2024-08-15 14-02-16屏幕截图](https://private-user-images.githubusercontent.com/46997229/358135210-92ee59cd-390a-44d3-9d2e-ac5c56dd071a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDQyNDUsIm5iZiI6MTcyMzcwMzk0NSwicGF0aCI6Ii80Njk5NzIyOS8zNTgxMzUyMTAtOTJlZTU5Y2QtMzkwYS00NGQzLTlkMmUtYWM1YzU2ZGQwNzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA2MzkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NDBiNTU5YWUxY2RhNWJlNjkxZWJhOGIwNmNjMDkyMzUwZGZiNzI0MzkyMTNmZGVhMjIzZDExODU1NDk4MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D77vglYwQAMKy9rMcpSIM1bkDlTNFl8skM9olcJoghk)

when I use the -o0 optimization level to generate the IR ,and then use svf to generate call graph ,the reult is wrong.
But I use the command "opt -S -passes="globalopt" -o testSVF_modify.ll testSVF.ll" to optimize the IR ,then I used svf to analysis testSVF_modify.ll.  The result is true.
So I think it's possible that the optimization level is causing the error.
In testSVF.ll,The instruction to call the WithSemaphore function is
```
%6 = invoke noundef ptr @_ZN13WithSemaphoreC1ER16Semaphore_fatherj(ptr noundef nonnull align 4 dereferenceable(8) %2, ptr noundef nonnull align 4 dereferenceable(8) %1, i32 noundef 1)
``` 
The definition of _ZN13WithSemaphoreC1ER16Semaphore_fatherj is
```
@_ZN13WithSemaphoreC1ER16Semaphore_fatherj = dso_local unnamed_addr alias ptr (ptr, ptr, i32), ptr @_ZN13WithSemaphoreC2ER16Semaphore_fatherj
```
In testSVF_modify.ll ,The instruction to call the WithSemaphore function is:
```
%6 = invoke noundef ptr @_ZN13WithSemaphoreC2ER16Semaphore_fatherj(ptr noundef nonnull align 4 dereferenceable(8) %2, ptr noundef nonnull align 4 dereferenceable(8) %1, i32 noundef 1)
```
and the  definition of _ZN13WithSemaphoreC2ER16Semaphore_fatherj  is：
```
define dso_local noundef ptr @_ZN13WithSemaphoreC2ER16Semaphore_fatherj(ptr noundef nonnull returned align 4 dereferenceable(8) %0, ptr noundef nonnull align 4 dereferenceable(8) %1, i32 noundef %2) unnamed_addr #5 align 2 {
  %4 = alloca ptr, align 4
  %5 = alloca ptr, align 4
  %6 = alloca i32, align 4
  %7 = alloca i32, align 4
  store ptr %0, ptr %4, align 4
  store ptr %1, ptr %5, align 4
  store i32 %2, ptr %6, align 4
  %8 = load ptr, ptr %4, align 4
  %9 = getelementptr inbounds %class.WithSemaphore, ptr %8, i32 0, i32 0
  store i32 0, ptr %9, align 4
  %10 = getelementptr inbounds %class.WithSemaphore, ptr %8, i32 0, i32 1
  %11 = load ptr, ptr %5, align 4
  store ptr %11, ptr %10, align 4
  %12 = getelementptr inbounds %class.WithSemaphore, ptr %8, i32 0, i32 1
  %13 = load ptr, ptr %12, align 4
  %14 = load ptr, ptr %13, align 4
  %15 = getelementptr inbounds ptr, ptr %14, i64 0
  %16 = load ptr, ptr %15, align 4
  %17 = call noundef i32 %16(ptr noundef nonnull align 4 dereferenceable(8) %13)
  store i32 %17, ptr %7, align 4
  %18 = load i32, ptr %7, align 4
  %19 = call noundef nonnull align 4 dereferenceable(4) ptr @_ZNSolsEi(ptr noundef nonnull align 4 dereferenceable(4) @_ZSt4cout, i32 noundef %18)
  %20 = call noundef nonnull align 4 dereferenceable(4) ptr @_ZNSolsEPFRSoS_E(ptr noundef nonnull align 4 dereferenceable(4) %19, ptr noundef @_ZSt4endlIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_)
  ret ptr %8
}
```
So I think it may be an error caused by the optimization level，but it doesn't matter, I can use globalopt pass to optimize the IR,and then I could get the true result .
Finally thank you very much for helping me solve this problem

**Comment by jumormt** [comment]
Do you mean it fails without optimization? I ran it with o0 it stills works: clang++ -g -S -c -Xclang -disable-O0-optnone -fno-discard-value-names -emit-llvm "$1" -o "$ll_file". It also works fine if you optimize the bitcode: opt -S -p=mem2reg "$ll_file" -o "$ll_file".

**Comment by zz-fz-john** [comment]
Sorry, this is due to the parameter matching I added in the svf, which filtered out _ZN13WithSemaphoreC1ER16Semaphore_fatherj. So there is no edge from main to _ZN13WithSemaphoreC1ER16Semaphore_fatherj in the call graph. I restored the svf to its original version and found that your patch worked.
Thank you for taking the time to fix this bug

**Comment by jumormt** [comment]
@zz-fz-john No worries. Good to hear~
