### ISSUE TITLE
Is it possible to use parsed CLI args with `Options` in Util headers?

### ISSUE THREAD

**Issue by cubicYYY** [SVF-tools/SVF#1516]
I'm trying to add some logic for logging in `svf/include/SparseBitVector.h` with my custom CLI argument in `SVF::Options`.
However, directly including `Util/Options.h` does not work. It just resulted in compilation errors. Many symbols are not defined, maybe due to declaration order issues...?

So, what is the correct way to get CLI arguments if we are not in a "top-level" program(e.g., WPA) but a Util lib instead?

**Comment by yuleisui** [comment]
Not sure, what you would like to achieve. You will need to follow the compilation errors to figure it out.

**Comment by cubicYYY** [comment]
> Not sure, what you would like to achieve. You will need to follow the compilation errors to figure it out.

The problem is that I cannot include `Options.h` in `Util/SparseBitVector.h` because of some circular dependencies like:
SparseBitVector.h -> Options.h -> PTAStat.h -> SVFValue.h -> SVFType.h -> SparseBitVector.h -> ...

**Comment by yuleisui** [comment]
You can't do that. As the header `Options.h` needs to be included in the cpp.
