### ISSUE TITLE
Incorrect function call in SVF

### ISSUE THREAD

**Issue by nix7965** [SVF-tools/SVF#157]
Hi, SVF developers.

At https://github.com/SVF-tools/SVF/blob/master/include/Util/ThreadAPI.h#L159
I think it must call "getActualParmAtForkSite". 
Look like a small mistake. But, it may generate a wrong result.
Is that correct?

**Comment by yuleisui** [comment]
You are right. Would you be able to submit a patch to fix it? Thanks

**Comment by nix7965** [comment]
@kswgit will do it soon. Thank you for your confirmation.
