### ISSUE TITLE
Query Mod-Ref Analysis

### ISSUE THREAD

**Issue by FrancisYL** [SVF-tools/SVF#161]
Hello,

In the [SVF Design](https://github.com/SVF-tools/SVF/wiki/SVF-Design) page, it mentions that in the first stage of Value-Flow Construction

> a lightweight **Mod-Ref Analysis** to capture inter-procedural reference and modification side-effects of program variables.

Does SVF provide this Mod-Ref analysis query API? For instance, a memory location is read or written by another instruction. If not, will it be supported in the future?

**Comment by yuleisui** [comment]
SVFG naturally supports what you want. Each node on SVFG represents a statement (PAGEdge) and each edge between two nodes represent their dependence relations.

**Comment by FrancisYL** [comment]
Hi Yulei,

I'm trying to implement Mod-Ref Analysis APIs based on SVF and am glad to hear that SVFG naturally supports this. Could you share more thoughts and resources (internal modules, apis, etc.) on where to start? I was recently reading your paper [SVF: Interprocedural Static Value-Flow Analysis in LLVM](https://yuleisui.github.io/publications/cc16.pdf) in the purpose of better understanding SVFG, some more suggestions on the implementation level would be really appreciated!
