### ISSUE TITLE
Add publications and systems using SVF in the website http://svf-tools.github.io/SVF/

### ISSUE THREAD

**Issue by rainoftime** [SVF-tools/SVF#166]
Thanks for making SVF open-source!
Just a suggestion: I think the website http://svf-tools.github.io/SVF/ can list some third-party publications/systems that use SVF, similar to the KLEE website (https://klee.github.io/publications/).
Then, the users of SVF can learn more about the utility and usage of it.

The following are some examples.
- Hawkeye: Towards a Desired Directed Grey-box Fuzzer, CCS'18
- Chopped Symbolic Execution, ICSE'18
- Origin-sensitive control-flow integrity, USENIX Security'19

**Comment by yuleisui** [comment]
Reference added https://github.com/SVF-tools/SVF/commit/9917aaa466bba65d006c81e6525cd2546511e90b.

Thanks for pointing out~
