### ISSUE TITLE
gepId overflows for large programs

### ISSUE THREAD

**Issue by holmessherlock** [SVF-tools/SVF#173]
While constructing PAG for large programs, `gepId`, which is of type `NodeID`, [overflows](https://github.com/SVF-tools/SVF/blob/master/lib/MemoryModel/PAG.cpp#L347).

**Comment by yuleisui** [comment]
Thanks for reporting this. @kisslune  can you please take a look at this?

**Comment by holmessherlock** [comment]
@kisslune Did you get a chance to look into the issue?

**Comment by yuleisui** [comment]
@holmessherlock could you please take a look at the pull request and check whether it will fix the overflow problem?

https://github.com/SVF-tools/SVF/pull/175/files

**Comment by kisslune** [comment]
Hi @holmessherlock, 

Sorry for contacting you so late because of the network problem.

You can try a version from: https://github.com/kisslune/SVF-release.git 
to check whether the issue is solved.

If the problem still exists, please contact me.

Thanks.

**Comment by holmessherlock** [comment]
Looks like it works! Thanks a lot.
