### ISSUE TITLE
ref contains all the mod in Mod-Ref Analysis

### ISSUE THREAD

**Issue by FrancisYL** [SVF-tools/SVF#176]
I'm implementing interprocedural getModRefInfo APIs based on the mod-ref results generated by SVF and found one line of code in [MSSA/MemRegion.cpp](https://github.com/SVF-tools/SVF/blob/master/lib/MSSA/MemRegion.cpp#L520) decreases the accuracy.

Below is an example.
```C
int get_value(int* p, int a) {
  *p = a;
  return a;
}

int main(int argc, const char* argv[]) {
  int a = argc;
  int* p = &a;

  int value = get_value(p, a);

  printf("%d", value);
  return 0;
}
```

the memory location pointed by `p` is only modified in `get_value`, not referenced. A **Mod** result is expected when querying the mod-ref result between callsite `get_value(p, a)` and pointer `p` through two attributes `csToRefsMap` and `csToModsMap`. However, `ref |= mod` assigns all the mod to ref of this callsite, which leads to a less accurate result **ModRef**.

After removing `ref |= mod`, the accuracy increases and **Mod** result becomes possible. It also affects the MSSA generated afterward. Only **χ** will be annotated around callsite if there's only an indirect mod but no ref of the memory region. Given an **χ** represents both use and def of a memory region semantically, removing the redundant **μ** around the callsite seems reasonable.

I'm not sure is any upper client application gets affected so I raised this issue for further inspection. Thank you.

**Comment by yuleisui** [comment]
In fact, you have answered your question. Any modification, e.g., x = \chi(x) represents both a mod and use of x.

For a callsite,  \mu(x) often annotated before a callsite denotes an "invisible" passing parameter for an address-taken variable x. Missing \mu will not be able to pass variable x into the callee function. x = \chi(x) annotated after the callsite denotes whether we will take the old value of x from the caller, or a new value of x modified from callee.

**Comment by yuleisui** [comment]
Thanks!
