### ISSUE TITLE
setup guide for CMAKE

### ISSUE THREAD

**Issue by taxic** [SVF-tools/SVF#183]
Hi,
Sometimes, the build process needs to specify the version of CXX_COMPILER and C_COMPILER.
Instead of using directly
``
cmake ../
``
try commands like
``
cmake -DCMAKE_CXX_COMPILER=llvm-3.8.0.src/llvm-3.8.0.obj/bin/clang++ -DCMAKE_C_COMPILER=llvm-3.8.0.src/llvm-3.8.0.obj/bin/clang -DLLVM_DIR=llvm-3.8.0.src/llvm-3.8.0.obj/bin ..
``
where 3.8.0 can be the compatible version of LLVM.

If this is helpful, hopefully this can be added to corresponding Wiki page.

**Comment by yuleisui** [comment]
Thanks, just added to Setup Guide.
