### ISSUE TITLE
Is there any means to map a PAG NodeID back to the IR instruction it is generated from?

### ISSUE THREAD

**Issue by holmessherlock** [SVF-tools/SVF#184]
With `-nander -print-pts` switch, SVF prints out the points-to relations in terms of PAG NodeIDs. Right now, I have a "hacky" mechanism in place to get the LLVM IR instruction that generated the PAG node. Is there any elegant way out to retrieve the same information from SVF? In other words, once the points-to relations are generated in terms of PAG nodes (e.g., see the example below), what is the suggested workflow to verify those relations manually?

```
------------------------------------------
----------------------------------------------
##<retval> Source Loc: 
Ptr 14      PointsTo: { 15 }

!!Target NodeID 15   [<retval> Source Loc: ]
----------------------------------------------
----------------------------------------------
```

**Comment by mbarbar** [comment]
If you're purpose is only to check things out manually, and you're okay with long text dumps the easy solution is:
Convert the following two lines,
https://github.com/SVF-tools/SVF/blob/dde8e4ca7b139f95290a1775a6afdbb1dd1cb90d/lib/MemoryModel/PointerAnalysis.cpp#L486
https://github.com/SVF-tools/SVF/blob/dde8e4ca7b139f95290a1775a6afdbb1dd1cb90d/lib/MemoryModel/PointerAnalysis.cpp#L516

to
```
outs() << "##<";
node->getValue()->print(outs());
outs() << "> ";
```
This gives me, with `-print-all-pts`, stuff like:
```
----------------------------------------------
##<  %7 = load i32*, i32** %y.addr, align 8, !dbg !285, !tbaa !275> Source Loc: ln: 13 fl: virtual2.cpp
Ptr 492 		PointsTo: { 332 334 }

!!Target NodeID 332	 [##<  %i = alloca i32, align 4, !ctir !8> Source Loc: ln: 18 fl: virtual2.cpp] 
!!Target NodeID 334	 [##<  %j = alloca i32, align 4, !ctir !8> Source Loc: ln: 18 fl: virtual2.cpp] 
```
```
----------------------------------------------
##<  %11 = load i32*, i32** %q, align 8, !dbg !24, !tbaa !17> Source Loc: ln: 10 fl: xmalloc_1.c
Ptr 341 		PointsTo: { 307 345 }

!!Target NodeID 307	 [##<  %call = call noalias i8* @malloc(i64 %0) #4, !dbg !25> Source Loc: ln: 4 fl: xmalloc_1.c] 
!!Target NodeID 345	 [##<  %call = call noalias i8* @malloc(i64 %0) #4, !dbg !25> Source Loc: ln: 4 fl: xmalloc_1.c] 
```

Is that what you're after?

**Comment by holmessherlock** [comment]
Thanks!
