### ISSUE TITLE
MSSA misses to include struct object through function call

### ISSUE THREAD

**Issue by FrancisYL** [SVF-tools/SVF#188]
I have the following program which passes a Node pointer `n` and appends it with a new value to the Node pointed by `n`
```C++
struct Node {
  int value;
  Node *next;
};

void appendNode(Node *n, int newValue) {
  Node* newNode = (Node *)malloc(sizeof(Node));
  newNode->value = newValue;
  newNode->next = NULL;
  n->next = newNode;
}

int main(int argc, char **argv) {
  Node *n = (Node *)malloc(sizeof(Node));
  n->value = argc;
  n->next = NULL;
  appendNode(n, 10);

  return 0;
}
```

However, the MSSA generated fails to catch the pass of Node object after casting of pointer `n` in the bitcode.
```
==========FUNCTION: main==========
2V_1 = ENCHI(MR_2V_0) 	pts{30 }
4V_1 = ENCHI(MR_4V_0) 	pts{1030 }
6V_1 = ENCHI(MR_6V_0) 	pts{10 1010 }

CALMU(MR_2V_1) 	pts{30 }
  %3 = call noalias i8* @malloc(i64 16) #3
2V_2 = CALCHI(MR_2V_1) 	pts{30 }

  %4 = bitcast i8* %3 to %struct.Node*
  %5 = getelementptr inbounds %struct.Node, %struct.Node* %4, i32 0, i32 0
  store i32 %0, i32* %5, align 8
2V_3 = STCHI(MR_2V_2) 	pts{30 }

  %6 = getelementptr inbounds %struct.Node, %struct.Node* %4, i32 0, i32 1
  store %struct.Node* null, %struct.Node** %6, align 8
4V_2 = STCHI(MR_4V_1) 	pts{1030 }

CALMU(MR_4V_2) 	pts{1030 }
CALMU(MR_6V_1) 	pts{10 1010 }
  call void @_Z10appendNodeP4Nodei(%struct.Node* %4, i32 10)
4V_3 = CALCHI(MR_4V_2) 	pts{1030 }
6V_2 = CALCHI(MR_6V_1) 	pts{10 1010 }

  ret i32 0
RETMU(MR_2V_3) 	pts{30 }
RETMU(MR_4V_3) 	pts{1030 }
RETMU(MR_6V_2) 	pts{10 1010 }
```

Could you please take a look at this bug? many thanks!

**Comment by yuleisui** [comment]
Can you elaborate a bit more about this, or you may wish to propose a solution?

**Comment by FrancisYL** [comment]
I was querying getModRefInfo between pointer `n` and callsite `appendNode(n, 10)` and get the result NoModRef (I'm expecting the result Mod since `n->next = newNode` modifies the second field of object pointed by `n`).

I found in the MSSA that the Node's first and second fields are treated as two separate memory versions instead of one version with two objects. So only object 1030 passes into the callsite appendNode(), which results in a NoModRef since pointer `n` only points to object 30.

I use the following command to generate the MSSA
```bash
clang++ -O0 -c -Xclang -disable-O0-optnone -emit-llvm program.cpp -o program.bc
opt -mem2reg program.bc -o program.opt
wpa -ander -svfg -dump-mssa program.opt
```
and got the full MSSA as follows
```
==========FUNCTION: _Z10appendNodeP4Nodei==========
8V_1 = ENCHI(MR_8V_0) 	pts{10 }
10V_1 = ENCHI(MR_10V_0) 	pts{1010 }
4V_1 = ENCHI(MR_4V_0) 	pts{1030 }

CALMU(MR_8V_1) 	pts{10 }
  %3 = call noalias i8* @malloc(i64 16) #3
8V_2 = CALCHI(MR_8V_1) 	pts{10 }

  %4 = bitcast i8* %3 to %struct.Node*
  %5 = getelementptr inbounds %struct.Node, %struct.Node* %4, i32 0, i32 0
  store i32 %1, i32* %5, align 8
8V_3 = STCHI(MR_8V_2) 	pts{10 }

  %6 = getelementptr inbounds %struct.Node, %struct.Node* %4, i32 0, i32 1
  store %struct.Node* null, %struct.Node** %6, align 8
10V_2 = STCHI(MR_10V_1) 	pts{1010 }

  %7 = getelementptr inbounds %struct.Node, %struct.Node* %0, i32 0, i32 1
  store %struct.Node* %4, %struct.Node** %7, align 8
4V_2 = STCHI(MR_4V_1) 	pts{1030 }

  ret void
RETMU(MR_8V_3) 	pts{10 }
RETMU(MR_10V_2) 	pts{1010 }
RETMU(MR_4V_2) 	pts{1030 }
==========FUNCTION: malloc==========
==========FUNCTION: main==========
2V_1 = ENCHI(MR_2V_0) 	pts{30 }
4V_1 = ENCHI(MR_4V_0) 	pts{1030 }
6V_1 = ENCHI(MR_6V_0) 	pts{10 1010 }

CALMU(MR_2V_1) 	pts{30 }
  %3 = call noalias i8* @malloc(i64 16) #3
2V_2 = CALCHI(MR_2V_1) 	pts{30 }

  %4 = bitcast i8* %3 to %struct.Node*
  %5 = getelementptr inbounds %struct.Node, %struct.Node* %4, i32 0, i32 0
  store i32 %0, i32* %5, align 8
2V_3 = STCHI(MR_2V_2) 	pts{30 }

  %6 = getelementptr inbounds %struct.Node, %struct.Node* %4, i32 0, i32 1
  store %struct.Node* null, %struct.Node** %6, align 8
4V_2 = STCHI(MR_4V_1) 	pts{1030 }

CALMU(MR_4V_2) 	pts{1030 }
CALMU(MR_6V_1) 	pts{10 1010 }
  call void @_Z10appendNodeP4Nodei(%struct.Node* %4, i32 10)
4V_3 = CALCHI(MR_4V_2) 	pts{1030 }
6V_2 = CALCHI(MR_6V_1) 	pts{10 1010 }

  ret i32 0
RETMU(MR_2V_3) 	pts{30 }
RETMU(MR_4V_3) 	pts{1030 }
RETMU(MR_6V_2) 	pts{10 1010 }
```

**Comment by FrancisYL** [comment]
One more question is that in function `main`, the other object pointed by pointer `newNode` is introduced as `6V_1 = ENCHI(MR_6V_0) 	pts{10 1010 }` however in `appendNode`, the object is introduced as `8V_1 = ENCHI(MR_8V_0) 	pts{10 }` and `10V_1 = ENCHI(MR_10V_0) 	pts{1010 }`, this inconsistency in memory versioning confuses me also.

**Comment by yuleisui** [comment]
I had a look at your case. I think SVF generates the correct SSA form.

First, let us look at your memory objects 
object IDs `10` and `1010` are the base and 2nd field objects allocated at `Node* newNode = (Node *)malloc(sizeof(Node));` in `appendNode`.

object IDs `30` and `1030` are the base and 2nd field from `Node *n = (Node *)malloc(sizeof(Node));` in `main`.

Only objects `1030`,`10` and `1010` are modified and referred in callee `appendNode` and the base object `30` is not, therefore you will not have `mu` or `chi` for `30` at the callsite `  appendNode(n, 10);`

Second, SVF treats `10` and `1010` in `appendNode` as two separate memory regions, i.e., `MR_8` and `MR_10`, but in `main` these two objects are access-equivalent, thus collapsed into one region `MR_6`. You may wish to check the value-flows that there will be two edges from `MR_6` to both `MR_8` and `MR_10` in callee since they have overlapping objects.

Please let me know if you have any question.

**Comment by FrancisYL** [comment]
Hi Yulei, thank you for the detailed explanation. I think the reason is that SVF is dealing with objects field-sensitively. I've made a pull request #190 to fix this issue.
