### ISSUE TITLE
Function processStore may cause a point-to loop.

### ISSUE THREAD

**Issue by nopitydays** [SVF-tools/SVF#193]
Hi, I find something weird when used SVF to process linux kernel code. The output of SVF shows the node 46 which represents the global value g_ar_dev (hismart_ar.c line: 33), points to itself (hismart_ar.output line: 103456). Moreover, all the nodes that  represent g_ar_dev with different offsets, such as node 330046 (hismart_ar.output line: 116375), point to the same node 46, too. It seems that a point-to loop was generated.

I use SVF with llvm 8.0.1 and compile source code with llvm 8.0.1.
SVF was run with "wpa -debug -indCallLimit=100000 -print-pag -print-all-pts -dump-callgraph -ander -svfg -dump-mssa /path/to/llvm_bc_file"

My linux kernel source code:
https://drive.google.com/open?id=1myQfQp410ARrjnCfhb8821n5MYfPX95t
The bc file:
https://drive.google.com/open?id=1QSl-h9FRSMfthzNldRI3kimB4iqkra4w
SVF output file:
https://drive.google.com/open?id=1GLXDZK3F29XyxZ9cLfPZtYF3DqxxtZYM

I am not sure whether I use SVF correctly and try to find the reason. Here is my opinion:

No matter in LoadInst or in StoreInst, the direction of point-to should be from DstNode to SrcNode, right?
In lib/WPA/AndersenWaveDiff.cpp (lib/WPA/Andersen.cpp seems the same), the first parameter of function handleStore is DstNode of the second parameter (StoreEdge), and function handleStore will union the Pts of StoreEdge SrcNode into all the Pts of nodes in DstNode's Pts, as the figure below shows. However, I think we can only let DstNode point-to SrcNode. Whether nodes in Pts_of_DstNode will point to SrcNode is not sure.

SrcNode -----StoreEdge-----> DstNode

SrcNode <-----Pts----- DstNode

Pts_of_SrcNode <---Pts--- SrcNode

Pts_of_Pts_of_DstNode <---Pts--- Pts_of_DstNode <---Pts--- DstNode

Pts_of_Pts_of_DstNode = Pts_of_Pts_of_DstNode | Pts_of_SrcNode

I think the figure should be like that (same as handleLoad):

SrcNode -----StoreEdge-----> DstNode

SrcNode <-----Pts----- DstNode

Pts_of_Pts_of_SrcNode <---Pts--- Pts_of_SrcNode <---Pts--- SrcNode

Pts_of_DstNode <---Pts--- DstNode

Pts_of_DstNode = Pts_of_DstNode | SrcNode
Pts_of_DstNode = Pts_of_DstNode | Pts_of_SrcNode
Pts_of_DstNode = Pts_of_DstNode | Pts_of_Pts_of_SrcNode

Please let me know if you need any additional information.

**Comment by yuleisui** [comment]
Hello,

Your SVF is an old version. It is a bit hard for me to debug and understand your code snippet. 

For your points-to cycle, this is possible, because (1) the object itself can be a recursive data structure such as linked list, and (2) two objects can also be collapsed into one object due to positive weight cycles.

**Comment by nopitydays** [comment]
> Hello,

Thanks for reply.
The SVF I use is the latest version : commit f7b3d0e3b51b25e3894d5645a0f5172284645f29. After I patched function handleStore, my loop disappered. So I analyzed this function with rich debug information and get my result.

**Comment by yuleisui** [comment]
What do you mean by "patched function handleStore"?

May I know your SVF patch?

**Comment by nopitydays** [comment]
```
diff --git a/lib/WPA/AndersenWaveDiff.cpp b/lib/WPA/AndersenWaveDiff.cpp
index 0bed54c..26facdf 100644
--- a/lib/WPA/AndersenWaveDiff.cpp
+++ b/lib/WPA/AndersenWaveDiff.cpp
@@ -157,7 +157,9 @@ bool AndersenWaveDiff::handleLoad(NodeID nodeId, const ConstraintEdge* edge)
 bool AndersenWaveDiff::handleStore(NodeID nodeId, const ConstraintEdge* edge)
 {
     bool changed = false;
-    for (PointsTo::iterator piter = getPts(nodeId).begin(), epiter = getPts(nodeId).end();
+    NodeID srcNode = edge->getSrcID();
+
+    for (PointsTo::iterator piter = getPts(srcNode).begin(), epiter = getPts(srcNode).end();
          piter != epiter; ++piter) {
         if (processStore(*piter, edge)) {
             changed = true;
```

**Comment by yuleisui** [comment]
Can you submit a pull request?

**Comment by nopitydays** [comment]
Submitted. This patch will cause some point-to information false-negative and I am still trying to fix it.

**Comment by shiheyuan** [comment]
> llvm 8.0.1

Hi @nopitydays , I am curious about build kernel source by LLVM and perform static analysis by SVF.
Can you provide some advice to guide me to do this?
What is your kernel configuration?
What is the used build command?
By the way, I failed to use LLVM 8.0.1 to build kernel because of asm unsupport.
When I use LLVM 9, it can be built but show numerous warning like "Failed to find link section for the section XX", and when I use SVF to analyze vmlinux.bc the error log appears:
wpa: SVF/include/MemoryModel/MemModel.h:571: SymID SymbolTableInfo::getValSym(const Value*): Assertion `iter!=valSymMap.end() &&"value sym not found"' failed.

Thanks!

**Comment by nopitydays** [comment]
> > llvm 8.0.1
> 
> Hi @nopitydays , I am curious about build kernel source by LLVM and perform static analysis by SVF.
> Can you provide some advice to guide me to do this?
> What is your kernel configuration?
> What is the used build command?
> By the way, I failed to use LLVM 8.0.1 to build kernel because of asm unsupport.
> When I use LLVM 9, it can be built but show numerous warning like "Failed to find link section for the section XX", and when I use SVF to analyze vmlinux.bc the error log appears:
> wpa: SVF/include/MemoryModel/MemModel.h:571: SymID SymbolTableInfo::getValSym(const Value*): Assertion `iter!=valSymMap.end() &&"value sym not found"' failed.
> 
> Thanks!

Hi, I sent a message to your mailbox. Let's discuss by email.
