### ISSUE TITLE
Incorrect Andersen's result?

### ISSUE THREAD

**Issue by mbarbar** [SVF-tools/SVF#211]
![wc](https://user-images.githubusercontent.com/12083002/82218660-94772300-995f-11ea-895f-3adae3a6a35b.png)

This image is produced by `./bin/wpa -nander -fieldlimit=0 -dump-consG wc.ll` (the orange edges are GEP edges). The important part is the octopus-ish thing in the middle. It appears to me that `14` should point to itself. With `-print-all-pts`, the result is that `14`'s points-to set is empty. `-ander` has the same result.

My reasoning is...
* `17` points to `14`.
* `18` points to `14`.
* `17` `--store-->` `18`.
* *Expectation*: a copy edge from `17` to `14` because `18` points to `14`.

I've attached the offending `.ll` below. Uncommenting the line marked with `TODO` also produces, what appears to me as, an unexpected result, but fixing the aforementioned will fix this too I believe.

[wc.txt](https://github.com/SVF-tools/SVF/files/4644416/wc.txt)

**Comment by yuleisui** [comment]
Is node 14 is a constant object? If so, it does not allow to point to any other object.

**Comment by mbarbar** [comment]
Ahh yes. It is the `malloc` function itself. Thanks!
