### ISSUE TITLE
Backward value flow analysis

### ISSUE THREAD

**Issue by man9ourah** [SVF-tools/SVF#219]
Hello, 

I am in a problem where I need to inter-procedurally find the source of the value of a given field of a struct. For example, starting from `send(buf)` .. I want to trace back the value of `buf.xid` where it was first originated.. say three function calls back setting pckt.xid = rand(). 

I am wondering if SVF can help me with this. I tired doing this dynamically but I realized it is impossible to since I will have to taint every byte of memory which wont scale. Any help or pointers is much appreciated!

Thanks!

**Comment by yuleisui** [comment]
SUPA seems to suit your requirement.
https://github.com/SVF-tools/SUPA
