### ISSUE TITLE
Error on master branch: : CommandLine Error: Option 'help-list' registered more than once!

### ISSUE THREAD

**Issue by zhangysh1995** [SVF-tools/SVF#220]
Hi,

I'm following the quick start guide with `LLVM-10`, after the command `. ./setup.sh` and run `wpa -ander`, I got the following error:

````
zhangys@xxx:~/utility/SVF$ echo $LLVM_DIR
/usr/lib/llvm-10
zhangys@xxx:~/utility/SVF$ wpa -ander
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
````

I tried restarting a new terminal and it doesn't disappear. There was no warnings and no errors during compilation and setup.

````
zhangys@xxx:~/utility/SVF$ echo $LLVM_DIR
/usr/lib/llvm-10
zhangys@xxx:~/utility/SVF$ g++ --version
g++ (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
````

**Comment by zhangysh1995** [comment]
I think this is related to #209.

**Comment by yuleisui** [comment]
Are you building SVF on Ubuntu or Mac？

**Comment by zhangysh1995** [comment]
@yuleisui Ubuntu 18.04. But my LLVM is installed with `apt`. https://apt.llvm.org/

**Comment by yuleisui** [comment]
Can you follow SVF's cmake guide.
https://github.com/SVF-tools/SVF/wiki/Setup-Guide-(CMake)

**Comment by yuleisui** [comment]
I suspect llvm from apt is different from its released binary on its website. You may wish to dig a bit more. We can leave this issue open.

**Comment by zhangysh1995** [comment]
Having the same issue with self-compiled LLVM 10 from source code.

**Comment by yuleisui** [comment]
SVF supports continuous integration builds on both ubuntu and mac. If you have problems, you are likely not following our setup guide. 

https://travis-ci.org/github/SVF-tools/SVF/builds/690848921?utm_source=github_status&utm_medium=notification

**Comment by zhangysh1995** [comment]
I have no idea. But CI build pass doesn't mean it can build on the same operating system on different machines.

**Comment by zhangysh1995** [comment]
And also I'm familiar with LLVM and I carefully followed the guide to build SVF.

**Comment by zhangysh1995** [comment]
I could only use the downloaded binary to build SVF. @yuleisui
