### ISSUE TITLE
core dump with `./bin/wpa`: Aborted (core dumped)

### ISSUE THREAD

**Issue by zhangysh1995** [SVF-tools/SVF#223]
I want to test if the binary works:

````
zhangys@xxx:~/utility/SVF/build$ ./bin/wpa 
wpa: /home/zhangys/utility/SVF/lib/SVF-FE/LLVMModule.cpp:81: SVFModule* LLVMModuleSet::buildSVFModule(const std::vector<std::__cxx11::basic_string<char> >&): Assertion `!moduleNameVec.empty() && "no module is found from LLVM bc file!"' failed.
Aborted (core dumped)
````

It doesn't handle the case without a argument and dumped. It is expected to print the help list if no argument is supplied.

However it works with `--help`.

**Comment by yuleisui** [comment]
Hi Yushan,

It says clearly `no LLVM module is found`. Did you feed any LLVM bc files, why so rush?

**Comment by zhangysh1995** [comment]
> It says clearly no LLVM module is found. Did you feed any LLVM bc files, why so rush?

I'm not rush. It should sat no `bc` but not result in a core dump.

**Comment by yuleisui** [comment]
As per your suggestion:
https://github.com/SVF-tools/SVF/commit/6b09989fb659fc948b08d647c341d59c9699bb24

**Comment by zhangysh1995** [comment]
Close the issue now!
