### ISSUE TITLE
Outdated doxygen manual

### ISSUE THREAD

**Issue by prashast** [SVF-tools/SVF#239]
Hi, just as an FYI, the doxygen manual hosted at http://www.cse.unsw.edu.au/~corg/svf/doxygen/ seems to be heavily outdated.

**Comment by yuleisui** [comment]
Hello,

Please refer to here for the latest oxygen of SVF:
https://svf-tools.github.io/SVF-doxygen/

**Comment by prashast** [comment]
Great, thanks a lot!
