### ISSUE TITLE
std::unique_ptr vs. new

### ISSUE THREAD

**Issue by swthorn** [SVF-tools/SVF#243]
Take a look at this gist of two .cpp files I am testing with: https://gist.github.com/swthorn/3f9f6f4f3f5deaea257c8fa37a2e317c

using 
./wpa -wander --dump-callgraph -genicfg test1.bc && dot -Tpdf callgraph_final.dot > test1.pdf
./wpa -wander --dump-callgraph -genicfg test2.bc && dot -Tpdf callgraph_final.dot > test2.pdf

I get the following ICFG's:
test1:
[test1.pdf](https://github.com/SVF-tools/SVF/files/4815279/test1.pdf)

test2:
[test2.pdf](https://github.com/SVF-tools/SVF/files/4815280/test2.pdf)

I noticed in test1, the icfg doesn't show the call to printf, but test2 does. Could this be a similar issue as #212 where the summary on std::unique_ptr (and perhaps std::shared_ptr too) are incorrect? I think this may be causing an issue when analyzing code that utilizes std::unique_ptr a lot.

**Comment by yuleisui** [comment]
I think so. Could you send me your two compiled bc files?

**Comment by swthorn** [comment]
Sure! I've attached a zip file containing both compiled bc's
[unique_ptr_test.zip](https://github.com/SVF-tools/SVF/files/4816426/unique_ptr_test.zip)

**Comment by yuleisui** [comment]
As far as I can see that in the test1.bc, it does not have a `printf`

**Comment by swthorn** [comment]
hmm, looks like you're right. I suspect this is a problem with the way the compiler handles
`std::unique_ptr<TesterClass> test;`
vs.
`auto test = std::make_unique<TesterClass>();`

The "correct" way to use the unique_ptr is the 2nd way I've listed. The code I'm analyzing uses the first way. The compiler seems to remove the calls to the constructor in the compiled program and the LLVM IR.

I'll reopen this issue if I find any more information that might help, I think it may be more of an issue with the compiler though.
