### ISSUE TITLE
Extracting call ordering information

### ISSUE THREAD

**Issue by prashast** [SVF-tools/SVF#247]
Let's say I have the following code snippet:
```
foo( ) {
   bar ( );
   baz ( );
}
```
Does SVF encode the call ordering information in its `PTACallGraph`.? That is, Is it possible for me to infer that `foo` calls `bar` first and then `baz`? I looked at the source code for a bit but nothing popped out that would answer this query from the PTACallGraph.

My current plan is to use the ICFG to extract the call ordering information. Does that make sense or is there an easier way to extract this information using SVF?

**Comment by yuleisui** [comment]
`PTACallGraph ` does not reflect the control-flow order. ICFG would be the best way to extract your call order.

**Comment by prashast** [comment]
Sounds good. Thanks for the quick reply! :)
