### ISSUE TITLE
Is there an error in function "updatePropaPts" ?

### ISSUE THREAD

**Issue by yiyuaner** [SVF-tools/SVF#255]
In SVF's basic anderson pointer analysis (type: **Andersen_WPA**), the function for adding copy constraint is [as follows](https://github.com/SVF-tools/SVF/blob/master/include/WPA/Andersen.h#L272):
```
/// Add copy edge on constraint graph
    virtual inline bool addCopyEdge(NodeID src, NodeID dst) {
        if (consCG->addCopyCGEdge(src, dst)) {
            updatePropaPts(src, dst);
            return true;
        }
        return false;
    }
```
Where we call `updatePropaPts(src, dst)`. However, the [definition](https://github.com/SVF-tools/SVF/blob/master/include/WPA/Andersen.h#L230) for this function is:
```
/// Handle propagated points-to set.
    inline void updatePropaPts(NodeID dstId, NodeID srcId) {
        if (!enableDiff())
            return;
        NodeID srcRep = sccRepNode(srcId);
        NodeID dstRep = sccRepNode(dstId);
        getDiffPTDataTy()->updatePropaPtsMap(srcRep, dstRep);
    }
```

1. The position of src and dst is reversed in the argument list. Is this a programming mistake or there is a reason for doing so? Is it related to the idea of "propogated points to set"?
2. In the [function](https://github.com/SVF-tools/SVF/blob/master/include/MemoryModel/PointsToDS.h#L240) `DiffPTData::updatePropaPtsMap`, dst is modified with the intersection of src and dst. May I ask why we use set intersection instead of set union here?  Since when  adding edege p --> q, pts(p) ⊆ pts(q).

Wish for your help, thanks!

**Comment by yuleisui** [comment]
@kisslune can you help answer this question?

**Comment by yuleisui** [comment]
Both your questions are correct from my point of view:

1. it does not matter for the position of the parameters as long as the results are correct.

2. intersection is used to only propagate the new points-to information based on the wave propagation algorithm. http://compilers.cs.ucla.edu/fernando/publications/papers/CGO09.pdf
