### ISSUE TITLE
Some questions related to a LLVM-gold plugin and Linux kernel.

### ISSUE THREAD

**Issue by threeearcat** [SVF-tools/SVF#27]
I have read some documents related to the gold plugin and LTO, but still not clear for me.
As far as I understood, the reason why we use llvm-gold plugin is becuase
- the linker needs all available bitcode/object files (without any missing functions/files) in order to do the link time optimization, and
- Successful linking (or LTO) guarantees there is no missing part.
- and in order to link all bitcodes/objects together using `clang -flto`, I should give all bitcodes/objects as arguments altogether.

Am I right?

Based on what I guess, I tried to follow your suggestion.
But it looks building Linux kernel is not a trivial. I tried a few things as follows and all fails.

I first tried to build a vmlinux bitcode file with [llvmlinux](http://llvm.linuxfoundation.org/index.php/Main_Page) project.
I used a script as a CC instead of clang or gcc.
It emits both bitcode files and object files for all clang command.
I think it was successful so far. So I was able to generate bitcode files for individual C codes.
And then I ran ``clang -flto $(find . -name '*.bc') -o $OUTPUT``.
I knew there might be some missing files but I wanted to see what would happen.

It generated a lot of multiple definition errors as follows.
```
...
/usr/bin/ld: error: /tmp/intel_audio-5ce78a.o: multiple definition of 'intel_audio_codec_disable'
/usr/bin/ld: /tmp/built-in-02b6ce.o: previous definition here
/usr/bin/ld: error: /tmp/intel_audio-5ce78a.o: multiple definition of 'intel_init_audio'
/usr/bin/ld: /tmp/built-in-02b6ce.o: previous definition here
/usr/bin/ld: error: /tmp/intel_audio-5ce78a.o: multiple definition of 'i915_audio_component_init'
/usr/bin/ld: /tmp/built-in-02b6ce.o: previous definition here
/usr/bin/ld: error: /tmp/intel_audio-5ce78a.o: multiple definition of 'i915_audio_component_cleanup'
/usr/bin/ld: /tmp/built-in-02b6ce.o: previous definition here
...
```

I also tried to build it in the way suggested in [quickstart-for-using-lto-with-autotooled-projects](http://llvm.org/docs/GoldPlugin.html#quickstart-for-using-lto-with-autotooled-projects) without using another project.
It generated following errors.
```
...
In file included from arch/x86/kernel/asm-offsets.c:8:
In file included from include/linux/crypto.h:24:
In file included from include/linux/slab.h:14:
In file included from include/linux/gfp.h:5:
include/linux/mmzone.h:345:22: error: use of undeclared identifier 'MAX_NR_ZONES'; did you mean
      '__MAX_NR_ZONES'?
        long lowmem_reserve[MAX_NR_ZONES];
                            ^~~~~~~~~~~~
                            __MAX_NR_ZONES
...
```

I found the other project [linux-misc](https://github.com/andikleen/linux-misc) whose a purpose is building LTO-applied Linux kernel (based on gcc).
But combining this project and llvmlinux is a little bit confusing me, and I think it will not work properly.

If you have the experience analyzing Linux kernel, please give me an advice how I can link Linux kernel in a proper way.
Thanks!

**Comment by rockysui** [comment]
```
I have read some documents related to the gold plugin and LTO, but still not clear for me.
As far as I understood, the reason why we use llvm-gold plugin is becuase

the linker needs all available bitcode/object files (without any missing functions/files) in order to do the link time optimization, and
Successful linking (or LTO) guarantees there is no missing part.
and in order to link all bitcodes/objects together using clang -flto, I should give all bitcodes/objects as arguments altogether.
Am I right?
```

Yes, you are right.


```
clang -flto $(find . -name '*.bc') -o $OUTPUT
```

This is not the right way to do. Please see our instructions:
https://github.com/unsw-corg/SVF/wiki/Install-LLVM-Gold-Plugin-on-Ubuntu


On  [llvmlinux](http://llvm.linuxfoundation.org/index.php/Main_Page)

We haven't tried llvmlinux before. I suggest that you should directly ask them for help, as they are more experienced to know which part needs to be configured properly.

You may also wish to email llvm-dev to seek help, as compiling linux whole kernal itself using gold-plugin is not a very straightforward task.

**Comment by threeearcat** [comment]
I forgot to mention that is the last instruction that I tried.
Of course I tried your instructions, but sadly, failed.
To be honest, I tried a few things, from your instruction to a very wired combination of instructions.
But everything failed.

It looks like a time-consuming job.
I will continue to work on it.
I will let you know as soon as I succeed in analyzing a kernel.
I really want to succeed to analyze a kernel with your tool (I like this tool :) ).

Anyway, thanks a lot for your help!

**Comment by threeearcat** [comment]
I moved to another project and now come back here.
As far as I know, the reasons why I failed to get the useful information are 1) assembly and  2) pointer casting (pointer to long or int).

For example, 1) in x86, `current` macro is implemented as
`
#define percpu_cmpxchg_op(var, oval, nval)				\
({									\
	typeof(var) pco_ret__;						\
	typeof(var) pco_old__ = (oval);					\
	typeof(var) pco_new__ = (nval);					\
	switch (sizeof(var)) {						\
	case 1:								\
		asm("cmpxchgb %2, "__percpu_arg(1)			\
			    : "=a" (pco_ret__), "+m" (var)		\
			    : "q" (pco_new__), "0" (pco_old__)		\
			    : "memory");				\
		break;							\
	case 2:								\
		asm("cmpxchgw %2, "__percpu_arg(1)			\
			    : "=a" (pco_ret__), "+m" (var)		\
			    : "r" (pco_new__), "0" (pco_old__)		\
			    : "memory");				\
		break;							\
	case 4:								\
		asm("cmpxchgl %2, "__percpu_arg(1)			\
			    : "=a" (pco_ret__), "+m" (var)		\
			    : "r" (pco_new__), "0" (pco_old__)		\
			    : "memory");				\
		break;							\
	case 8:								\
		asm("cmpxchgq %2, "__percpu_arg(1)			\
			    : "=a" (pco_ret__), "+m" (var)		\
			    : "r" (pco_new__), "0" (pco_old__)		\
			    : "memory");				\
		break;							\
	default: __bad_percpu_size();					\
	}								\
	pco_ret__;							\
})

#define this_cpu_read_stable(var)   percpu_stable_op("mov", var)

static __always_inline struct task_struct *get_current(void)
{
    return this_cpu_read_stable(current_task);
}
#define current get_current()
`
and in fs, retriving `struct file*` from `fd` is implemented like this
`
unsigned long v = __fdget(fd);
struct file *file = (struct file *)(v & ~3);
`
I guess everything else is good.
(well, the above problem seems obivious because of LLVM IR)

I fixed these only for the pta, (like, just making `current` macro return &init_task)
Of course, fixed code should not work properly, but now I can get the useful result of pta (at least one of the device driver).
