### ISSUE TITLE
Aliases of two pagNodes

### ISSUE THREAD

**Issue by aliahad97** [SVF-tools/SVF#270]
Hello,

I am trying to *optimize* **aliasing** for a certain set of **pagNodes**. My question is whether *two* different **pagNodes** have the ***same*** **aliases** if they are **aliases** of one another? For my small program, this property exists but I would like to know if I can generalize this property for larger programs.

I consider two pagNodes to be aliases of one another if `pta->alias(node1, node2) != NoAlias`. 

Thank you.

**Comment by yuleisui** [comment]
Yes, two PAG nodes are aliases if `pta->alias(node1, node2) != NoAlias`

**Comment by aliahad97** [comment]
But would they both then share the same set of aliases if they both are aliases?

**Comment by yuleisui** [comment]
Not necessarily. `node1` and `node2` are aliases only means that their points-to sets are overlapping.

**Comment by aliahad97** [comment]
Makes sense. Thank you!
