### ISSUE TITLE
Basic Andersen's point-to analysis fails to identify MayAlias relation between pointers

### ISSUE THREAD

**Issue by jzhou76** [SVF-tools/SVF#286]
I'm analyzing `curl`'s source code with the basic Andersen's point-to analysis algorithm implemented in SVF-1.8. I noticed that for certain functions SVF fails to identify that two pointers may alias to each other.

For `curl`, function `tool_header_cb()` defined in `src/tool_cb_hdr.c` (https://github.com/curl/curl/blob/curl-7_70_0/src/tool_cb_hdr.c#L56) is compiled to the following LLVM IR (compiled by LLVM 10.0 with -O3):

```llvm
  1 ; Function Attrs: nounwind uwtable                                              
  2 define internal i64 @tool_header_cb(i8* %0, i64 %1, i64 %2, i8* nocapture %3) #2 {
  3   %5 = alloca i64, align 8                                                      
  4   %6 = getelementptr inbounds i8, i8* %3, i64 336                               
  5   %7 = getelementptr inbounds i8, i8* %3, i64 200                               
  6   %8 = bitcast i8* %7 to %struct.OutStruct*                                     
  7   %9 = mul i64 %2, %1                                                           
  8   %10 = getelementptr inbounds i8, i8* %0, i64 %9                               
  9   %11 = bitcast i64* %5 to i8*                                                  
 10   call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %11) #10               
 11   store i64 0, i64* %5, align 8, !tbaa !27                                      
 12   %12 = icmp eq i64 %1, 0                                                       
 13   %13 = icmp eq i64 %2, 0                                                       
 14   %14 = or i1 %12, %13                                                          
 15   %15 = zext i1 %14 to i64                                                      
 16   %16 = getelementptr inbounds i8, i8* %3, i64 16                               
 17   %17 = bitcast i8* %16 to %struct.OperationConfig**                            
 18   %18 = load %struct.OperationConfig*, %struct.OperationConfig** %17, align 8, !tbaa !40
 19   %19 = icmp eq %struct.OperationConfig* %18, null                              
 20   br i1 %19, label %377, label %20                                              
 21                                                                                 
 22 20:                                               ; preds = %4                  
 23   %21 = getelementptr inbounds %struct.OperationConfig, %struct.OperationConfig* %18, i64 0, i32 30
 24   %22 = load i8*, i8** %21, align 8, !tbaa !46                                  
 25   %23 = icmp eq i8* %22, null                                                   
 26   br i1 %23, label %36, label %2

......
```
(see https://gist.github.com/jzhou76/b2f1f0f9b53e43298d771add4ca86a88 for the complete IR file)

At line 18, the pointer operand (`%17`) of the `load` instruction should MayAlias to the fourth argument `%3` of this function, which can be manually inferred from line 16 - 18. However, `WPAPass`'s `alias(%3, %17)` method returns `NoAlias`.  This `load` corresponds to line 76 of `src/tool_cb_hdr.c` (https://github.com/curl/curl/blob/curl-7_70_0/src/tool_cb_hdr.c#L76).

I wrote a small program to confirm that SVF's implementation of the basic Andersen's algorithm does perform field-insensitive analysis.  For program
```C
struct Config {
    int i;
    double d;
};

typedef struct {
    int i;
    char c;
    long l;
    struct Config *config;
} Data;

void foo(void *p, int num) {                                                      
      Data *data = (Data *)p;                                                     
                                                                                 
      if (!data->config) {                                                        
          printf("lalala\n");                                                     
      }                                                                                                                                                                                               
 }
```
The LLVM IR is (compiled by the same compiler with -O3)
```llvm
  1 ; Function Attrs: nofree noinline nounwind uwtable                              
  2 define internal fastcc void @foo(i8* nocapture readonly %0) unnamed_addr #0 {   
  3   %2 = getelementptr inbounds i8, i8* %0, i64 16                                
  4   %3 = bitcast i8* %2 to %struct.Config**                                       
  5   %4 = load %struct.Config*, %struct.Config** %3, align 8, !tbaa !5             
  6   %5 = icmp eq %struct.Config* %4, null                                         
  7   br i1 %5, label %6, label %9                                                  
  8                                                                                 
  9 6:                                                ; preds = %1                  
 10   %7 = getelementptr [7 x i8], [7 x i8]* @str.9, i64 0, i64 0                   
 11   %8 = tail call i32 @puts(i8* nonnull dereferenceable(1) %7)                   
 12   br label %9                                                                   
 13                                                                                 
 14 9:                                                ; preds = %6, %1              
 15   ret void                                                                      
 16 }
```

At line 4 for the `load` instruction,  SVF's `WPAPass`'s `alias(%0, %3)` method successfully returns `MayAlias` as expected. As you can see here, the code pattern of line 3 - 5 of function `foo()` is very similar to line 16 - 18 of function
`tool_header_cb()`. But SVF fails to identify the MayAlias relation for the latter.

I'm confused with what is described above. Do I misunderstand SVF somehow, or could there be implementation bugs in SVF-Andersen's point-to analysis?

**Comment by yuleisui** [comment]
Is `%3` in `tool_header_cb ` a null pointer? If so, their points-to sets are non-overlapping thus, no-alias.

**Comment by jzhou76** [comment]
> Is `%3` in `tool_header_cb ` a null pointer? If so, their points-to sets are non-overlapping thus, no-alias.

@yuleisui `%3` is the fourth argument of `tool_header_cb`, defined as `void *userdata` (https://github.com/curl/curl/blob/curl-7_70_0/src/tool_cb_hdr.c#L56); you can also see it on line 2 of the first LLVM IR code snippet of this issue. I believe it will not be a null pointer because the major computation of this function is from pointers derived from `%3`. For example, if `%3` is a null pointer,  line 59 to line 62 would cause segfault immediately when the function starts to run (https://github.com/curl/curl/blob/curl-7_70_0/src/tool_cb_hdr.c#L59). If compiler thinks it is a null pointer, the majority of the code of this function would not make sense.

**Comment by yuleisui** [comment]
At runtime, yes. But statically, I did not see any other function calling `tool_header_cb`?

**Comment by jzhou76** [comment]
> At runtime, yes. But statically, I did not see any other function calling `tool_header_cb`?

`tool_header_cb()` is passed as an argument to function `my_setopt()` (https://github.com/curl/curl/blob/curl-7_70_0/src/tool_operate.c#L1865). Is it possible that SVF's analysis infers that `tool_header_cb` will not be called? I compiled `curl` with `-O3` and ran `WPAPass` after running all the LLVM's built-in LTO passes; so it means LLVM's analysis believes `tool_header_cb` might be called sometime. I don't know if the basic Andersen's analysis could find more dead functions.

**Comment by yuleisui** [comment]
Is this an indirect call?

**Comment by jzhou76** [comment]
> Is this an indirect call?

Yes I believe so. `tool_header_cb()` is never called directly. Its address is passed to some function. So does SVF computes the point-to sets by traversing the call-graph and only analyzing functions reachable on the call graph? If so it makes sense to me that it is possible the whole `tool_header_cb()` function was not analyzed at all.

**Comment by jzhou76** [comment]
> > Is this an indirect call?
> 
> Yes I believe so. `tool_header_cb()` is never called directly. Its address is passed to some function. So does SVF computes the point-to sets by traversing the call-graph and only analyzing functions reachable on the call graph? If so it makes sense to me that it is possible the whole `tool_header_cb()` function was not analyzed at all.
> 
> Also does `WPAPass` provides an interface to give us the set of all reachable functions from `main()` on the call graph? I didn't see one from the online document. The reason my analysis pass tries to analyze `tool_header_cb`() is that it simply iterates over all functions from the whole LLVM `Module` except library functions. If `WPAPass` provides such an interface then I don't have to use LLVM's `Module` iterator.

An update on this issue:
I confirmed that LLVM's built-in `CallGraph` is not able to figure out which function calls `tool_header_cb()` at compile time. So, is it possible that SVF doesn't provide the point-to relations for `tool_header_cb()` because it cannot decide which function calls `tool_header_cb()` so SVF just ignores it?

**Comment by yuleisui** [comment]
Thanks for your updates. SVF can handle indirect calls, but your case is a bit complicated and I am unsure whether the function pointer has been assigned a value or depending on some external configuration. It would be good to shrink your benchmark and make it as small as possible so that I could help you with the issue.

**Comment by jzhou76** [comment]
> Thanks for your updates. SVF can handle indirect calls, but your case is a bit complicated and I am unsure whether the function pointer has been assigned a value or depending on some external configuration. It would be good to shrink your benchmark and make it as small as possible so that I could help you with the issue.

Thanks for the help. `curl` is a relatively large program and it's very hard for me to strip off the irrelevant code to get a small piece of code that reproduce the same manifested in `tool_header_cb()`. However, I found a few small cases that displays the similar issue.

I'm analyzing the `musl-libc`(https://www.musl-libc.org/) with SVF and I noticed that SVF doesn't provide point-to information for a lot of library functions. For example, for the `strncat()` function defined in `src/string/strncat.c` (https://git.musl-libc.org/cgit/musl/tree/src/string/strncat.c?h=v1.2.1),
```C
  3 char *strncat(char *restrict d, const char *restrict s, size_t n)               
  4 {                                                                               
  5     char *a = d;                                                                
  6     d += strlen(d);                                                             
  7     while (n && *s) n--, *d++ = *s++;                                           
  8     *d++ = 0;                                                                   
  9     return a;                                                                   
 10 }
```

 the `WPAPass` identify neither the first argument `d` MayAlias with the `d` in line 7 nor the second argument `s` MayAlias with the `s` in line 7. I copied & pasted this function to a small test program and **call** it in `main()`; in this case, `WPAPass` successfully captures the MayAlias relations between the arguments and the ones used in line 7, both the load from `s` and the store to `d`. This seems to indicate that SVF doesn't analyze this `strncat()` function at all because we're compiling a `libc` and no other function calls this function in the same library.

So as a general rule, is it true that if SVF doesn't see a function F being called by any function, then it just omits analyzing F?

**Comment by yuleisui** [comment]
SVF is able to handle external functions given the hand-written side-effect summarization of external APIs (see https://github.com/SVF-tools/SVF/blob/master/lib/Util/ExtAPI.cpp). 

The function body of any external functions (e.g., `strncat `) summarized in `ExtAPI.cpp` will not be analyzed and only its summarized side-effect is applied.

For your aliases, SVF determines aliases based on points-to analysis, i.e., intersecting the points-to sets of two pointers.
In your `strncat` case, even if it is not put in `ExtAPI.cpp`,  `d` (argument) and `d` (line 6) are treated as non-aliases since `d`'s points-to set is empty unless `strncat` is called with valid inputs.

**Comment by jzhou76** [comment]
> SVF is able to handle external functions given the hand-written side-effect summarization of external APIs (see https://github.com/SVF-tools/SVF/blob/master/lib/Util/ExtAPI.cpp).
> 
> The function body of any external functions (e.g., `strncat `) summarized in `ExtAPI.cpp` will not be analyzed and only its summarized side-effect is applied.
> 
> For your aliases, SVF determines aliases based on points-to analysis, i.e., intersecting the points-to sets of two pointers.
> In your `strncat` case, even if it is not put in `ExtAPI.cpp`, `d` (argument) and `d` (line 6) are treated as non-aliases since `d`'s points-to set is empty unless `strncat` is called with valid inputs.

Thanks for the explanation. It helps a lot. To my understanding,  "External Functions" in this context are not only library functions, but they actually also include functions that are in the source code but the call to which cannot be resolved at compile (such as `strncat()` in `musl-libc`, correct? 

Can you also give me an estimate on how much effort (e.g. how many person day/month) it would take to modify SVF to analyze those "false negative" external functions? Basically I'd like to analyze any function in the source code. And can you point to me where (which source code) should I start from if I'd like to work on this "extension"?

**Comment by yuleisui** [comment]
> > SVF is able to handle external functions given the hand-written side-effect summarization of external APIs (see https://github.com/SVF-tools/SVF/blob/master/lib/Util/ExtAPI.cpp).
> > The function body of any external functions (e.g., `strncat `) summarized in `ExtAPI.cpp` will not be analyzed and only its summarized side-effect is applied.
> > For your aliases, SVF determines aliases based on points-to analysis, i.e., intersecting the points-to sets of two pointers.
> > In your `strncat` case, even if it is not put in `ExtAPI.cpp`, `d` (argument) and `d` (line 6) are treated as non-aliases since `d`'s points-to set is empty unless `strncat` is called with valid inputs.
> 
> Thanks for the explanation. It helps a lot. To my understanding, "External Functions" in this context are not only library functions, but they actually also include functions that are in the source code but the call to which cannot be resolved at compile (such as `strncat()` in `musl-libc`, correct?
> 

Yes.

> Can you also give me an estimate on how much effort (e.g. how many person day/month) it would take to modify SVF to analyze those "false negative" external functions? Basically I'd like to analyze any function in the source code. And can you point to me where (which source code) should I start from if I'd like to work on this "extension"?

If a function has a function body in the LLVM-IR, you are good to remove that function in the `extAPI.cpp` or you may wish take a look or modify the following code to see how the PAG is constructed.

https://github.com/SVF-tools/SVF/blob/master/lib/SVF-FE/PAGBuilder.cpp#L668-L678
