### ISSUE TITLE
Dump ICFG not working

### ISSUE THREAD

**Issue by 5hadowblad3** [SVF-tools/SVF#294]
Hi, there.

I am new to this great tool SVF.

However, I find that wpa cannot dump icfg for the bc I give, though other graphs are working fine.
My command is:
~~~~
wpa -fspta -genicfg -dump-icfg -dump-inst target.bc
~~~~
It only shows the statistic of the analysis but no graph is generated.
I would like to hear your advice about this.

Thank you.

**Comment by guanqin-123** [comment]
hey, I have made a quick check. There is no problem to generate ICFG.  I guess you haven't noticed the where to find it. 
e.g.  if you use the command line, in the current path, icfg_final.dot will be wisely generated there.  But as you use it in some IDE like clion and you set up in the configurations to build && run, the generated dot file will be stored in the same path of the  executable file --wpa.

**Comment by 5hadowblad3** [comment]
I use SVF command-line tool. Unfortunately, I still do not find the dumped graph in that folder.

Is that related to a recent update? Because my version is from a couple of months ago.

**Comment by guanqin-123** [comment]
ohh, you would be better to update to the latest version.  Maybe you could try SVF-ex,  https://github.com/SVF-tools/SVF-example  as well . It's quite straightforward to dump every graph and a quite easy-way to use namespace SVF to implement your own algorithms with SVF.

**Comment by 5hadowblad3** [comment]
OK, the newest version works!

Thanks.

**Comment by 5hadowblad3** [comment]
BTW, do you have any documentation for explaining the factors such as node's type, its color, and the details of this ICFG?

Thank you in advance.
