### ISSUE TITLE
symbols lost in print-all-pts

### ISSUE THREAD

**Issue by tiedaoxiaotubie** [SVF-tools/SVF#297]
I want to do `alias analysis` base on `SVF`, so debug symbols/variable names are quite important for me. However, I noticed in `wpa -ander -print-all-pts`, the debug symbols are always lost, which makes the result confusing for user.

I have compiled the program with `-fno-discard-value-names`  and `-g -O0`. I have attached my toy program to show my problem I met. The command I used is `wpa --ander --print-all-pts my_test.bc > my_test_ander`.
[my_test.zip](https://github.com/SVF-tools/SVF/files/5078674/my_test.zip)

The variable name was missing in `line 350` of `my_test_ander`, which should be `buf` according to the `my_test.c`.

Besides, for the variable `len` in `my_test.c:+3`, there are 3 different `ptr` were generated in `my_test_ander`, which makes me confused, I don't understand the differences between `Ptr 15`, `Ptr 16`, and `Ptr 21`, since there is only one variable in fact, why there will be 3 unique pointer?

**Comment by yuleisui** [comment]
SVF analyzes llvm IR whose symbols are preserved by clang. This question is best to ask in the llvmdev list.
