### ISSUE TITLE
Comparison of NodeID (unsigned int) and -1

### ISSUE THREAD

**Issue by canlockkeyin** [SVF-tools/SVF#299]
In the following piece of code, a NodeID is compared to -1, even though it is supposed to be unsigned.
https://github.com/SVF-tools/SVF/blob/7500e23dab46c6bad2cff329e9eb321da148307a/lib/SVF-FE/PAGBuilder.cpp#L1294

Simply changing the typedef for NodeID only leads to lots of errors.

**Comment by yuleisui** [comment]
UINT_MAX can be used I guess to make a clear.

**Comment by yuleisui** [comment]
Fix here: https://github.com/SVF-tools/SVF/commit/ee9bbea6acc5989521d996748f7df40a3076d392
