### ISSUE TITLE
wpa will Abort in VFG.h:409

### ISSUE THREAD

**Issue by tiedaoxiaotubie** [SVF-tools/SVF#306]
When I tried to execute `wpa -ander -svfg -dump-svfg libpng16.a.op`, an error will raise:
```
wpa: /home/SVF/include/Graphs/VFG.h:409: SVF::NodeID SVF::VFG::getDef(const SVF::PAGNode*) const: Assertion `it!=PAGNodeToDefMap.end() && "PAG node does not have a definition??"' failed.
Aborted (core dumped)
```
This error is completely same with https://github.com/SVF-tools/SVF/issues/296#issue-677353986

Compared with showcase in issue#296, the bc file is much more smaller this time:
[libpng.zip](https://github.com/SVF-tools/SVF/files/5136425/libpng.zip)

**Comment by yuleisui** [comment]
@tiedaoxiaotubie can you try the latest version of SVF to see whether the issue is gone?

**Comment by rainoftime** [comment]
At the latest commit, the bc triggers an issue
~~~~
Writing 'svfg_final.dot'...wpa: /home/legend/SVF/lib/Graphs/SVFG.cpp:1040: static std::string llvm::DOTGraphTraits<SVF::SVFG*>::getNodeAttributes(llvm::DOTGraphTraits<SVF::SVFG*>::NodeType*, SVF::SVFG*): Assertion `false && "no such kind of node!!"' failed.
~~~~

**Comment by yuleisui** [comment]
Fixed.
