### ISSUE TITLE
Handling ARGV points to

### ISSUE THREAD

**Issue by Machiry** [SVF-tools/SVF#309]
Hi @yuleisui,

Is there any way we can track points-to of argv? The old method of handling using BLACKHOLEOBJ seems to be removed.

-Thank You,
Aravind

**Comment by yuleisui** [comment]
Hi Aravind,

I think you can create a dummy object (https://github.com/SVF-tools/SVF/blob/master/include/Graphs/PAGNode.h#L69) and added it in the points-to set of the argument before the main solving phase of the Andersen's analysis. Then you can use reverse pts (https://github.com/SVF-tools/SVF/blob/master/include/MemoryModel/PointerAnalysis.h#L247) to track the pointers which point to this object.

**Comment by Machiry** [comment]
Thank You!
