### ISSUE TITLE
Andersen analysis implementations display different results on --print-pts

### ISSUE THREAD

**Issue by rainoftime** [SVF-tools/SVF#313]
Hi, when trying different engines of Andersen analysis (on some small programs), I found that 
the results of `./wpa --print-pts` seem to be "different".

- `-wander` and `-ander` are the same
- `-wander` and `-lander` can be different
- `-hlander` and `-lander` can be different 

Is this because of the cycle elimination algorithms in `lander` and `hlander`? E.g., some nodes are merged and thus the results "look different".

**Comment by rainoftime** [comment]
Here is a bitcode (in LLVM 10)

[small.bc.zip](https://github.com/SVF-tools/SVF/files/5176182/small.bc.zip)
The results of `wander` and `lander`
[wander.txt](https://github.com/SVF-tools/SVF/files/5176189/wander.txt)
 
[lander.txt](https://github.com/SVF-tools/SVF/files/5176192/lander.txt)

The diff of the two files
~~~~
[peisen@chcpu12d ~]$ diff wander.txt lander.txt
920c920
< NodeID 1238 		PointsTo: { 45 50 1028 }
---
> NodeID 1238 		PointsTo: { 50 }
926c926
< NodeID 1244 		PointsTo: { 45 50 1028 }
---
> NodeID 1244 		PointsTo: { 50 }
1046c1046
< NodeID 1706 		PointsTo: { 45 50 1028 }
---
> NodeID 1706 		PointsTo: { 50 }
~~~~

**Comment by yuleisui** [comment]
@kisslune can you take a look this issue?

**Comment by kisslune** [comment]
Hello @rainoftime! Please try the newest version, which has the identical point-to sets.

**Comment by rainoftime** [comment]
For the same bc https://github.com/SVF-tools/SVF/files/5176182/small.bc.zip,
`wpa --print-all-pts -wander` and `wpa --print-all-pts -hlander` seem to yield different results

**Comment by kisslune** [comment]
Hello @rainoftime! -hlander is also fixed.

**Comment by rainoftime** [comment]
@kisslune 
I tried another option `print-all-pts`, not `print-pts`. 
Under the new option, `wander` and `lander` are the same, but `wander` and `hlander` are diffeent.

**Comment by kisslune** [comment]
Hello @rainoftime! 

The option `print-pts` exactly print the point-to sets of all the top-level variables, while `print-all-pts` will print the point to sets of all nodes on the graph, including the auxiliary nodes that created by different methods, which leads to the difference of the results.

Generally, `print-pts` is used to get the point-to results.
