### ISSUE TITLE
Assertion violation at /include/Graphs/VFG.h:417

### ISSUE THREAD

**Issue by rainoftime** [SVF-tools/SVF#315]
Hi, for the following bitcode (LLVM 10)
[417.bc.zip](https://github.com/SVF-tools/SVF/files/5177912/417.bc.zip)

~~~~
/dvf --cxt err.bc

dvf: /home/legend/SVF/include/Graphs/VFG.h:417: SVF::NodeID SVF::VFG::getDef(const SVF::PAGNode*) const: Assertion `it!=PAGNodeToDefMap.end() && "PAG node does not have a definition??"' failed.
Aborted (core dumped)
~~~~

Commit: 84bc1d117d20

**Comment by yuleisui** [comment]
Just fixed. This is due to a recent merge here: https://github.com/SVF-tools/SVF/pull/311/files. The reason is here: https://github.com/SVF-tools/SVF/blob/master/lib/SVF-FE/PAGBuilder.cpp#L979

**Comment by rainoftime** [comment]
~~~~
/dvf -cxt --query=all --stat=false
~~~~~
[read_grid.o.bc.zip](https://github.com/SVF-tools/SVF/files/5244182/read_grid.o.bc.zip)

**Comment by yuleisui** [comment]
Just fixed. Please see here: https://github.com/SVF-tools/SVF/commit/d1ca33a91696c008031c12e719692da802fbe072
