### ISSUE TITLE
incorrect handling lock release call

### ISSUE THREAD

**Issue by ycaibb** [SVF-tools/SVF#316]
Dear Developers:

I found an issue about handling lock release call in the function analyzeLockSpanCxtStmt() in the file of LockAnalysis.cpp. The correct way is to remove the must-alias acquire locks in the function removeCxtStmtToSpan(). In present, the function removeCxtStmtToSpan() seems to remove the corresponding lock release call in the cxtStmtToCxtLockSet and cxtLocktoSpan, but they only store lock acquire calls.

```
void LockAnalysis::analyzeLockSpanCxtStmt()
{

    FunSet entryFuncSet = tct->getEntryProcs();
    for (FunSet::const_iterator it = entryFuncSet.begin(), eit = entryFuncSet.end(); it != eit; ++it)
    {
        if (!isLockCandidateFun(*it))
            continue;
        CallStrCxt cxt;
        CxtStmt cxtstmt(cxt, &((*it)->front().front()));
        pushToCTSWorkList(cxtstmt);
    }

    while (!cxtStmtList.empty())
    {
       ...;
        else if (isTDAcquire(curInst))
        {
            assert(hasCxtLock(cts) && "context-sensitive lock not found!!");
            if(addCxtStmtToSpan(cts,cts))
                handleIntra(cts);
        }
        else if (isTDRelease(curInst))   // handling lock release call
        {
            if(removeCxtStmtToSpan(cts,cts))
                handleIntra(cts);
        }
       ...;
    }
}
```

```
inline bool removeCxtStmtToSpan(CxtStmt& cts, const CxtLock& cl)
{
        bool find = cxtStmtToCxtLockSet[cts].find(cl)!=cxtStmtToCxtLockSet[cts].end();
        if(find)
        {
            cxtStmtToCxtLockSet[cts].erase(cl);
            cxtLocktoSpan[cl].erase(cts);
        }
        return find;
    }
```

**Comment by yuleisui** [comment]
Hi Ryan,

MTA has not been maintained after llvm-10.0.0. Did you make it compiled and work on the current SVF?

**Comment by ycaibb** [comment]
I work on the previous version of SVF on llvm-3.6.2. 
Yes, I noticed MTA hasn't been updated for a long term.

**Comment by yuleisui** [comment]
Would you mind helping us port it to the current version? Because we are now working on the lastest SVF. We can try to help you once it is ported here.

**Comment by ycaibb** [comment]
I would try it. Thank you.
