### ISSUE TITLE
Assertion violation at: lib/WPA/AndersenSFR.cpp:140

### ISSUE THREAD

**Issue by legendtang** [SVF-tools/SVF#320]
Hi, for the following bitcode (LLVM 10)

https://mega.nz/file/vZ4FlAYK#z_RUrsUz_3Ljfll67VGG-IcxiDSFl-t1O3e0uUWtUao
(The bc file is too large to attach here)

``
/wpa --sfrander gcc.bc
``

``
wpa: /home/username/SVF/lib/WPA/AndersenSFR.cpp:140: void SVF::AndersenSFR::fieldExpand(SVF::NodeSet&, SVF::Size_t, SVF::NodeBS&, SVF::PointsTo&): Assertion `false && "Not an object node!!"' failed.
``
Commit: 84bc1d1

**Comment by yuleisui** [comment]
@kisslune can you take a look at this issue?

**Comment by kisslune** [comment]
Hello @legendtang! Please try the newest version.

**Comment by legendtang** [comment]
> Hello @legendtang! Please try the newest version.

Just confirm the fix is functional. Thank you.
