### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by threeearcat** [SVF-tools/SVF#33]
When I conducted PTA, some of the source location is duplicated like
```
!!Target NodeID 16735	 [<__cleanup_mnt> Source Loc: in line: 1072 file:
/home/workspace/llvmlinux/targets/x86_64/src/linux/fs/namespace.cin line: 1072 file:
/home/workspace/llvmlinux/targets/x86_64/src/linux/fs/namespace.cin line: 1072 file:
...
...
/home/workspace/llvmlinux/targets/x86_64/src/linux/fs/namespace.cin line: 1072 file:
/home/workspace/llvmlinux/targets/x86_64/src/linux/fs/namespace.c]
```

Is this a bug? Please, can you check this?

**Comment by yuleisui** [comment]
Could you please show us how to reproduce your outputs?

My guess is that you may invoke the getSourceLoc function multiple times.

**Comment by threeearcat** [comment]
I got the duplicated result when I just executed the following command
`wpa -ander -print-all-pts $SOURCE_BC > $RESULT`
and $RESULT file contains the above result.
My commit is c586410ef1960dc0fe74cd30bab21ef46297d41e

**Comment by yuleisui** [comment]
The debug information is generated by clang/llvm which is not part of SVF. I believe it is not the bug of SVF. What's the side-effect of this output? Does it affect your analysis?

**Comment by threeearcat** [comment]
Not at all. Just the size of the output is slightly larger. 
But you mean the above problem is caused by clang/llvm? It makes me surprised though.
Whatever, I can ignore it.
