### ISSUE TITLE
DFPTData LLVM RTTI

### ISSUE THREAD

**Issue by mbarbar** [SVF-tools/SVF#330]
In refactoring the PTData classes, I was looking over the LLVM RTTI for them.

https://github.com/SVF-tools/SVF/blob/e5e780a46f62b53f1be611a260055fdf49db122f/include/MemoryModel/PointsToDFDS.h#L425-L428

This looks good.

https://github.com/SVF-tools/SVF/blob/e5e780a46f62b53f1be611a260055fdf49db122f/include/MemoryModel/PointsToDFDS.h#L429-L432

This looks correct but unnecessary and can be deleted.

https://github.com/SVF-tools/SVF/blob/e5e780a46f62b53f1be611a260055fdf49db122f/include/MemoryModel/PointsToDFDS.h#L433-L437

I believe this should be `return ptd->getPTDTY() == PTData<Key,Data>::IncDFPTD`.

The above 3 snippets are in `DFPTData`.

The code in the above snippet should replace the following (in `DFPTData`):
https://github.com/SVF-tools/SVF/blob/e5e780a46f62b53f1be611a260055fdf49db122f/include/MemoryModel/PointsToDFDS.h#L195-L198

Does all this sound correct?

**Comment by yuleisui** [comment]
Sounds correct to me. Please submit a patch for the fix.

> In refactoring the PTData classes, I was looking over the LLVM RTTI for them.
> 
> https://github.com/SVF-tools/SVF/blob/e5e780a46f62b53f1be611a260055fdf49db122f/include/MemoryModel/PointsToDFDS.h#L425-L428
> 
> This looks good.
> 
> https://github.com/SVF-tools/SVF/blob/e5e780a46f62b53f1be611a260055fdf49db122f/include/MemoryModel/PointsToDFDS.h#L429-L432
> 
> This looks correct but unnecessary and can be deleted.
>
Not quite sure. Would this be necessary?

> https://github.com/SVF-tools/SVF/blob/e5e780a46f62b53f1be611a260055fdf49db122f/include/MemoryModel/PointsToDFDS.h#L433-L437
> 
> I believe this should be `return ptd->getPTDTY() == PTData<Key,Data>::IncDFPTD`.
>
Yes, please fix this.

> The above 3 snippets are in `DFPTData`.
> 
> The code in the above snippet should replace the following (in `DFPTData`):
> 
> https://github.com/SVF-tools/SVF/blob/e5e780a46f62b53f1be611a260055fdf49db122f/include/MemoryModel/PointsToDFDS.h#L195-L198
> 
This code looks good to me.

> Does all this sound correct?

**Comment by mbarbar** [comment]
Great, I'll include in my refactoring.

> > https://github.com/SVF-tools/SVF/blob/e5e780a46f62b53f1be611a260055fdf49db122f/include/MemoryModel/PointsToDFDS.h#L429-L432
> > 
> > This looks correct but unnecessary and can be deleted.
> 
> Not quite sure. Would this be necessary?

Because the `classof(PTData...)` should be sufficient here. You can call the `PTData` version of `classof` with a `DFPTData` pointer. I was under the impression we need to handle the top-most root class (`PTData`) and the class itself (`IncDFPTData`), is that correct?

**Comment by yuleisui** [comment]
> Great, I'll include in my refactoring.
> 
> > > https://github.com/SVF-tools/SVF/blob/e5e780a46f62b53f1be611a260055fdf49db122f/include/MemoryModel/PointsToDFDS.h#L429-L432
> > > 
> > > This looks correct but unnecessary and can be deleted.
> > 
> > 
> > Not quite sure. Would this be necessary?
> 
> Because the `classof(PTData...)` should be sufficient here. You can call the `PTData` version of `classof` with a `DFPTData` pointer. I was under the impression we need to handle the top-most root class (`PTData`) and the class itself (`IncDFPTData`), is that correct?

It makes sense.
