### ISSUE TITLE
Incorporating indirect call resolution into ICFG.

### ISSUE THREAD

**Issue by prashast** [SVF-tools/SVF#342]
I have this following sample program with an indirect function call.
```
#include <stdio.h>

struct bar {
    int a;
    void (*fun_ptr)(int);
};

void foo(int);
void buggy();
void baz();


void foo(int b) {
    int c = b;
}

struct bar bar_struct = { 0, &foo };
int main() {
    baz();
}

void baz() {
    bar_struct.fun_ptr(10);
    buggy();
}

void buggy() {
    int a = 2;
}
```

There exists an indirect call edge from `baz->foo`. This edge is lifted correctly in the call graph. However, the same edge is not lifted in the ICFG. In #280, it was mentioned that there would be an `updateCallGraph` method that could be used to update ICFG with indirect calls. However, in the current master, the same method does not exist for ICFG. Could you let me know how can I incorproate the indirect call resolutions from the call graph into the ICFG?

**Comment by yuleisui** [comment]
ICFG can be updated with a callgraph which has resolved indirect calls. Please see here: https://github.com/SVF-tools/SVF/blob/master/include/Graphs/ICFG.h#L108

**Comment by prashast** [comment]
Sounds good to me. The commit I was working with was older than the one which was referenced in the issue, apologies.

**Comment by croemheld** [comment]
> ICFG can be updated with a callgraph which has resolved indirect calls. Please see here: https://github.com/SVF-tools/SVF/blob/master/include/Graphs/ICFG.h#L108

Just to make sure so that I don't have to create a new issue for this: Am I correct in my understanding that this function is only for extending an existing graph (generated via ICFG) with indirect edges coming from my own implementation on top of SVF? Or does ICFG do that by default?

My approach is to use something akin to constant propagation and try to significantly reduce the number of targets for indirect calls.

**Comment by yuleisui** [comment]
```
    SVFIRBuilder builder;
    SVFIR *svfir = builder.build(svfModule);
    PTACallGraph* callgraph = AndersenWaveDiff::createAndersenWaveDiff(svfir)->getPTACallGraph();
    builder.updateCallGraph(callgraph);
    ICFG *icfg = svfir->getICFG();
    icfg->updateCallGraph(callgraph);
    icfg->dump("icfg");
```

The above is simple way to update ICFG based on an input callgraph (with indirect calls resolved by Andersen's pointer analysis)
