### ISSUE TITLE
Adding precision to reachability analysis

### ISSUE THREAD

**Issue by prashast** [SVF-tools/SVF#344]
```
#include<stdio.h>

void foo(); 
void bar(); 
void baz(); 
void target();
 
int main() {
    foo(1);
    baz();
}
void foo(int choice) {
    if (choice == 1)
        target();
    else {
        bar();
    }
}
void baz() {
    foo(2);
}
void bar() {
    int a = 0;
}
void target() {
   int meh = 0;
}
```
Given this code snippet, let's assume the target function is `target`. As you can see foo can be called under two different contexts `main` and `baz`. Out of these two contexts, the one we are interested in is `main` and not `baz` since the latter does not reach our function of interest. If we were to perform the reachability analysis provided by SVF which operates on [call graph](https://github.com/SVF-tools/SVF/blob/master/include/Graphs/PTACallGraph.h#L436), it would say that `baz can reach target` which is incorrect because it is not taking into account the values with which `foo` is called.

Does SVF provide a way to make this reachability analysis more precise so that the analysis can say `main can reach target but baz cannot`. If not, could you point us to existing literature that we could use to extend SVF and incorporate such precision in a scalable manner?

**Comment by yuleisui** [comment]
Unfortunately not at this stage. This requires encoding the corresponding PAGEdges/LLVM Instructions using an SAT solver e.g., Z3. You may wish to explore it if you wish. 

For scalability, I guess the encoding could be done on SVFG to reduce the number of conditions to be solved in an SAT solver. It might be helpful to take a look at this implementation using BDDs.
https://github.com/SVF-tools/SVF/blob/master/include/Util/Conditions.h
