### ISSUE TITLE
SVFG: detect evaluation/value order

### ISSUE THREAD

**Issue by gerion0** [SVF-tools/SVF#358]
Just a question: It is somehow possible within the SVFG to detect the order (withing the CFG) of several events?

Let me clarify this with an example:
```
#include <stdio.h>

struct Foo {
	char i;

	void set(char a) { i = a; }
	void print() { putchar(i); }
};

int main() {
	Foo f;
	f.set('a');
	f.set('b');
	f.print();
}
```
It is obvious that this program outputs "b" on the terminal.
I'm trying to retrieve the same information with the SVF.

This is the resulting SVFG:
![svf](https://user-images.githubusercontent.com/32870336/103922765-82c3d500-5114-11eb-9cd4-6032ac512d4c.png)

If I see it right, "a" and "b" are modeled as StmtSVFGNodes that are connected to a PHISVFGNode (marked in red). I can follow the value point somehow up to this point but need to decide at this specific place whether "a" or "b" is the taken statement. I must decide about the order of "a" and "b" here.

Is there a way to retrieve this information from the SVFG? Or would I need to interpret the equivalent CFG?

**Comment by yuleisui** [comment]
Every SVFGNode resides in a unique ICFGNode. You can map the two SVFGNodes to their corresponding ICFGNodes (see here https://github.com/SVF-tools/SVF/blob/master/include/Graphs/VFGNode.h#L74) and use reachability analysis to know the order. 

In your example, the two function calls have an order, however, it seems to me that `a` and `b` are global variables. Do they have order?

**Comment by gerion0** [comment]
> Every SVFGNode resides in a unique ICFGNode. You can map the two SVFGNodes to their corresponding ICFGNodes (see here https://github.com/SVF-tools/SVF/blob/master/include/Graphs/VFGNode.h#L74) and use reachability analysis to know the order.

Ok, thank you. Is such an analysis already implemented?

> In your example, the two function calls have an order, however, it seems to me that `a` and `b` are global variables. Do they have order?

`a` and `b` are global variables without an order but their flow into `i` has an order. If I get it right, this flow is represented by the edges into the PHINode.

**Comment by yuleisui** [comment]
> > Every SVFGNode resides in a unique ICFGNode. You can map the two SVFGNodes to their corresponding ICFGNodes (see here https://github.com/SVF-tools/SVF/blob/master/include/Graphs/VFGNode.h#L74) and use reachability analysis to know the order.
> 
> Ok, thank you. Is such an analysis already implemented?
> 
There is no such analysis available, however, it should be easy to implement.
Here is an example that might be helpful: https://github.com/SVF-tools/SVF-example/blob/1b5edfbe9fdfc6461ea1abba11e5fc668bba2297/src/svf-ex.cpp#L80

> > In your example, the two function calls have an order, however, it seems to me that `a` and `b` are global variables. Do they have order?
> 
> `a` and `b` are global variables without an order but their flow into `i` has an order. If I get it right, this flow is represented by the edges into the PHINode.
Yes.

**Comment by gerion0** [comment]
> > > Every SVFGNode resides in a unique ICFGNode. You can map the two SVFGNodes to their corresponding ICFGNodes (see here https://github.com/SVF-tools/SVF/blob/master/include/Graphs/VFGNode.h#L74) and use reachability analysis to know the order.
> > 
> > 
> > Ok, thank you. Is such an analysis already implemented?
> 
> There is no such analysis available, however, it should be easy to implement.
> Here is an example that might be helpful: https://github.com/SVF-tools/SVF-example/blob/1b5edfbe9fdfc6461ea1abba11e5fc668bba2297/src/svf-ex.cpp#L80

Ok, I will try this.
