### ISSUE TITLE
Why are all constant objects treated as the same object?

### ISSUE THREAD

**Issue by kren1** [SVF-tools/SVF#36]
I'm trying to use the SVF pointer alias analysis to partition the  all abstract memory objects into disjoint sets. So I'm doing something like:

```C++
for(auto& idToType : *pag) {
        if(ObjPN* opn = dyn_cast<ObjPN>(idToType.second)) {
          unsigned nodeId = idToType.first;
          PointsTo& ptsToOrIsPointedTo = _pta->getPts(nodeId);
          ptsToOrIsPointedTo |= _pta->getRevPts(nodeId);
          ptsToOrIsPointedTo &= memObjects;
          if(!ptsToOrIsPointedTo.empty()) {
            ptsToOrIsPointedTo.set(nodeId);
            auto foundElem = std::find_if(disjointObjects.begin(), disjointObjects.end(),
              [&ptsToOrIsPointedTo](const PointsTo& e)
                  {return e.intersects(ptsToOrIsPointedTo);});
            if( foundElem == disjointObjects.end()) {
                disjointObjects.push_front(ptsToOrIsPointedTo);
            } else {
                *foundElem |= ptsToOrIsPointedTo;
            }
          }
        }
    }
```

However when considering something like:

```C
  char* p = cond ? "hello" : "world";
  char* q = "some other string"
```

I get disjoint set like: `[ 1(constObjId)  idOfP ifOfQ]`, which makes sense because SVF considers all constants as a single object. So I tried hacking a bit and changed `isConstantObjSym` to always return false. Which kind of gave me the right result in producing 2 disjoint sets: `[idOfP idOfhello idOfWorld]` and `[idOfQ idOfsomeotherstring]`. But it seems that it has assigned multiple ids to the constant string.

I don't understand SVF very well, so I'm wondering if there is a deeper reason (aside performance?) as to why constants are all a single object? 

Thanks!

**Comment by yuleisui** [comment]
Hi Timotej,

Merging constants into one object is for performance reason. This is common in pointer analysis.

Nevertheless, we have an option to model constants separately.

Please try "-modelConsts" (line 68 at MemModel.cpp) to see whether it can solve your case.

Yulei

**Comment by kren1** [comment]
Hi Yulei,

Thanks for the quick response. I think I can work from that. Cheers!

**Comment by kren1** [comment]
I played around with this a little more and I can't get it to work. I'm not sure how to show this but basically I get 2 representations of global variables.

Here is the output from my log:

```
...
[71 72 73 76 77 943 944 945]
943 -> 0x4bb8c98 tainted: 18 is FIObjPN: 0 is: @.str.5 = private unnamed_addr constant [6 x i8] c"sword\00", align 1
944 -> 0x4bb9a78 tainted: 15 is FIObjPN: 0 is: @.str.4 = private unnamed_addr constant [6 x i8] c"world\00", align 1
945 -> 0x4bba5f8 tainted: 12 is FIObjPN: 0 is: @.str.3 = private unnamed_addr constant [6 x i8] c"hello\00", align 1
...
[16 18]
18 -> 0x4bb8c98 tainted: 18 is FIObjPN: 1 is: @.str.5 = private unnamed_addr constant [6 x i8] c"sword\00", align 1
[183 184 185]
184 -> 0x4bff9d8 tainted: 184 is FIObjPN: 1 is:   %x = alloca i32, align 4
[13 15]
15 -> 0x4bb9a78 tainted: 15 is FIObjPN: 1 is: @.str.4 = private unnamed_addr constant [6 x i8] c"world\00", align 1
[122 123]
123 -> 0x4c076c8 tainted: 123 is FIObjPN: 1 is: 
[10 12]
12 -> 0x4bba5f8 tainted: 12 is FIObjPN: 1 is: @.str.3 = private unnamed_addr constant [6 x i8] c"hello\00", align 1
```

What I output is the dijoint sets, which are the numbers in square brackets and then I print more information about `MemObj`s in those sets. As you can see the first output has str.3, str.4 and str.5 grouped toghether along with some other stuff, which is exactly what I want. However  str3,4,5 also appear in sepearte nodeIDs 18,15,12 and they don't point to the other nodes! Which I don't understand why and sounds wrong? Furthermore, when I query the pag with the actual `llvm::GlobalVariable` with `pag->getObjNode()`, I get ids 12,15,18 for their respective global variables, so I can't get the ids from the group I want.

The only difference I can see is that the ids 12,15,18 are of type FIObjPN, whereas the other ones are GepObjPN.

The example I'm trying to analyze is this, I'm using SVF v1.3 with llvm3.8:

```C
void main() {
    int i,j;
    char *q = "bralalla";
    char* p = i > 2? "hello" : "world";
    p = j > 2 ? p : "sword";
    if(*p == 'h') {
        printf("trueBranch\n");
    } else {
      printf("falseBranch\n");
    } 
}
```

**Comment by kren1** [comment]
Hi Yulei,

Thanks for the quick and detailed response. I really appreciate the time.

I see now there can be both FIObjPN and GepObjPN. 

I think I resolved my problem, but if you are interested, my problem basically boils down to correlating `llvm::Value` to pag node IDs. If I get the pag node ID of an `llvm::GlobalVariable`,  it is the id of FIObj(12). If I get the pag node id of the pointer operand of a load instruction, I get back the id of GepObjNode (77). 

I would like those to be same ids. I can use `GepObjNode->getSymId()` to do it, which seems to do what I want. However I guess I lose some precision, if the global variable has multiple fields that can't alias. I don't see a way of going the other way ie. finding all the GepObjNodes of a FIObjNode.

**Comment by yuleisui** [comment]
Hmm, please try “getAllFieldsObjNode” in PAG.h. Hopefully, it will solve your problem.

We also have an interface to get base obj (FIObjPN) given a GepOBjPN in PAG.h

**Comment by kren1** [comment]
Ah, that should do the trick! Thanks again for all your help.
