### ISSUE TITLE
Assertion failed in wpa -nander -dump-pag 

### ISSUE THREAD

**Issue by charlesxsh** [SVF-tools/SVF#363]
Build from the master branch

./llvm-10.0.0.obj/bin/clang -S -fno-discard-value-names -emit-llvm test.c -o test.ll

test.c is simply:
```c
void swap(char **p, char **q){
  char* t = *p; 
       *p = *q; 
       *q = t;
}
int main(){
      char a1, b1; 
      char *a = &a1;
      char *b = &b1;
      swap(&a,&b);
}
```

wpa -nander -dump-pag test.ll
Writing 'pag_initial.dot'...Assertion failed: (llvm::isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file /Users/xsh/code/SVF/include/Util/Casting.h, line 315.

Could I get some help on this issue?

**Comment by yuleisui** [comment]
Just fixed https://github.com/SVF-tools/SVF/commit/06e1a489c3e51a2d56599a80f458efbc7778117d. The assertion was introduced due to a recent commit https://github.com/SVF-tools/SVF/commit/d2830c5080af15527eb31d858485fd6c5fb999c5

**Comment by charlesxsh** [comment]
@yuleisui Thanks. It solved the problem!
