### ISSUE TITLE
Is SVF::LLVMModuleSet support/safe to add module dynamically

### ISSUE THREAD

**Issue by charlesxsh** [SVF-tools/SVF#369]
I found that if the following code been used in a new LLVM `ModulePass`:
```cpp
bool runOnModule(Module &mod) override {
    SVF::SVFModule* svfModule = SVF::LLVMModuleSet::getLLVMModuleSet()->buildSVFModule(mod);
    SVF::PAGBuilder builder;
    SVF::PAG* pag = builder.build(svfModule);
}
```
I always can get segmentation fault at either SVF::SymbolTableInfo::buildMemModel or some other unknown places in runOnModule...

Did I do anything wrong or does anyone have some walkarounds?

**Comment by yuleisui** [comment]
What is the segmentation fault?

**Comment by charlesxsh** [comment]
► 0x7ffff1458318    mov    rax, qword ptr [0x10]

**Comment by charlesxsh** [comment]
Segmentation fault (happened inside of `runOnModule`) will happen if multiple LLVM module generated, means `runOnModule` will be triggered multiple times.

**Comment by yuleisui** [comment]
For multiple modules,  `loadModules(const std::vector<std::string> &moduleNameVec)` should be used 
 https://github.com/SVF-tools/SVF/blob/master/tools/Example/svf-ex.cpp#L154.

`buildSVFModule(Module &mod)` is supposed to be invoked only once if I remember correctly unless I can see the stack trace for the fault to understand more. You also feel free to change it for your purposes and let me once you get a patch.

**Comment by charlesxsh** [comment]
That's correct, however in LLVMPassManager, ModulePass will be triggered simultaneously for each module...seems like we don't have chance to use `loadModules(const std::vector<std::string> &moduleNameVec)` since `runOnModule(Module &mod)` only give one module at a time...

**Comment by charlesxsh** [comment]
Current walkaround is using local variable LLVMModuleSet, not singleton one.

**Comment by charlesxsh** [comment]
The solution is to find a way that compiler frontend only generate one unit/module...

**Comment by yuleisui** [comment]
I think another way is to call `LLVMModuleSet::releaseLLVMModuleSet()` and `PAG::releasePAG()` to release LLVMModule and the created PAG each time. It looks not very nice but might solve your problem.
