### ISSUE TITLE
Question about Points-to Analysis to statically detect all indirect function calls

### ISSUE THREAD

**Issue by nix7965** [SVF-tools/SVF#37]
Hi, 

I am trying to detect all indirect function calls via points-to analysis.
However, some of them are missing from my observation.
I have tried it with Andersen, AndersenWave, AndersenWaveDiff, AndersenWaveDiffWithType, AndersenLCD with LLVM 4.0. 

When I tried it with Andersen, I used the following codes.
> Andersen* pt = new Andersen();
> pt->analyze(*module);

Then, when I get callsite, I used the following set of codes.
> if(pt->hasIndCSCallees((CallInst*)cinst)){   // indirect
>      set <const llvm::Function*> indFuncSet = pt->getIndCSCallees((CallInst*)cinst);
>      for(auto ifs = indFuncSet.begin(); ifs != indFuncSet.end(); ++ifs){
>             calleeFunc = *ifs;           //This is an indirect callee candidate
>             ......
>      }
> }

Am I doing something wrong?
If so, could you tell me what is the most accurate way to detect all indirect callee?

**Comment by yuleisui** [comment]
Hello,

Please try the following to create pointer analysis and get callees of an indirect callsite.
```
AndersenWaveDiff* ander = AndersenWaveDiff::createAndersenWaveDiff(svfModule);
if(ander->hasIndCSCallees(callInst)){ 
     set <const llvm::Function*> indFuncSet = pt->getIndCSCallees(callInst);
}
```

Or you can also try to use PTACallGraph to get callEdges of an indirect callsite
````
PTACallGraph cg = ander->getCallGraph() 
        for (PTACallGraph::CallGraphEdgeSet::const_iterator cgIt = cg->getCallEdgeBegin(callInst),
                ecgIt = cg->getCallEdgeEnd(callInst); cgIt != ecgIt; ++cgIt) {
       }

```

**Comment by nix7965** [comment]
I used the old version. So, at that time, that version couldn't catch many indirect calls. But, the recent version seems to work correctly (even with any types of Andersen points-to analysis).
So, I close this issue.

**Comment by yuleisui** [comment]
The code I give you should work regardless the versions of SVF. Please check the difference between yours and my one in correct pointer analysis creation.
