### ISSUE TITLE
assertion violation 

### ISSUE THREAD

**Issue by van-ema** [SVF-tools/SVF#370]
I'm running SVF Anderson analysis at linking time through a driver LLVM pass.
Running the pass on nginx 1.4.0 I get the following violation:

```
SVF/include/Graphs/PAGNode.h:95: const Value* SVF::PAGNode::getValue() const: Assertion `(this->getNodeKind() != DummyValNode && this->getNodeKind() != DummyObjNode) && "dummy node do not have value!"' failed.
clang-9: error: unable to execute command: Aborted (core dumped)
```

**Comment by yuleisui** [comment]
It looks to me that you were trying to retrieve the value of a dummy pag node. Could you use `hasValue` before fetching their llvm value.

**Comment by van-ema** [comment]
Hi Yulei! yes, I'm using the `hasValue` operation. However I think the assertion violation is internally generated. Using the following patch I could successfully run the pass.

```
diff --git a/lib/WPA/Andersen.cpp b/lib/WPA/Andersen.cpp
index 390d0dd..9ec719f 100644
--- a/lib/WPA/Andersen.cpp
+++ b/lib/WPA/Andersen.cpp
@@ -663,7 +663,8 @@ void Andersen::connectCaller2CalleeParams(CallSite cs, const SVFFunction* F, Nod
 
             if (cs_arg->isPointer() && fun_arg->isPointer())
             {
-                DBOUT(DAndersen, outs() << "process actual parm  " << *(cs_arg->getValue()) << " \n");
+                               if (cs_arg->hasValue())
+                                       DBOUT(DAndersen, outs() << "process actual parm  " << *(cs_arg->getValue()) << " \n");
                 NodeID srcAA = sccRepNode(cs_arg->getId());
                 NodeID dstFA = sccRepNode(fun_arg->getId());
                 if(addCopyEdge(srcAA, dstFA))
```
 It looks to me that the `getValue` method gets invoked only for debugging purpose.

**Comment by yuleisui** [comment]
Just replace `getValue()` with `toString()`, please find it here: https://github.com/SVF-tools/SVF/commit/3d2f21c6226cb99a47dac349b9c5442f26d9ee4c
