### ISSUE TITLE
Question about SVF output

### ISSUE THREAD

**Issue by cssaheel** [SVF-tools/SVF#377]
I am trying to understand the example second to the last example graph: https://github.com/SVF-tools/SVF/wiki/Analyze-a-Simple-C-Program
![image](https://user-images.githubusercontent.com/1297249/109239070-a6191100-77a2-11eb-9742-9bd602dfa751.png)

I see node 25 pts-to 24, but there are no edges between nodes 24 and 25, how is that possible? Thank you.

**Comment by mbarbar** [comment]
This graph is an SVFG and the `X` in `NodeID: X` are SVFG node IDs, not variable (like memory objects) IDs. This is a data structure encoding control-flow (it is a fancy control-flow graph). The `Y` in `pts{Y ...}` are variables (memory objects, specifically). SVFG nodes and variable nodes are in separate namespaces, so to speak.

If you dump the constraint graph (but you can't do this for a flow-sensitive analysis), it may be more intuitive as nodes represent variables (implicit objects and explicit pointers) and edges represent an action. The black edge is a copy edge, so `s --black--> d` means `pt(d) = pt(d) U pt(s)`.

```
./bin/wpa -ander -print-all-pts -dump-consG file.bc
```

**Comment by cssaheel** [comment]
> This graph is an SVFG and the `X` in `NodeID: X` are SVFG node IDs, not variable (like memory objects) IDs. This is a data structure encoding control-flow (it is a fancy control-flow graph). The `Y` in `pts{Y ...}` are variables (memory objects, specifically). SVFG nodes and variable nodes are in separate namespaces, so to speak.
> 
> If you dump the constraint graph (but you can't do this for a flow-sensitive analysis), it may be more intuitive as nodes represent variables (implicit objects and explicit pointers) and edges represent an action. The black edge is a copy edge, so `s --black--> d` means `pt(d) = pt(d) U pt(s)`.
> 
> ```
> ./bin/wpa -ander -print-all-pts -dump-consG file.bc
> ```

Thank you for clarifying, but what is the purpose of "X <-- Y"? Is this used to represent data/objects flow across the SVFG nodes? For example, NODE-ID-3  has "17 <-- 18" does this mean the object 18 is flowing to 17? Thank you.

**Comment by mbarbar** [comment]
Sort of. These nodes with the arrow are statement nodes, so they represent a statement. Given `X <-- Y`...
* Green (addr.) means `X = &Y` (`pt(X) = { Y }`). This is what Node 3 is.
* Black (copy) means `X = Y` (`pt(X) = pt(X) U pt(Y)`)
* Blue (store) means `*X = Y` (`for all o in pt(X): pt(o) = pt(o) U pt(Y)`)
* Red (load) means `X = *Y` (`for all o in pt(Y): pt(X) = pt(X) U pt(o)`)

These are the most basic ones. You can see a full list of what the colours mean at https://github.com/SVF-tools/SVF/blob/d2edc40b77e5dede65f8b1d0b509acd854858b3a/lib/Graphs/SVFG.cpp

As for the edges between nodes...
* Edges which are unbroken are direct value-flow. `S ---> D` implies there is some top-level pointer (i.e., a pointer with a name that the programmer/compiler has made) defined at `S` and used at `D`.
* Edges which are dashed are indirect value-flow. `S - - -> D` implies there is some address-taken variable (i.e., an implicitly created memory object for the sake of the analysis, through, for example, `malloc`, which may represent many real memory objects) which is defined at `S` and used at `D`. These edges actually have labels which are not shown in the picture, like `S - - {o1, o2} - -> D`, for example, which means objects `o1` and `o2` are defined at `S` and used at `D`.

To clarify what is meant by top-level and address-taken variables. Consider C code `int *p = (int *)malloc(...)`. `p` is a top-level variable. To represent the memory `p` points to, which is returned by `malloc`, we create an "abstract memory object" which is referred to as an address-taken variable. Another example: in `int *x = &y`, `x` is a top-level pointer, and to represent the memory which `y` refers to, i.e., the memory at address `&y`, we create an abstract memory object.

**Comment by cssaheel** [comment]
Thank you so much for you detailed clarification, I wish you a pleasant day!
