### ISSUE TITLE
A Question about vtable parsing

### ISSUE THREAD

**Issue by benquike** [SVF-tools/SVF#382]
I am looking into the code for parsing vtable [here](https://github.com/SVF-tools/SVF/blob/master/lib/SVF-FE/CHG.cpp#L456) and have some questions.

Here, it seems that it is handling null pointers in the vtable after the typeinfo field.
First of all, I am not sure whether there are cases null pointers exist in the vtable.
If possible could you please give me a concrete example?

Secondly, later on in the same function [here](https://github.com/SVF-tools/SVF/blob/master/lib/SVF-FE/CHG.cpp#L570),
some other functions will be inserted into the places where null pointers are detected. Can you explain what is the reason behind this implementation?

Thanks!

**Comment by yuleisui** [comment]
This part of the code is not written by me. You feel free to improve it and would be good to give examples for comparison purposes. Thanks,
