### ISSUE TITLE
Support LLVM 12.0.0

### ISSUE THREAD

**Issue by sherlly** [SVF-tools/SVF#417]
Hello, 
I have tried to patch the SVF source code to support LLVM 12.0.0, this is my patch. https://github.com/sherlly/SVF/commit/39f2d9f97aa98eaa3f2f856cb456c2e0e651a16e

**Comment by yuleisui** [comment]
Thanks for your contribution! Would you mind submitting a pull request and pass the CI?

**Comment by sherlly** [comment]
> Thanks for your contribution! Would you mind submitting a pull request and pass the CI?

Sure, I have submitted it in https://github.com/SVF-tools/SVF/pull/418
