### ISSUE TITLE
Flow sensitive intra-procedural analysis and flow-insensitive context in-sensitive inter-procedural analysis

### ISSUE THREAD

**Issue by zhaogang92** [SVF-tools/SVF#42]
Hi, I just got to know this library. I am in need of flow sensitive intra-procedural analysis and flow-insensitive context in-sensitive inter-procedural analysis. Can any one give some tips about how to implement these two analyses based on this tool. This may save a lot of time. Thanks!

**Comment by yuleisui** [comment]
Hello,

Please see below:

1) set up following: https://github.com/SVF-tools/SVF/wiki/Setup-Guide-(CMake)
2) "cd $SVF_HOME" and ". ./setup"
3) "wpa -ander xxx.bc" flow-insensitive analysis
4) "wpa -fspta xxx.bc" flow-sensitive analysis

A simple way to use flow-insensitive analysis in SVF:
```
AndersenWaveDiff* ander = AndersenWaveDiff::createAndersenWaveDiff(svfModule);
```

To implement one:
https://github.com/SVF-tools/SVF/wiki/Write-a-flow--and-field---insensitive-pointer-analysis

For flow-sensitive implementation:
see 
https://github.com/SVF-tools/SVF/blob/master/lib/WPA/FlowSensitive.cpp

Good luck.

**Comment by zhaogang92** [comment]
Thanks!

I have went through the repo wiki. Now I think I understand how to do the flow-insensitive, context insensitive inter-procedural analysis part. But for the flow sensitive intra-procedural analysis, is any quick way to do this ?

**Comment by yuleisui** [comment]
https://github.com/SVF-tools/SVF/blob/master/lib/WPA/FlowSensitive.cpp
The above code implements an inter-procedural flow-sensitive analysis. It is not hard to derive an intra-procedural version on top of this.

I suggest you read some flow-sensitive analysis papers (e.g., Flow-sensitive pointer analysis for millions of lines of code) before you start implementing.
