### ISSUE TITLE
SVF detecting multiple callsites in thunk function and crashing

### ISSUE THREAD

**Issue by mbarbar** [SVF-tools/SVF#424]
Code I have been able to analyse before is coming up with this assertion:
```
wpa: /home/mbarbar/clone/svf/lib/SVF-FE/CPPUtil.cpp:303: const Function* SVF::cppUtil::getThunkTarget(const Function*): Assertion `ret == nullptr && "multiple callsites in thunk func"' failed.
```

This has happened a few times on different programs, and here's some example bitcode: 
[xpdf.zip](https://github.com/SVF-tools/SVF/files/6364097/xpdf.zip)

**Comment by yuleisui** [comment]
@benquike can you please take a look at this crash?

**Comment by mbarbar** [comment]
Will point out that the assertion a line up is triggered too.

**Comment by yuleisui** [comment]
> Will point out that the assertion a line up is triggered too.

Can you provide a bc crashed that line? Better to be smaller bc..

**Comment by mbarbar** [comment]
I think this one did: 
[xpdf.zip](https://github.com/SVF-tools/SVF/files/6373964/xpdf.zip)
not sure if `squid` did too. I haven't come across a smaller BC yet, and haven't investigated as I have no time.
