### ISSUE TITLE
SVF  compile error  on macOS Big Sur version 11.3,  clang 12

### ISSUE THREAD

**Issue by McFarlandSuber** [SVF-tools/SVF#433]
When I compile this project using ./build.sh, tons of errors happened.
I'm using macOS Big Sur Version 11.3 and my default clang version is 12.0.5 which as follow.
```
➜  SVF git:(master) ✗ clang --version
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.4.0
Thread model: posix
```
It looks like that some of the syntax in this project are not compatible with the latest C++ rule.

[ 34%] Building CXX object lib/CMakeFiles/Svf.dir/DDA/DDAStat.cpp.o
In file included from /Users/mcfarland/Workspace/Doing/SVF/lib/DDA/ContextDDA.cpp:8:
In file included from /Users/mcfarland/Workspace/Doing/SVF/include/Util/Options.h:8:
In file included from /Users/mcfarland/Workspace/Doing/SVF/include/MemoryModel/PointerAnalysisImpl.h:33:
In file included from /Users/mcfarland/Workspace/Doing/SVF/include/MemoryModel/PointerAnalysis.h:33:
In file included from /Users/mcfarland/Workspace/Doing/SVF/include/Graphs/PAG.h:34:
In file included from /Users/mcfarland/Workspace/Doing/SVF/include/Graphs/PAGEdge.h:34:
/Users/mcfarland/Workspace/Doing/SVF/include/Graphs/GenericGraph.h:98:19: error: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Werror,-Wnon-c-typedef-for-linkage]
    typedef struct
                  ^
                   equalGEdge
/Users/mcfarland/Workspace/Doing/SVF/include/Graphs/GenericGraph.h:100:9: note: type is not C-compatible due to this member declaration
        bool operator()(const GenericEdge<NodeType>* lhs, const GenericEdge<NodeType>* rhs) const
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mcfarland/Workspace/Doing/SVF/include/Graphs/GenericGraph.h:109:7: note: type is given name 'equalGEdge' for linkage purposes by this typedef declaration
    } equalGEdge;

**Comment by yuleisui** [comment]
Using the same macOS and clang, I did not have any compilation errors on my machine. Note that SVF imposes a more strict compilation process, i.e., any warning is treated as an error.

From your message, it looks to me that you are using a new C++20 feature to compile the repo, incurring a warning for anonymous type.  I can have a look if you share with us `CMakeCache.txt`  under $SVFHOME.

**Comment by McFarlandSuber** [comment]
This `CMakeCache.txt` is under $SVFHOME/Release , is that right?
[CMakeCache.txt](https://github.com/SVF-tools/SVF/files/6408706/CMakeCache.txt)

**Comment by yuleisui** [comment]
It seems to me that you are not using the default compiler in your CMakeCache.txt
```
//C compiler
CMAKE_C_COMPILER:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/cc
```
Type `cc -v`

You can send me your full error message or can try the following to build SVF again
```
cmake -DCMAKE_CXX_COMPILER=$LLVM_DIR/bin/clang++ -DLLVM_DIR=$LLVM_DIR
make
```

**Comment by McFarlandSuber** [comment]
I cloned the latest project again, following the guide manual, then it works.
By the way,  I must to create a soft link to  MacOSX11.3.sdk(the new one)   with  MacOSX11.1.sdk(which is needed to compile SVF but not available in current Xcode now)
https://www.lewuathe.com/no-rule-to-make-target-macosx-sdk.html
