### ISSUE TITLE
Does SVF-tool support transitive call or are there any possible strategies to reach it?

### ISSUE THREAD

**Issue by WSY66-hash** [SVF-tools/SVF#439]
Hi, sui ! The SVF-tool is working very well with the call graph generation jobs and contributes a lot to my related work, thanks a lot for your contribution. But still I got a question about its transitive call tracing ability cause it seems that it's now shown on the result that I have obtained. I am not quite sure about whether it's an incorrect use of SVF or not. 
I got a call chain from the dynamic case of my project and I am quite sure about its validity, which can be shown as below
```
['json_object_new', 'malloc', 'malloc_hook_ini', '_int_malloc']
```
the first api is from my project, and the left 3 apis are from libc-2.27.so, which is also known as glibc library too. 
After I have tried SVF, the result I have obtained is like below

```
['json_object_new', 'malloc']
```
so my question is, can SVF help to trace the apis called by "malloc"?  or are there any strategies to make it?
many thanks!

**Comment by yuleisui** [comment]
What do you mean by `apis called by "malloc"`?

Do you mean `malloc` redefined in your library?

**Comment by yuleisui** [comment]
You can also shorten your code (e.g., to around 100 lines) to reproduce your problem for us the inspect.

**Comment by WSY66-hash** [comment]
```malloc``` here is the original malloc function defined in glibc library and json_object_new is defined in my program.
To make it more clear, I just added the location of definition of the function within the parentheses, and the call chain can be shown as below
``` ['json_object_new(My program)', 'malloc(libc.so)', 'malloc_hook_ini(libc.so)', '_int_malloc(libc.so)']```
in this scenario, ```malloc``` is directly called by ```json_object_new```, and ``` 'malloc_hook_ini(libc.so)', '_int_malloc(libc.so)'``` are transitively called by  ```json_object_new```. and my question is that Is SVF capable of analyzing those transitive call **outside the program** ? cause the result i got is like 

```['json_object_new', 'malloc']```

and the code to reproduce the result is 
```C
static inline struct json_object *json_object_new(enum json_type o_type, size_t alloc_size,
                                                  json_object_to_json_string_fn *to_json_string)
{
	struct json_object *jso;

	jso = (struct json_object *)malloc(alloc_size);
	if (!jso)
		return NULL;

	jso->o_type = o_type;
	jso->_ref_count = 1;
	jso->_to_json_string = to_json_string;
	jso->_pb = NULL;
	jso->_user_delete = NULL;
	jso->_userdata = NULL;
	//jso->...   // Type-specific fields must be set by caller

#ifdef REFCOUNT_DEBUG
	lh_table_insert(json_object_table, jso, jso);
	MC_DEBUG("json_object_new_%s: %p\n", json_type_to_name(jso->o_type), jso);
#endif /* REFCOUNT_DEBUG */
	return jso;
}
```

**Comment by yuleisui** [comment]
This piece of code can not be compiled. Can you extract the code into a C file?

**Comment by WSY66-hash** [comment]
OK, let me simply my question in the following case. 
```C
#include <stdio.h>
int main(){
	int *a;
	a = (int *)malloc(15);
}
```
in this case, the result I have obtained from svf is like:
![main](https://user-images.githubusercontent.com/69136152/118666916-21301780-b826-11eb-981a-9a310e74a60c.png)
however if I use other dynamic trace tools(valgrind) to trace my program
The result I have obtained is like:
```
main(my program) --> malloc(libc.so) --> malloc_hook_ini(libc.so) -->_int_malloc(libc.so)
```
the function call malloc_hook_ini and _int_malloc are not shown. So is it possible for svf to trace the function call after "malloc"

the question can also be simplified as: if I used some third party APIs in my program via shared library(on linux it's via .so and on windows it's via .dll), is it possible for svf to trace the function calls within those third party shared library too?
Many thanks!

**Comment by yuleisui** [comment]
Unfortunately SVF can not trace into third party libraries whose source code is not available. In your case malloc will be treated as a memory allocation and it is the end point.

**Comment by WSY66-hash** [comment]
Many thanks! I am gonna close this issue.
