### ISSUE TITLE
SVFG construction fails: undefined PAG node

### ISSUE THREAD

**Issue by mbarbar** [SVF-tools/SVF#440]
For [`vis.bc`](https://github.com/SVF-tools/SVF/files/6527665/vis.zip), SVFG construction fails:
```
Assertion failed: (it!=PAGNodeToDefMap.end() && "PAG node does not have a definition??"), function getDef, file ../include/Graphs/VFG.h, line 407.
```

To reproduce,
```
./bin/wpa -fspta vis.bc
```

**Comment by yuleisui** [comment]
Just fixed. This is because SVF previously did not handle `VAArgInst and FreeezeInst`
https://github.com/SVF-tools/SVF/commit/04a069151d74ebbf800d96dc4d2f3c90283e13f0

**Comment by mbarbar** [comment]
Working now, thanks!
