### ISSUE TITLE
ContextDDA::isHeapCondMemObj not checking for NULL mem->getRefVal()

### ISSUE THREAD

**Issue by pietroborrello** [SVF-tools/SVF#444]
I have an abort triggered in 
```
/usr/lib/llvm-10/include/llvm/Support/Casting.h:105: 
static bool llvm::isa_impl_cl<llvm::Instruction, const llvm::Value *>::doit(const From *) [To = llvm::Instruction, From = const llvm::Value *]: 
Assertion `Val && "isa<> used on a null pointer"' failed.
```

Due to ContextDDA passing a NULL reference to `SVFUtil::dyn_cast<Instruction>()` in [ContextDDA::isHeapCondMemObj](https://github.com/SVF-tools/SVF/blob/2ecd7e23b19941dcb52929fa29cbe97a6a1a3eed/lib/DDA/ContextDDA.cpp#L318).
This is basically due to a MemObj being flagged as an HeapObj but having a NULL `refVal`.

I'm not sure whether having such an object is a different bug in itself, or if a HeapObj with a NULL `refVal` is valid, however I see   [MemObj::getType()](https://github.com/SVF-tools/SVF/blob/2ecd7e23b19941dcb52929fa29cbe97a6a1a3eed/lib/MemoryModel/MemModel.cpp#L287) checking for a NULL value in `refVal` before doing the same check, so probably it is just a missing check, and such an object is valid.

### details
I found this assert triggering while doing ContextDDA queries on [libxml2](https://gitlab.gnome.org/GNOME/libxml2.git), which is a pretty big project, it triggers after about 5h of analysis.

### version
llvm: 10
svf: 2.0

**Comment by yuleisui** [comment]
It is strange. If a mem object is flagged as a heap. It must be an instruction.

https://github.com/SVF-tools/SVF/blob/45460c79a7e8843f54bc0432e0f5bd6e5758e00e/lib/MemoryModel/MemModel.cpp#L146

Could you help check where the heap object is created other than here in your SVF version?

**Comment by pietroborrello** [comment]
Examining the aborting execution that I have in gdb, it seems that the MemObj is actually a `DummyObjNode` based on its `nodeKind`. Let me know any useful information that I could provide.
It seems also `MemObj::init` sets the HEAP_OBJ flag, both in my version and in master branch.

https://github.com/SVF-tools/SVF/blob/2ecd7e23b19941dcb52929fa29cbe97a6a1a3eed/lib/MemoryModel/MemModel.cpp#L243

**Comment by pietroborrello** [comment]
Sure I'll do a PR :)

**Comment by yuleisui** [comment]
Please also fix it in ContextDDA here:
https://github.com/SVF-tools/SVF/blob/45460c79a7e8843f54bc0432e0f5bd6e5758e00e/lib/DDA/ContextDDA.cpp#L318

**Comment by pietroborrello** [comment]
Isn't this already the only point that misses the NULL check? Is there any other point where should I add the check?

**Comment by yuleisui** [comment]
> Isn't this already the only point that misses the NULL check? Is there any other point where should I add the check?

Sorry, I misread. All good. Please submit the patch.

**Comment by pietroborrello** [comment]
submitted: #445

**Comment by pietroborrello** [comment]
I'm sorry to reopen this, but I have triggered the assert I put to check that the object is a dummy one, in a case that seems interesting (still libxml2, but after 7h).

https://github.com/SVF-tools/SVF/blob/67b4bb703bfc31083cad4bd827ea5e151f10b131/lib/DDA/ContextDDA.cpp#L320

The object that triggers the assert is a `SVF::GepObjPN` with id `1900048` with a `DummyObjPN` as a base object as shown below:
```cpp
➤  p/d *((GepObjPN*)pnode)
$29 = {
  <SVF::ObjPN> = {
    <SVF::PAGNode> = {
      <SVF::GenericNode<SVF::PAGNode, SVF::PAGEdge>> = {
        _vptr.GenericNode = 0x7ffff16e0c68 <vtable for SVF::GepObjPN+16>,
        id = 1900048,
        nodeKind = 5,
        InEdges = std::set with 0 elements,
        OutEdges = std::set with 0 elements
      }, 
      members of SVF::PAGNode:
      value = 0,
      InEdgeKindToSetMap = std::unordered_map with 0 elements,
      OutEdgeKindToSetMap = std::unordered_map with 0 elements,
      isTLPointer = 0,
      isATPointer = 1
    }, 
    members of SVF::ObjPN:
    mem = 316210528
  }, 
  members of SVF::GepObjPN:
  ls = {
    fldIdx = 17,
    byteOffset = 17,
    numStridePair = std::vector of length 0, capacity 0
  },
  base = 100048
}
```

with the base object with id `100048` being:
```cpp
➤  p/d *(DummyObjPN*)_pag->getPAGNode(100048)
$37 = {
  <SVF::ObjPN> = {
    <SVF::PAGNode> = {
      <SVF::GenericNode<SVF::PAGNode, SVF::PAGEdge>> = {
        _vptr.GenericNode = 0x7ffff16e09c0 <vtable for SVF::DummyObjPN+16>,
        id = 100048,
        nodeKind = 8,
        InEdges = std::set with 0 elements,
        OutEdges = std::set with 0 elements
      }, 
      members of SVF::PAGNode:
      value = 0,
      InEdgeKindToSetMap = std::unordered_map with 0 elements,
      OutEdgeKindToSetMap = std::unordered_map with 0 elements,
      isTLPointer = 0,
      isATPointer = 1
    }, 
    members of SVF::ObjPN:
    mem = 316210528
  }, <No data fields>}

```

Is this a valid object, that should be taken into consideration in the assert, or is this a bug? Does it make sense a GepObjPN on a dummy object?

Moreover, what bothers me is also the id assigned to the base dummy object: 100048.
According to `_pag->getNodeNumAfterPAGBuild()` returning `99405` in the buggy session, this should actually be a "GEP like" id, with offset 0 and base 48, so not a dummy object. And should not be possible to have an id > 100000 not being a GEP, as shown here for SVF-2.0:
https://github.com/SVF-tools/SVF/blob/7459133b6849a393af694fc20651817e51367080/lib/Graphs/PAG.cpp#L642
And moved here in the master branch:
https://github.com/SVF-tools/SVF/blob/dfdfb2dd96846345b1c0a59127ab8c3cff684fb0/lib/Util/NodeIDAllocator.cpp#L91
However, the node with id 48 is a `ValPN` node, corresponding to the LLVM Value `i16 990`, so a gep there would not make sense either.

**Comment by yuleisui** [comment]
> I'm sorry to reopen this, but I have triggered the assert I put to check that the object is a dummy one, in a case that seems interesting (still libxml2, but after 7h).
> 
> https://github.com/SVF-tools/SVF/blob/67b4bb703bfc31083cad4bd827ea5e151f10b131/lib/DDA/ContextDDA.cpp#L320
> 
> The object that triggers the assert is a `SVF::GepObjPN` with id `1900048` with a `DummyObjPN` as a base object as shown below:
> 
> ```c++
> ➤  p/d *((GepObjPN*)pnode)
> $29 = {
>   <SVF::ObjPN> = {
>     <SVF::PAGNode> = {
>       <SVF::GenericNode<SVF::PAGNode, SVF::PAGEdge>> = {
>         _vptr.GenericNode = 0x7ffff16e0c68 <vtable for SVF::GepObjPN+16>,
>         id = 1900048,
>         nodeKind = 5,
>         InEdges = std::set with 0 elements,
>         OutEdges = std::set with 0 elements
>       }, 
>       members of SVF::PAGNode:
>       value = 0,
>       InEdgeKindToSetMap = std::unordered_map with 0 elements,
>       OutEdgeKindToSetMap = std::unordered_map with 0 elements,
>       isTLPointer = 0,
>       isATPointer = 1
>     }, 
>     members of SVF::ObjPN:
>     mem = 316210528
>   }, 
>   members of SVF::GepObjPN:
>   ls = {
>     fldIdx = 17,
>     byteOffset = 17,
>     numStridePair = std::vector of length 0, capacity 0
>   },
>   base = 100048
> }
> ```
> 
> with the base object with id `100048` being:
> 
> ```c++
> ➤  p/d *(DummyObjPN*)_pag->getPAGNode(100048)
> $37 = {
>   <SVF::ObjPN> = {
>     <SVF::PAGNode> = {
>       <SVF::GenericNode<SVF::PAGNode, SVF::PAGEdge>> = {
>         _vptr.GenericNode = 0x7ffff16e09c0 <vtable for SVF::DummyObjPN+16>,
>         id = 100048,
>         nodeKind = 8,
>         InEdges = std::set with 0 elements,
>         OutEdges = std::set with 0 elements
>       }, 
>       members of SVF::PAGNode:
>       value = 0,
>       InEdgeKindToSetMap = std::unordered_map with 0 elements,
>       OutEdgeKindToSetMap = std::unordered_map with 0 elements,
>       isTLPointer = 0,
>       isATPointer = 1
>     }, 
>     members of SVF::ObjPN:
>     mem = 316210528
>   }, <No data fields>}
> ```
> 
> Is this a valid object, that should be taken into consideration in the assert, or is this a bug? Does it make sense a GepObjPN on a dummy object?

A GepObjPN can be derived from a dummy object. I think we need to have an assertion to include this case too.

> 
> Moreover, what bothers me is also the id assigned to the base dummy object: 100048.
> According to `_pag->getNodeNumAfterPAGBuild()` returning `99405` in the buggy session, this should actually be a "GEP like" id, with offset 0 and base 48, so not a dummy object. And should not be possible to have an id > 100000 not being a GEP, as shown here for SVF-2.0:
> https://github.com/SVF-tools/SVF/blob/7459133b6849a393af694fc20651817e51367080/lib/Graphs/PAG.cpp#L642
> 

From my understanding, `100048` means the base id is `1` and offset is `48` in the new SVF version?
@mbarbar would you take a look and clarify this?

> 
> And moved here in the master branch:
> https://github.com/SVF-tools/SVF/blob/dfdfb2dd96846345b1c0a59127ab8c3cff684fb0/lib/Util/NodeIDAllocator.cpp#L91
> 
> 
> However, the node with id 48 is a `ValPN` node, corresponding to the LLVM Value `i16 990`, so a gep there would not make sense either.

**Comment by mbarbar** [comment]
https://github.com/SVF-tools/SVF/blob/67b4bb703bfc31083cad4bd827ea5e151f10b131/lib/Util/NodeIDAllocator.cpp#L91-L95

For `master`, I agree with @pietroborrello. This would give us that 100048 is from:
* Base ID: 48
* Offset: 0 (first field)
* Multiplier: 100000

(0 + 1) * 100000 + 48 = 100048

Not sure how ContextDDA works, but in Andersen's/FS, I believe such a node wouldn't exist by default (`ff-eq-base` option), unless a path is not covered.

Regardless, 100048 being a base seems strange. Like you mention, it might be possible it shouldn't have been created as a dummy object in the first place, and should have been a GEP. I've run into a similar problem while writing another (unrelated) analysis a long time ago.

**Comment by yuleisui** [comment]
> https://github.com/SVF-tools/SVF/blob/67b4bb703bfc31083cad4bd827ea5e151f10b131/lib/Util/NodeIDAllocator.cpp#L91-L95
> 
> For `master`, I agree with @pietroborrello. This would give us that 100048 is from:
> 
> * Base ID: 48
> * Offset: 0 (first field)
> * Multiplier: 100000
> 
> (0 + 1) * 100000 + 48 = 100048
> 
> Not sure how ContextDDA works, but in Andersen's/FS, I believe such a node wouldn't exist by default (`ff-eq-base` option), unless a path is not covered.
> 
> Regardless, 100048 being a base seems strange. Like you mention, it might be possible it shouldn't have been created as a dummy object in the first place, and should have been a GEP. I've run into a similar problem while writing another (unrelated) analysis a long time ago.

`100048` can be created as a dummy object due to external calls here (I did not validate yet)
https://github.com/SVF-tools/SVF/blob/ca3ba613c51e7f99033ba2161ff77c3b169a6e57/lib/WPA/Andersen.cpp#L606

**Comment by yuleisui** [comment]
> Makes sense. Might be truly a base object then. 100048 is not far off from 99405.
> 
> This actually unearths another problem in that the GEP "namespace" might start clashing with other types of objects created sequentially (regardless of `DEBUG`). When name clashes happen in identifiers... debugging is a nightmare. I don't think this is the problem here though.
> 
I don't think it will be a clash according to the equation and we also have an assertion right after it:
https://github.com/SVF-tools/SVF/blob/67b4bb703bfc31083cad4bd827ea5e151f10b131/lib/Util/NodeIDAllocator.cpp#L95]]

> If we make the multiplier formula `pow(10, 1 + ceil ...`, it is not inconceivable then that the GEP namespace starts at 1 billion (when we have 1000000 values+objects), which makes 32 bit `NodeID`s too small.
In this case, we still have over 3billion nodes reserved for gepobjs:)

> 
> My opinion is to always `-node-alloc-strat=dense`, but I see the value in this scheme too. :)

**Comment by mbarbar** [comment]
>I don't think it will be a clash according to the equation and we also have an assertion right after it:
https://github.com/SVF-tools/SVF/blob/67b4bb703bfc31083cad4bd827ea5e151f10b131/lib/Util/NodeIDAllocator.cpp#L95]]

I noticed now it should probably not test against `numSymbols`, since `numSymbols` stops incrementing after initial PAG construction, but we keep sequentially adding objects through the likes of `allocateObjectId`. `numNodes` is also not something to test against since it includes GEP objects which aren't our problem here since the formula should protect against clashes between GEP objects (still possible for offsets like 10 and the problem in the next paragraph though...). What we want is something like `numNodesAllocatedFrom0ToNSequentially` or `greatestSequentiallyAllocatedNode`, but even this does not fix the problem described in the next paragraph.

Assuming we fix the assertion, the value we test against is a moving target. Consider:
* Initial PAG construction results in 999 symbols.
* The GEP multiplier is thus 100.
* The analysis creates a GEP object at 105 (passing the assertion).
* Andersen's (or another analysis) adds a dummy object.
* The GEP multiplier is thus now 1000.
* Though 105 already exists as a GEP object, and when the analysis tries to add a bunch of dummy objects... 105 will be "overwritten".

>In this case, we still have over 3billion nodes reserved for gepobjs:)
The formula is `id = (offset + 1) * gepMultiplier + base`. Assume we have a base of X, a `gepMultiplier of 1 billion` and an offset of 4. The result is 5 billion something (overflow).

**Comment by yuleisui** [comment]
> > I don't think it will be a clash according to the equation and we also have an assertion right after it:
> > [https://github.com/SVF-tools/SVF/blob/67b4bb703bfc31083cad4bd827ea5e151f10b131/lib/Util/NodeIDAllocator.cpp#L95]]](https://github.com/SVF-tools/SVF/blob/67b4bb703bfc31083cad4bd827ea5e151f10b131/lib/Util/NodeIDAllocator.cpp#L95%5D%5D)
> 
> I noticed now it should probably not test against `numSymbols`, since `numSymbols` stops incrementing after initial PAG construction, but we keep sequentially adding objects through the likes of `allocateObjectId`. `numNodes` is also not something to test against since it includes GEP objects which aren't our problem here since the formula should protect against clashes between GEP objects (still possible for offsets like 10 and the problem in the next paragraph though...). What we want is something like `numNodesAllocatedFrom0ToNSequentially` or `greatestSequentiallyAllocatedNode`, but even this does not fix the problem described in the next paragraph.
> 
I think `numSymbols` is the number of ValPN + ObjPN excluding GepObjPN. It should be fine, isn't it? 

> Assuming we fix the assertion, the value we test against is a moving target. Consider:
> 
> * Initial PAG construction results in 999 symbols.
> * The GEP multiplier is thus 100.
> * The analysis creates a GEP object at 105 (passing the assertion).

GepObj can only be created during points-to analysis and its id should greater than 999 not 105.

> * Andersen's (or another analysis) adds a dummy object.
> * The GEP multiplier is thus now 1000.
> * Though 105 already exists as a GEP object, and when the analysis tries to add a bunch of dummy objects... 105 will be "overwritten".
> 
> > In this case, we still have over 3billion nodes reserved for gepobjs:)
> 
> The formula is `id = (offset + 1) * gepMultiplier + base`. Assume we have a base of X, a `gepMultiplier of 1 billion` and an offset of 4. The result is 5 billion something (overflow).

**Comment by mbarbar** [comment]
>I think numSymbols is the number of ValPN + ObjPN (including DummyObj) excluding GepObjPN. It should be fine, isn't it?

`numSymbols` won't be incremented after the initial PAG construction, so it's missing the dummy object nodes. As long as the analysis does not create any non-GEPs, it's fine, otherwise, maybe not.

>GepObj can only be created during points-to analysis and its id should greater than 999 not 105.

Oh sorry, typo. That 999 should be 99 (then the multiplier is actually 100).

**Comment by yuleisui** [comment]
> > I think numSymbols is the number of ValPN + ObjPN (including DummyObj) excluding GepObjPN. It should be fine, isn't it?
> 
> `numSymbols` won't be incremented after the initial PAG construction, so it's missing the dummy object nodes. As long as the analysis does not create any non-GEPs, it's fine, otherwise, maybe not.

I see. DummyObjPN will only be created here:
https://github.com/SVF-tools/SVF/blob/e894db4946521ed22152099f679188eea95fc154/lib/WPA/Andersen.cpp#L636

So far it is very close to `numSymbols`, but we probably need to increase/update `numSymbols` when creating each DummyObjN?

> 
> > GepObj can only be created during points-to analysis and its id should greater than 999 not 105.
> 
> Oh sorry, typo. That 999 should be 99 (then the multiplier is actually 100).

**Comment by mbarbar** [comment]
Yes, or any other variable that encodes all non-GEP values + objects: so everything from 0 to N without any gaps.

However, this is still a moving target. An assert that succeeds once, may actually have failed if it occured later. If `numSymbols` is 99 now, and we allocate 105 to a GEP, what happens when Andersen's creates 6 new objects?

**Comment by yuleisui** [comment]
> Yes, or any other variable that encodes all non-GEP values + objects: so everything from 0 to N without any gaps.
> 
Yes, this will be the cleanest way.

> However, this is still a moving target. An assert that succeeds once, may actually have failed if it occured later. If `numSymbols` is 99 now, and we allocate 105 to a GEP, what happens when Andersen's creates 6 new objects?

One more change is that we do not allow creating dummyObj during analysis by adding an assertion `numSymbols = numNodes`when invoking the methods for adding dummyObj.

I will move these two lines to the PAGBuilding phase.
https://github.com/SVF-tools/SVF/blob/e894db4946521ed22152099f679188eea95fc154/lib/WPA/Andersen.cpp#L635-L636

**Comment by yuleisui** [comment]
@pietroborrello For now, I do not think your case is a correctness problem, but only the assertion you added cause the crash. We will need to add one more assertion for GepObjPN whose base is DummyObjPN. Something similar to the following code:

```
if(GepObjPN* gepobj = SVFUtil::dyn_cast<GepObjPN>(pnode)){
	assert(pag->getPAGNode(gepobj-> getBaseObjNode(gepobj->getId())) && "emtpy refVal in a gep object whose base is a non-dummy object");
}
else{
	assert((SVFUtil::isa<DummyObjPN>(pnode) || SVFUtil::isa<DummyValPN>(pnode)) && "emtpy refVal in non-dummy object");
}
```

**Comment by yuleisui** [comment]
Good!

As mentioned by @mbarbar you can always use `-node-alloc-strat=seq` or `-node-alloc-strat=dense` to allocate nodes sequentially so this problem will be gone.

**Comment by mbarbar** [comment]
>I will move these two lines to the PAGBuilding phase.

I think this is good. The PAG being more static gives less room for error.

>As mentioned by @mbarbar you can always use -node-alloc-strat=seq or -node-alloc-strat=dense to allocate nodes sequentially so this problem will be gone.

To add, Andersen's and FS and both far more performant with `=dense` than `=debug`. I don't know how well they work/fit in with the context sensitive and demand-driven stuff.

**Comment by pietroborrello** [comment]
Perfect, I'll bump up our dependency to SVF-2.1 then.
For the node allocator, it seems the default being documented as Stratagy::DENSE, but actually being DEBUG

Btw, created PR #451
