### ISSUE TITLE
mark the basicblock

### ISSUE THREAD

**Issue by xfang96** [SVF-tools/SVF#460]
Hi, Can I mark the relative basicblock or node in bitcode with SVF? For example , I want to mark all the dependent basicblock between a target source and sink. Is there fast way to finish this task? 
Thanks .

**Comment by yuleisui** [comment]
See here: https://github.com/SVF-tools/SVF-Teaching/blob/slides/slides/SVF_Teaching-Control-Data-Dependence.pdf

**Comment by xfang96** [comment]
> See here: https://github.com/SVF-tools/SVF-Teaching/blob/slides/slides/SVF_Teaching-Control-Data-Dependence.pdf

Yes I know , But I still want to catch the top-level def-use data-dependence between scalar variables. Is there a way to mark these nodes?
Thanks for your reply.

**Comment by yuleisui** [comment]
You can use alias results to get data dependence during control flow traversal
https://github.com/SVF-tools/SVF-Teaching/blob/slides/slides/SVF_Teaching-Taint-analysis.pdf
