### ISSUE TITLE
FFmpeg call-graph abort!

### ISSUE THREAD

**Issue by me22bee** [SVF-tools/SVF#469]
Hello,
I generate .bc file for ffmpeg using wllvm and now I want to extract the call-graph:
but It aborts in both `fspta` and `ander` mode.
 Is it because of my low memory space in both? or something else?
```
wpa -ander -dump-callgraph ffprobe_g.bc 
Writing 'callgraph_initial.dot'...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

```
wpa -fspta -dump-callgraph ffprobe_g.bc 
Writing 'callgraph_initial.dot'...
Writing 'callgraph_initial.dot'...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

**Comment by yuleisui** [comment]
Can you upload your bc for us to have a try?

**Comment by me22bee** [comment]
> Can you upload your bc for us to have a try?

yes, you can download it from [here](https://www.dropbox.com/s/h45ll3v0pznth0j/ffmpeg.bc?dl=0).
Thanks

**Comment by yuleisui** [comment]
It seems that you will have to use more memory for the analysis. Try `-node-alloc-strat=dense` to have another run.

**Comment by yuleisui** [comment]
`callgraph_initial.dot` is in fact generated but your analysis did not terminate due to the large size bc.

**Comment by me22bee** [comment]
> Try `-node-alloc-strat=dense`

what does it do?



> `callgraph_initial.dot`

what are the differences between the initial and final one?

**Comment by mbarbar** [comment]
`-node-alloc-strat=dense` allocates N memory objects from 0 to N, meaning that it they will result in smaller bit-vectors, hence less memory usage and faster unions.

SVF performs on-the-fly callgraph resolution from points-to results, so the final callgraph will include resolved indirect calls (e.g., that X calls Y due to a virtual call to Y in X).
