### ISSUE TITLE
Go from SVFG to LLVM values and back

### ISSUE THREAD

**Issue by gerion0** [SVF-tools/SVF#485]
I have searched for a function to get a SVFG node from an arbitrary LLVM value and go this way back.

However, this seems more difficult than expected. There exist a few methods for specific types of nodes but they often result in an assertion and so prevent further processing.

Here is a [minimal example/testcase for demonstration](https://gitlab.com/geri0n/svf-test):
```cpp
#include <llvm/Support/CommandLine.h>
#include <vector>
#include <string>
#include <SVF-FE/PAGBuilder.h>
#include <WPA/Andersen.h>
#include <llvm/IR/ValueSymbolTable.h>

static llvm::cl::opt<std::string> InputFilename(llvm::cl::Positional,
        llvm::cl::desc("<input bitcode>"), llvm::cl::init("-"));

const SVF::VFGNode* get_vfg_node(const SVF::SVFG& vfg, const llvm::Value* value) {
	SVF::PAG* pag = SVF::PAG::getPAG();
	SVF::PAGNode* pNode = pag->getPAGNode(pag->getValueNode(value));
	assert(pNode != nullptr);
	const SVF::VFGNode* vNode = vfg.getDefSVFGNode(pNode);
	assert(vNode != nullptr);
	return vNode;
}

int main(int argc, char ** argv) {
	int arg_num = 0;
	char **arg_value = new char*[argc];
	std::vector<std::string> moduleNameVec;
	SVF::SVFUtil::processArguments(argc, argv, arg_num, arg_value, moduleNameVec);
	llvm::cl::ParseCommandLineOptions(arg_num, arg_value,
                                "Whole Program Points-to Analysis\n");

	SVF::SVFModule* svfModule = SVF::LLVMModuleSet::getLLVMModuleSet()->buildSVFModule(moduleNameVec);
	llvm::Module* llvmModule = SVF::LLVMModuleSet::getLLVMModuleSet()->getMainLLVMModule();

	SVF::PAGBuilder builder;
	SVF::PAG *pag = builder.build(svfModule);

	SVF::Andersen *ander = SVF::AndersenWaveDiff::createAndersenWaveDiff(pag);

	SVF::SVFGBuilder svfBuilder;
	SVF::SVFG& svfg = *svfBuilder.buildFullSVFG(ander);
	svfg.dump("svfg");

	for (const auto& [_, node] : svfg) {
		llvm::errs() << "Node " << *node << "\n";
		if (auto s_node = llvm::dyn_cast<SVF::StmtVFGNode>(node)) {
			const llvm::Value* val = s_node->getPAGEdge()->getValue();
			// TODO does not work
			// auto n_node = get_vfg_node(svfg, val);
			// assert(s_node == n_node);
		} else if (auto s_node = llvm::dyn_cast<SVF::ActualParmVFGNode>(node)) {
			const llvm::Value* val = s_node->getParam()->getValue();
			auto n_node = get_vfg_node(svfg, val);
			assert(s_node == n_node);
		} else if (auto s_node = llvm::dyn_cast<SVF::FormalParmVFGNode>(node)) {
			const llvm::Value* val = s_node->getParam()->getValue();
			auto n_node = get_vfg_node(svfg, val);
			assert(s_node == n_node);
		} else if (auto s_node = llvm::dyn_cast<SVF::ActualRetVFGNode>(node)) {
			// TODO getRet vs getRev in ActualRet vs FormatRet?
			const llvm::Value* val = s_node->getRev()->getValue();
			auto n_node = get_vfg_node(svfg, val);
			assert(s_node == n_node);
		} else if (auto s_node = llvm::dyn_cast<SVF::FormalRetVFGNode>(node)) {
			const llvm::Value* val = s_node->getRet()->getValue();
			auto n_node = get_vfg_node(svfg, val);
			assert(s_node == n_node);
		} else if (auto s_node = llvm::dyn_cast<SVF::BinaryOPVFGNode>(node)) {
			const llvm::Value* val = s_node->getRes()->getValue();
			auto n_node = get_vfg_node(svfg, val);
			assert(s_node == n_node);
		} else if (auto s_node = llvm::dyn_cast<SVF::CmpVFGNode>(node)) {
			const llvm::Value* val = s_node->getRes()->getValue();
			auto n_node = get_vfg_node(svfg, val);
			assert(s_node == n_node);
		} else if (auto s_node = llvm::dyn_cast<SVF::UnaryOPVFGNode>(node)) {
			const llvm::Value* val = s_node->getRes()->getValue();
			auto n_node = get_vfg_node(svfg, val);
			assert(s_node == n_node);
		} else if (auto s_node = llvm::dyn_cast<SVF::PHIVFGNode>(node)) {
			const llvm::Value* val = s_node->getRes()->getValue();
			auto n_node = get_vfg_node(svfg, val);
			// TODO does not work
			// assert(s_node == n_node);
		} else if (auto s_node = llvm::dyn_cast<SVF::NullPtrVFGNode>(node)) {
			// no connected value (has PAGNode but no value)
		} else if (auto s_node = llvm::dyn_cast<SVF::MRSVFGNode>(node)) {
			// no connected value
		} else {
			assert(false && "Should not happen.");
		}
	}

	/*
	// TODO throws assertion
	// Is there a possibility to get as much as possible SVF Nodes?
	for (const auto& function : *llvmModule) {
		for (const auto& basic_block : function) {
			for (const auto& instruction : basic_block) {
				auto svf_node = get_vfg_node(svfg, &instruction);
			}
		}
	}
	*/

	for (const auto& value : llvmModule->getValueSymbolTable()) {
		auto svf_node = get_vfg_node(svfg, value.getValue());
	}
}
```

Is there a way to provide a working `get_vfg_node` function, that returns the correct `VFGNode`, if one exist and a `nullptr` otherwise? I'm especially interested in getting the `StmtVFGNode` back from a `llvm::StoreInst`. Is there a way to simplify the `llvm::Value` extraction, i.e. to not call a bunch of special methods on the derived classes?

Edit: Add repo link

**Comment by yuleisui** [comment]
Have you taken a look at the `toString()` method of each type of SVFGNodes?  I think it would be all there.

**Comment by yuleisui** [comment]
Sorry, I misunderstood your question. You can first retrieve the PAGNode and then get its def SVFGNode. Something similar as below:

```
pag->getPAGNode(llvm_value);
svfg->getDefSVFGNode(pagNode);
```

**Comment by gerion0** [comment]
> Sorry, I misunderstood your question. You can first retrieve the PAGNode and then get its def SVFGNode. Something similar as below:
> 
> ```
> pag->getPAGNode(llvm_value);
> svfg->getDefSVFGNode(pagNode);
> ```

Please take a look at the `get_vfg_node` function. It is actually pretty similar. However, that does not work for `StmtVFGNodes`. I guess, because they need a `PAGEdge` instead of a node?

**Comment by yuleisui** [comment]
> > Sorry, I misunderstood your question. You can first retrieve the PAGNode and then get its def SVFGNode. Something similar as below:
> > ```
> > pag->getPAGNode(llvm_value);
> > svfg->getDefSVFGNode(pagNode);
> > ```
> 
> Please take a look at the `get_vfg_node` function. It is actually pretty similar. However, that does not work for `StmtVFGNodes`. I guess, because they need a `PAGEdge` instead of a `PAGNode`?

You don't need to iterate every type of SVFGNodes. The following two lines should be good for your purpose.
```
PAGNode* pagnode = pag->getPAGNode(pag->getValueNode(llvm_value));
SVFGNode* svfgnode = svfg->getDefSVFGNode(pagNode);
```

**Comment by gerion0** [comment]
Maybe I'm overlooking something, but this is the exact code of the `get_vfg_node` function in the minimal example. However, when I'm uncommenting these lines, SVF fails with an assertion:
```
		if (auto s_node = llvm::dyn_cast<SVF::StmtVFGNode>(node)) {
			const llvm::Value* val = s_node->getPAGEdge()->getValue();
			// TODO does not work
			// auto n_node = get_vfg_node(svfg, val);
			// assert(s_node == n_node);
```

**Comment by yuleisui** [comment]
hmm,  it might be related to your bitcode and particular instructions. I guess some llvm value might not have a definition site. You can print it out if it fails (e.g., `toString`).

For you case, you can use `svfg->hasDef()` before your `svf-getDef()`.

**Comment by gerion0** [comment]
With [this example file](https://gitlab.com/geri0n/svf-test/-/blob/main/example.c) and this change:
```diff
diff --git a/main.cpp b/main.cpp
index 79383da..1ab06fa 100644
--- a/main.cpp
+++ b/main.cpp
@@ -43,7 +43,7 @@ int main(int argc, char ** argv) {
                if (auto s_node = llvm::dyn_cast<SVF::StmtVFGNode>(node)) {
                        const llvm::Value* val = s_node->getPAGEdge()->getValue();
                        // TODO does not work
-                       // auto n_node = get_vfg_node(svfg, val);
+                       auto n_node = get_vfg_node(svfg, val);
                        // assert(s_node == n_node);
                } else if (auto s_node = llvm::dyn_cast<SVF::ActualParmVFGNode>(node)) {
                        const llvm::Value* val = s_node->getParam()->getValue();
```
I got the following assert:
```
svf-test: ../subprojects/svf/include/Graphs/VFG.h:407: SVF::NodeID SVF::VFG::getDef(const SVF::PAGNode*) const: Assertion `it!=PAGNodeToDefMap.end() && "PAG node does not have a definition??"' failed.
```

Im pretty sure, that the error lies in the `PAGNode` vs `PAGEdge` usage. A `StmtVFGNode` seems to reference to a `PAGEdge`, which contains the `llvm::Value`. However, `pag->getPAGNode` returns a `PAGNode`. Is there a function to get also the `PAGEdge` for the `llvm::Value`?

I have also seen the function `VFG::getStmtVFGNode()`, which wants a `PAGEdge` and returns a `StmtVFGNode`. However, this function asserts, if there is no such `StmtVFGNode`. Can I check this condition beforehand? Also, I have no clue, how the get the `PAGEdge` back from the `llvm::Value`.

**Comment by yuleisui** [comment]
Typically, we do not want users to retrieve llvm values. This is the design principle of SVF to hide low-level llvm-IR.  Once you are in SVF, then you will not come back and forth. You can know where you are by using `toString()` method available for each type of Edge and Node. If you look into these `toString()` methods, you will know that not every node or edge is associated with an LLVM value.

For your assertion, it means that the llvm_value does not have a corresponding SVFGNode (you can print the value to know more. I guess it might be a constant value, such as an integer). As I mentioned you will need to add a conditional check.

From llvm_value to SVFGNode:
```
PAGNode* pagnode = pag->getPAGNode(pag->getValueNode(llvm_value));
if(svfg->hasDefSVFGNode(pagNode))
   SVFGNode* svfgnode = svfg->getDefSVFGNode(pagNode);
```


From SVFGNode to llvm_value

```
const PAGNode* pagnode = svfg->getLHSTopLevPtr(vfgnode);     // only eligible vfgnode, you need to take a look at the getLHSTopLevPtr
if(pagnode->hasValue())
  llvm_value = pagnode->getValue();
```

**Comment by gerion0** [comment]
> Typically, we do not want users to retrieve llvm values. This is the design principle of SVF to hide low-level llvm-IR. Once you are in SVF, then you will not come back and forth. You can know where you are by using `toString()` method available for each type of Edge and Node. If you look into these `toString()` methods, you will know that not every node or edge is associated with an LLVM value.

I understand your view. However, we are using the SVF as a library to assist in value finding. Large parts of the rest of the project operate directly on LLVM. So I need some kind of translation layer to get from an interesting (with that I mean, interesting for the surrounding project) value to the corresponding VFG node (if there is any).

I'm aware that not every node or edge is associated with an LLVM value. I'm only interested in the way from SVF to LLVM and back _if such a way exists_.


> For your assertion, it means that the llvm_value does not have a corresponding SVFGNode (you can print the value to know more. I guess it might be a constant value, such as an integer). As I mentioned you will need to add a conditional check.

The `llvm::Value` must have an corresponding `SVFGNode` because the `llvm::Value` is directly extracted from the `SVFGNode`.

With this change of the minimal example:
```diff
diff --git a/main.cpp b/main.cpp
index 79383da..fd2846c 100644
--- a/main.cpp
+++ b/main.cpp
@@ -41,9 +41,14 @@ int main(int argc, char ** argv) {
        for (const auto& [_, node] : svfg) {
                llvm::errs() << "Node " << *node << "\n";
                if (auto s_node = llvm::dyn_cast<SVF::StmtVFGNode>(node)) {
-                       const llvm::Value* val = s_node->getPAGEdge()->getValue();
+                       const SVF::PAGEdge* edge = s_node->getPAGEdge();
+                       llvm::errs() << "Corresponding PAGEdge: " << *edge << "\n";
+                       const llvm::Value* val = edge->getValue();
+                       llvm::errs() << "Corresponding llvm::Value " << *val << "\n";
+                       SVF::PAGNode* pNode = pag->getPAGNode(pag->getValueNode(val));
+                       llvm::errs() << "PagNode: " << *pNode << "\n";
                        // TODO does not work
-                       // auto n_node = get_vfg_node(svfg, val);
+                       auto n_node = get_vfg_node(svfg, val);
                        // assert(s_node == n_node);
                } else if (auto s_node = llvm::dyn_cast<SVF::ActualParmVFGNode>(node)) {
                        const llvm::Value* val = s_node->getParam()->getValue();
```

I got:

```
Node StoreVFGNode ID: 31 StorePE: [8<--7]	
   store %struct.ptrstruct* %P, %struct.ptrstruct** %P.addr, align 8 {  }
Corresponding PAGEdge: StorePE: [8<--7]	
   store %struct.ptrstruct* %P, %struct.ptrstruct** %P.addr, align 8 {  }
Corresponding llvm::Value   store %struct.ptrstruct* %P, %struct.ptrstruct** %P.addr, align 8
PagNode: ValPN ID: 12
   store %struct.ptrstruct* %P, %struct.ptrstruct** %P.addr, align 8 {  }
svf-test: ../subprojects/svf/include/Graphs/VFG.h:407: SVF::NodeID SVF::VFG::getDef(const SVF::PAGNode*) const: Assertion `it!=PAGNodeToDefMap.end() && "PAG node does not have a definition??"' failed.
```
So I'm able to go from the `StmtSVFGNode` to the corresponding `llvm::Value` exactly what `toString()` does, too.
But I cannot go back.

The obvious workaround would be to traverse the SVFG for statements nodes and create a backmap. But maybe such a map already exist. Like I said, I found such a map already for the mapping of PAGEdge -> SVFGNode (but it is quite inaccessible).

 
> From llvm_value to SVFGNode:
> 
> ```
> PAGNode* pagnode = pag->getPAGNode(pag->getValueNode(llvm_value));
> if(svfg->hasDefSVFGNode(pagNode))
>    SVFGNode* svfgnode = svfg->getDefSVFGNode(pagNode);
> ```
> 
> From SVFGNode to llvm_value
> 
> ```
> const PAGNode* pagnode = svfg->getLHSTopLevPtr(vfgnode);     // only eligible vfgnode, you need to take a look at the getLHSTopLevPtr
> if(pagnode->hasValue())
>   llvm_value = pagnode->getValue();
> ```

Thanks, this is a lot more generic than my solution in the example above. However, this fails for `StmtVFGNode`.

**Comment by yuleisui** [comment]
> > Typically, we do not want users to retrieve llvm values. This is the design principle of SVF to hide low-level llvm-IR. Once you are in SVF, then you will not come back and forth. You can know where you are by using `toString()` method available for each type of Edge and Node. If you look into these `toString()` methods, you will know that not every node or edge is associated with an LLVM value.
> 
> I understand your view. However, we are using the SVF as a library to assist in value finding. Large parts of the rest of the project operate directly on LLVM. So I need some kind of translation layer to get from an interesting (with that I mean, interesting for the surrounding project) value to the corresponding VFG node (if there is any).
> 
> I'm aware that not every node or edge is associated with an LLVM value. I'm only interested in the way from SVF to LLVM and back _if such a way exists_.
> 
> > For your assertion, it means that the llvm_value does not have a corresponding SVFGNode (you can print the value to know more. I guess it might be a constant value, such as an integer). As I mentioned you will need to add a conditional check.
> 
> The `llvm::Value` must have an corresponding `SVFGNode` because the `llvm::Value` is directly extracted from the `SVFGNode`.
> 
> With this change of the minimal example:
> 
> ```diff
> diff --git a/main.cpp b/main.cpp
> index 79383da..fd2846c 100644
> --- a/main.cpp
> +++ b/main.cpp
> @@ -41,9 +41,14 @@ int main(int argc, char ** argv) {
>         for (const auto& [_, node] : svfg) {
>                 llvm::errs() << "Node " << *node << "\n";
>                 if (auto s_node = llvm::dyn_cast<SVF::StmtVFGNode>(node)) {
> -                       const llvm::Value* val = s_node->getPAGEdge()->getValue();
> +                       const SVF::PAGEdge* edge = s_node->getPAGEdge();
> +                       llvm::errs() << "Corresponding PAGEdge: " << *edge << "\n";
> +                       const llvm::Value* val = edge->getValue();
> +                       llvm::errs() << "Corresponding llvm::Value " << *val << "\n";
> +                       SVF::PAGNode* pNode = pag->getPAGNode(pag->getValueNode(val));
> +                       llvm::errs() << "PagNode: " << *pNode << "\n";
>                         // TODO does not work
> -                       // auto n_node = get_vfg_node(svfg, val);
> +                       auto n_node = get_vfg_node(svfg, val);
>                         // assert(s_node == n_node);
>                 } else if (auto s_node = llvm::dyn_cast<SVF::ActualParmVFGNode>(node)) {
>                         const llvm::Value* val = s_node->getParam()->getValue();
> ```
> 
> I got:
> 
> ```
> Node StoreVFGNode ID: 31 StorePE: [8<--7]	
>    store %struct.ptrstruct* %P, %struct.ptrstruct** %P.addr, align 8 {  }
> Corresponding PAGEdge: StorePE: [8<--7]	
>    store %struct.ptrstruct* %P, %struct.ptrstruct** %P.addr, align 8 {  }
> Corresponding llvm::Value   store %struct.ptrstruct* %P, %struct.ptrstruct** %P.addr, align 8
> PagNode: ValPN ID: 12
>    store %struct.ptrstruct* %P, %struct.ptrstruct** %P.addr, align 8 {  }
> svf-test: ../subprojects/svf/include/Graphs/VFG.h:407: SVF::NodeID SVF::VFG::getDef(const SVF::PAGNode*) const: Assertion `it!=PAGNodeToDefMap.end() && "PAG node does not have a definition??"' failed.
> ```
> 
OK, I see. The problem here is that `store` instruction does not have any definition on LLVM's SSA, it indirectly defines an object. You will need to specify which operand you want to retrieve its definition (either value or pointer operand) when you have a `store` instruction.  

> So I'm able to go from the `StmtSVFGNode` to the corresponding `llvm::Value` exactly what `toString()` does, too.
> But I cannot go back.
> 
> The obvious workaround would be to traverse the SVFG for statements nodes and create a backmap. But maybe such a map already exist. Like I said, I found such a map already for the mapping of PAGEdge -> SVFGNode (but it is quite inaccessible).

For convenience, you can iterate through each PAGEdge on the PAG and maintain a map from PAGEdge to llvm_value since each edge is attached with a llvm_value or an empty value.
> 
> > From llvm_value to SVFGNode:
> > ```
> > PAGNode* pagnode = pag->getPAGNode(pag->getValueNode(llvm_value));
> > if(svfg->hasDefSVFGNode(pagNode))
> >    SVFGNode* svfgnode = svfg->getDefSVFGNode(pagNode);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > From SVFGNode to llvm_value
> > ```
> > const PAGNode* pagnode = svfg->getLHSTopLevPtr(vfgnode);     // only eligible vfgnode, you need to take a look at the getLHSTopLevPtr
> > if(pagnode->hasValue())
> >   llvm_value = pagnode->getValue();
> > ```
> 
> Thanks, this is a lot more generic than my solution in the example above. However, this fails for `StmtVFGNode`.

**Comment by gerion0** [comment]
Thank you, that clarifies my questions.

Would you accept such a map and methods that use it upstream?

For example:
```cpp
llvm::Value* SVFGNode::getLLVMValue(); // without assert, would return a nullptr, if not possible
SVFGNode* SVFG::fromLLVMValue(const llvm::Value*); // without assert, would return a nullptr, if not possible
PAGEdge* PAG::getValueEdge(const llvm::Value*) // this would use the newly created map
```

**Comment by yuleisui** [comment]
It looks good to me and good to have in the upstream. However, the last one is a bit tricky since it seems to me that one multiple PAGEdges might map to one llvm_value.

**Comment by yuleisui** [comment]
Could you submit a pull request?

**Comment by gerion0** [comment]
I will try.
