### ISSUE TITLE
Possibly incorrect flow-sensitive SVFG using FSPTA

### ISSUE THREAD

**Issue by ErrReporter** [SVF-tools/SVF#493]
Hi,

For the following LLVM bitcode, there is an obvious strong update at Lines 37-39:

```llvm
  store i8* %11, i8** %12, align 8
  store i8* null, i8** %12, align 8
  %13 = load i8*, i8** %12, align 8
```

and its corresponding SVFG:
![image](https://user-images.githubusercontent.com/57319574/127771323-04e3c0bd-2d17-4101-9144-ef696f2c6c7e.png)

in which I believe the left dashed indirect edge should not exist in a flow-sensitive analysis.

The SVF command is `wpa dfree2.bc -fspta`. Tested on the commit: 5042d7a99747a457b86c8602a84bd85ea9edd73a.

**Comment by yuleisui** [comment]
The SVFG does not support strong updates but the flow sensitive analysis does. So the dashed edge should always be there. The flow sensitive analysis algorithm on top of SVFG will not propagate the points-to from the first store to the second one if it refers to a singleton.

**Comment by ErrReporter** [comment]
> The SVFG does not support strong updates but the flow sensitive analysis does. So the dashed edge should always be there. The flow sensitive analysis algorithm on top of SVFG will not propagate the points-to from the first store to the second one if it refers to a singleton.

Well received with thanks. It seems if flow-sensitive SVFG exists, it will be very useful for future work.
