### ISSUE TITLE
Allocation through callsite arguments

### ISSUE THREAD

**Issue by kayondomartin** [SVF-tools/SVF#499]
I was wondering if there's a way to mark function calls that do allocate/reallocate memory to pointers passed to them as arguments. I'm trying to do some pointer analysis on a Rust program, and I realize I'm gonna have to add some settings on my own. Rust vectors may allocate memory when the push method is called. So, I'd like to mark the push method but haven't been able to find a way. C++ should have a similar case.

**Comment by yuleisui** [comment]
You can take a look at this file which might be helpful for your case:
https://github.com/SVF-tools/SVF/blob/master/include/Util/Annotator.h

**Comment by kayondomartin** [comment]
Thanks a lot for the prompt response
