### ISSUE TITLE
Possible wrong NoAlias result

### ISSUE THREAD

**Issue by anilavakundu** [SVF-tools/SVF#518]
Consider the code snippet below:

![issue](https://user-images.githubusercontent.com/41585874/134460844-8dc5f5cb-e861-467b-808b-93661d9c0b7c.jpg)

An alias query between %6 and %7 results in a NoAlias with both fspta and dda. I am using the default alias(Value* v1, Value* v2) function present in both of them

If I am not wrong it is a MustAlias(it is just casting the result of the call to int*) but if not MustAlias shouldn't the analyses be conservative enough to answer as a MayAlias? 

I checked the points-to sets of both the instruction they seem to be empty. I also found a lot of other NoAlias results I am not sure if they are correct. I am attaching the input LL file along with this.
[btSequentialImpulseConstraintSolver_mem.zip](https://github.com/SVF-tools/SVF/files/7215304/btSequentialImpulseConstraintSolver_mem.zip)

**Comment by yuleisui** [comment]
SVF's alias results are based on points-to analysis. Therefore, if %6 or %7 points to nothing, they will not be aliases.

I had a look at your ll file. `_Z22btAlignedAllocInternalmi` is an external function and we do not know its side-effect. Hence, the points-to set of %6 is null. You may wish to take a look at how to write a summary for an external function here:

https://github.com/SVF-tools/SVF/blob/master/lib/Util/ExtAPI.cpp#L30

**Comment by anilavakundu** [comment]
Hey thanks for the reply! I'll look into this
