### ISSUE TITLE
svfgNode or PagNode to llvm instruction

### ISSUE THREAD

**Issue by macromachine** [SVF-tools/SVF#52]
Hi, 
Do you have any map from svfgnode or pagnode to llvm instruction,  or its verse.

I'd like to use the result in SVF to other task.

Thanks

**Comment by yuleisui** [comment]
You may wish to take a look at the following two:

https://github.com/SVF-tools/SVF/blob/master/include/MSSA/SVFG.h#L199

https://github.com/SVF-tools/SVF/blob/master/include/MemoryModel/PAGNode.h#L189

**Comment by macromachine** [comment]
Thanks, 
I have found a function "getLLVMValue" in ProgSlic.cpp, which can get LLVM::Value* from svfgNode.
I think this function is a general approach.
