### ISSUE TITLE
Optimising SVFG and SVFG edge description

### ISSUE THREAD

**Issue by Ramakantj** [SVF-tools/SVF#553]
Hello

I have tried using -opt-svfg=false option while creating the graph but the graph does not change. ActualParm ActualIn FormalRet FormalOut nodes are still present. Is there any other way to generate a compact graph? Further, can the graph be reduced to just load/store on the pointers present in the code discarding other information?
Secondly, I couldn't find any documentation describing the different SVFG edges and their interpretation. Is it similar to the description given for the PAG?
Any inputs will be useful

**Comment by yuleisui** [comment]
Have you read this?

https://github.com/svf-tools/SVF/wiki/Technical-documentation#3-value-flow-construction

**Comment by Ramakantj** [comment]
Hi

Yes, I did go through it. Maybe didn't put my question correctly. I wanted to get the information regarding the color-coding scheme used for edges in the SVFG graph as is given for the PAG graph here: https://github.com/svf-tools/SVF/wiki/Analyze-a-Simple-C-Program#an-example. Though I found it now in the publication: https://yuleisui.github.io/publications/cc16.pdf

**Comment by yuleisui** [comment]
For colors, you can take a look here in VFG.cpp

https://github.com/SVF-tools/SVF/blob/9609395647cf5c791e9ab7d56bd90cbfcc3151c0/lib/Graphs/VFG.cpp#L1032

Also the same method in SVFG.cpp

**Comment by Ramakantj** [comment]
Thank you for sharing the file information. 
For optimizing the graph it will be helpful if you could point out the files involved where I can modify what nodes appear in the graph.

**Comment by yuleisui** [comment]
You can take a look at SVFGOPT.cpp:

https://github.com/SVF-tools/SVF/blob/master/lib/Graphs/SVFGOPT.cpp#L58-L62

**Comment by Ramakantj** [comment]
Okay.Thank you.
