### ISSUE TITLE
LocationSet::computeAllLocations coming up with a non-existant object?

### ISSUE THREAD

**Issue by mbarbar** [SVF-tools/SVF#555]
I'm a little confused on what this method is doing/how it works so bear with me.

The method fills in a points-to set and tries to insert a non-existent object into it. It does `result.set(ofst)` when `ofst == 3993`. This happens during FS, and I know with certainty 3993 does not occur in any points-to set produced by Andersen's, `NodeIDAllocator::get()->getNumObjects() == 3993` (dense), and there is no PAG node corresponding to 3993. This is causing a crash because, with clustering, the points-to set cares about the values of objects going in -- [assertion](https://github.com/mbarbar/svf-public/blob/e560e099653bb05e40805d53ceede0fb12da68ba/lib/Util/PointsTo.cpp#L291).

A hacky fix would be to use `NodeBS` instead of `PointsTo`, but I don't really understand what the aim is so that might be ignoring a correctness issue.

**Comment by yuleisui** [comment]
LocationSet class is really a bit messy. This is designed for bit offset model and actually not used in SVF. We may need some refactoring. I think NodeBS would be the solution to this problem.

**Comment by mbarbar** [comment]
Changed to `NodeBS`.
