### ISSUE TITLE
Questions about sat solver used in SVF

### ISSUE THREAD

**Issue by c2hpxq** [SVF-tools/SVF#561]
@yuleisui @mbarbar 
Hi, I've been using SVF for a while and have some questions concerned with constraint solving in SVF.

Q1: Is Z3 still actively used in SVF? I find that code concerned with representing condition with z3 seems to be commented out
```c
class PathCondAllocator
{
    ...
    typedef DdNode Condition;     /// bdd condition
    //typedef CondExpr Condition;   /// z3 condition
    ...
}
```
And it seems that `saber` doesn't have an option for choosing between CUDD&Z3. So can I take those as Z3 is deperacated?

Q2: Will it improve precision of analysis if we use Z3 as (sat/smt) solver in SVF? Or is it just a change in cond representation.
My perseonal answer is no since SVF doesn't take details of cond into consideration. However, since I may miss sth. in the code so I really need guidance here...

Q3: Is there any option for a **user-friendly** way of showing path boolean formula as ,e.g.,`C1/\C2`? The information outputed by `saber` under the option `-debug` is quite hard to understand.

Thanks in advance!

**Comment by yuleisui** [comment]
Thanks for your question. Unfortunately, z3 is not actively used. BDD is still the main solver (though not path-sensitive) in Saber. We may update Saber for path-sensitive symbolic execution later.

**Comment by c2hpxq** [comment]
Thanks for your reply! I think Q1&Q2 get perfectly answered :-)

About path-sensitive symbolic execution, I think it may be difficult to implement it starting from source node... since a lot of 'runtime' info is missing due to partial path (not starting from main)

Anyway, thanks again!

**Comment by yuleisui** [comment]
It will be a static symbolic execution, not like the one in Klee.

**Comment by c2hpxq** [comment]
I see... Currently KLEE (or maybe plus QSYM & SymCC) is all I know about (dynamic) symbolic execution. Willing to learn more about static symbolic execution....
