### ISSUE TITLE
Should the WPA solver unconditionally accept a new graph?

### ISSUE THREAD

**Issue by mbarbar** [SVF-tools/SVF#573]
Referring to this code:
https://github.com/SVF-tools/SVF/blob/de95143679d6b0d3ecc684daa958417623ad0000/include/WPA/WPASolver.h#L82-L87

Why is the assignment guarded behind `!scc`? In my mind, if the graph is to be updated, and `setGraph` is called, `scc` should be changed too. Currently, `_graph = g` means a new graph is set, but `scc` is not updated if it has been set before. Am I misunderstanding?

**Comment by yuleisui** [comment]
Yes, your understanding is correct. It looks that this is a problem. `setGraph` only be used once for each analysis I assume? 
The condition (line 85) should be removed.

**Comment by mbarbar** [comment]
Yes I think so.

In the case of FS, I don't think SCC even matters since it is for the SVFG but good to fix for later.

16 Dec. 2021 10:07:52 Yulei Sui ***@***.***>:

**Comment by yuleisui** [comment]
Just fixed https://github.com/SVF-tools/SVF/commit/a32913d6afb65e09a4363e5c44e0ccc3b381a055

**Comment by mbarbar** [comment]
Great, looks good.

16 Dec. 2021 10:51:01 Yulei Sui ***@***.***>:
