### ISSUE TITLE
Wrong number of templates arguments

### ISSUE THREAD

**Issue by v4lt** [SVF-tools/SVF#58]
Hello, i'm trying to integrate your work as an LLVM pass to reuse the result for an other pass.
I try to build it with llvm 6 but during the build i have severals errors like:

`llvm-6.0.0.src/include/llvm/Util/DataFlowUtil.h:210:85: error: wrong number of template arguments (1, should be 2)
 class IteratedDominanceFrontier: public llvm::DominanceFrontierBase<llvm::BasicBlock> {`

OR

`error: ‘iterator’ does not name a type
     iterator getIDFSet(llvm::BasicBlock *B) {`

Any ideas?

**Comment by yuleisui** [comment]
Hello,

You may wish to take a look at this thread: https://github.com/SVF-tools/SVF/issues/53


@zhaogang92

Hi Gang, could you please take a look at the issue? If possible, would you mind writing us a short wiki page about how to integrate SVF as a lib in your own project?
Thanks,
