### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by 251** [SVF-tools/SVF#580]
Hi,

When I'm using SVF on a small program:
```CPP
  auto * svf_module = SVF::LLVMModuleSet::getLLVMModuleSet()->buildSVFModule(*llvm_module);
  svf_module->buildSymbolTableInfo();
  SVF::PAGBuilder builder;
  auto * pag = builder.build(svf_module);
```
my application leaks hundreds of thousands of objects and roughly 14MB of memory. I had to use a rather large list of functions to tear down SVF:

```CPP
  // clean up
  auto * icfg = pag->getICFG();
  SVF::PAG::releasePAG();
  delete icfg;
  SVF::LLVMModuleSet::releaseLLVMModuleSet();
  delete svf_module;
  auto * extAPI = SVF::ExtAPI::getExtAPI();
  delete extAPI;
  SVF::NodeIDAllocator::unset();
  auto * threadAPI = SVF::ThreadAPI::getThreadAPI();
  delete threadAPI;
```

Is this the way it is supposed to be used or did I miss something in the documentation/examples? Furthermore, I had to change SVF to leak less memory (see: https://github.com/251/SVF/tree/fix_leaks):

* `GenericGraph` does not delete edges (https://github.com/251/SVF/commit/a4d6a2b70b3c93a5d90be72317445e39de1ecf18)
* `SVFModule` does not free pointers in `FunctionSet` (https://github.com/251/SVF/commit/dbd4b726909eb73357da32462d8261a4dc2abab6)
* `SymbolTableInfo` does not free `DataLayout` (https://github.com/251/SVF/commit/bfbf2c41aca74a2c088352abfc91cbf11f5a7dd5)

I'd provide a PR but I have no idea what the ownership semantics is in most cases (e.g. Does PAG own ICFG or should it be a shared_ptr for external usage? Who owns the edges in GenericGraph - the graph or a node?).

**Comment by yuleisui** [comment]
> 



> Hi,
> 
> When I'm using SVF on a small program:
> 
> ```c++
>   auto * svf_module = SVF::LLVMModuleSet::getLLVMModuleSet()->buildSVFModule(*llvm_module);
>   svf_module->buildSymbolTableInfo();
>   SVF::PAGBuilder builder;
>   auto * pag = builder.build(svf_module);
> ```
> 
> my application leaks hundreds of thousands of objects and roughly 14MB of memory. I had to use a rather large list of functions to tear down SVF:
> 
> ```c++
>   // clean up
>   auto * icfg = pag->getICFG();
>   SVF::PAG::releasePAG();
>   delete icfg;
>   SVF::LLVMModuleSet::releaseLLVMModuleSet();
>   delete svf_module;
>   auto * extAPI = SVF::ExtAPI::getExtAPI();
>   delete extAPI;
>   SVF::NodeIDAllocator::unset();
>   auto * threadAPI = SVF::ThreadAPI::getThreadAPI();
>   delete threadAPI;
> ```
> 
> Is this the way it is supposed to be used or did I miss something in the documentation/examples? Furthermore, I had to change SVF to leak less memory (see: https://github.com/251/SVF/tree/fix_leaks):
> 
> * `GenericGraph` does not delete edges ([251@a4d6a2b](https://github.com/251/SVF/commit/a4d6a2b70b3c93a5d90be72317445e39de1ecf18))
> * `SVFModule` does not free pointers in `FunctionSet` ([251@dbd4b72](https://github.com/251/SVF/commit/dbd4b726909eb73357da32462d8261a4dc2abab6))
> * `SymbolTableInfo` does not free `DataLayout` ([251@bfbf2c4](https://github.com/251/SVF/commit/bfbf2c41aca74a2c088352abfc91cbf11f5a7dd5))
> 
> I'd provide a PR but I have no idea what the ownership semantics is in most cases (e.g. Does PAG own ICFG or should it be a shared_ptr for external usage? Who owns the edges in GenericGraph - the graph or a node?).

Thanks for reporting this.  Do you mean that 14MB is the peak memory? It would be good to have a PR to clean up the unused memory.

ICFG is created inside PAG and they should both have one instance (Singleton) across all analyses.

GenericNode stores all its incoming/outgoing edges.

**Comment by 251** [comment]
> Do you mean that 14MB is the peak memory?

14MB is the amount of memory that is allocated by SVF but not freed on termination for one specific bitcode file (~18k lines incl. dbg info).

> ICFG is created inside PAG and they should both have one instance (Singleton) across all analyses.

So `releasePAG()` should free it or is there a case where a user might finish analyses and keep the ICFG around?

> GenericNode stores all its incoming/outgoing edges.

Then a node should free its edges instead of the `GenericGraph`.

I try to come up with a PR.

**Comment by yuleisui** [comment]
> 
`releasePAG()` should release both PAG and ICFG.

**Comment by 251** [comment]
@yuleisui 

What is the best place to delete `ThreadAPI`, `ExtAPI`, and `NodeIDAllocator`? In the destructor of `SVFModule` or should they be managed by a shared_ptr and every user deletes it?

**Comment by yuleisui** [comment]
`ThreadAPI`, `ExtAPI`, and `NodeIDAllocator` should all be destroyed when we release SVFModule.
