### ISSUE TITLE
unused variables

### ISSUE THREAD

**Issue by 251** [SVF-tools/SVF#583]
@mbarbar 

In a recent commit you added some unused variables (`first`/`second`). Maybe you wanted to use `first` instead of `p.first` in the return?
https://github.com/SVF-tools/SVF/blob/9903a9267761335a5a0318b3aade19e8a209969a/include/Util/SVFBasicTypes.h#L267

**Comment by mbarbar** [comment]
Oh, that's an oversight on my part. Yes, `first` and `second` should be used instead of `p.*`.

**Comment by yuleisui** [comment]
> Oh, that's an oversight on my part. Yes, `first` and `second` should be used instead of `p.*`.

Is this hash function being used anywhere? Could you make a PR to fix it?

**Comment by mbarbar** [comment]
Yes it is in use. The versioned PTData for example.

**Comment by 251** [comment]
Fixed in #585.
