### ISSUE TITLE
memory leak in MemSSA::newSSAName

### ISSUE THREAD

**Issue by 251** [SVF-tools/SVF#587]
`MRVer` objects are stored in `mr2VerStackMap` here:
https://github.com/SVF-tools/SVF/blob/d170bd248d00bb95f80b57372cf365faada6b221/lib/MSSA/MemSSA.cpp#L378

Later the underlying vector is manipulated just by `pop_back/clear` without freeing the objects. However, when I use `unique_ptr`s here, I got invalid reads via `SVF::SVFG::connectIndirectSVFGEdges() -> SVF::MRVer::getMR()`. I've no idea how to fix this without digging deeper. I guess it's easier for you to fix this.

As test case I used `svf-ex -ander -read-ander=ir_annotator single-inheritance-3.bc`.

**Comment by yuleisui** [comment]
Hmm, MRVer will be used and referred when building SVFG after MemSSA. Their liveness spans two phases MemSSA and SVFG construction. I believe we can destroy MRver once after SVFG is built

https://github.com/SVF-tools/SVF/blob/45460c79a7e8843f54bc0432e0f5bd6e5758e00e/lib/MSSA/SVFGBuilder.cpp#L110

**Comment by yuleisui** [comment]
I think `clearMSSA()` https://github.com/SVF-tools/SVF/blob/f35939d4207d99e8afd529ce54eedd484223dd03/lib/Graphs/SVFG.cpp#L187 should be invoked once after SVFG is built here:
https://github.com/SVF-tools/SVF/blob/45460c79a7e8843f54bc0432e0f5bd6e5758e00e/lib/MSSA/SVFGBuilder.cpp#L110
