### ISSUE TITLE
why some NodeIDs in PointsTo set are not found in PAG?

### ISSUE THREAD

**Issue by czcq** [SVF-tools/SVF#595]
![image](https://user-images.githubusercontent.com/16433413/148211232-cd727e28-3f11-49b3-9e69-3a47a7f4f31f.png)

; ModuleID = 'structtest.ll'
source_filename = "structtest.c"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.Test = type { i32, i32 }

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @main() #0 {
  %1 = alloca i32, align 4
  %2 = alloca %struct.Test, align 4
  %3 = alloca i32*, align 8
  %4 = alloca i32*, align 8
  store i32 0, i32* %1, align 4
  %5 = getelementptr inbounds %struct.Test, %struct.Test* %2, i32 0, i32 0
  store i32* %5, i32** %3, align 8
  %6 = getelementptr inbounds %struct.Test, %struct.Test* %2, i32 0, i32 1
  store i32* %6, i32** %4, align 8
  %7 = load i32*, i32** %3, align 8
  %8 = load i32*, i32** %4, align 8
  %9 = icmp eq i32* %7, %8
  %10 = zext i1 %9 to i32
  ret i32 %10
}

attributes #0 = { noinline nounwind optnone uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }

!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"uwtable", i32 1}
!2 = !{i32 7, !"frame-pointer", i32 2}
!3 = !{!"clang version 13.0.0"}

**I cannot find the allocation site id 26 in PAG**

**Comment by czcq** [comment]
![image](https://user-images.githubusercontent.com/16433413/148247888-5040b670-25c0-40b6-874c-a223cdc54e84.png)
**another question**
why ValPN ID: 75 is not exist in **Andersen Pointer Analysis Stats** output?

**Comment by yuleisui** [comment]
26 is a GepObjPN created during field-sensitive pointer analysis but not before. PAG or SVFIR only creates nodes and edges according to LLVM IR.

you can try `-dump-constraint-graph` to have a look.

**Comment by czcq** [comment]
> 26 is a GepObjPN created during field-sensitive pointer analysis but not before. PAG or SVFIR only creates nodes and edges according to LLVM IR.
> 
> you can try `-dump-constraint-graph` to have a look.

OK,I got it,Thanks for your replay ,sir :)

**Comment by czcq** [comment]
thanks！！

**Comment by czcq** [comment]
> ![image](https://user-images.githubusercontent.com/16433413/148211232-cd727e28-3f11-49b3-9e69-3a47a7f4f31f.png)
> 
> ; ModuleID = 'structtest.ll' source_filename = "structtest.c" target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128" target triple = "x86_64-unknown-linux-gnu"
> 
> %struct.Test = type { i32, i32 }
> 
> ; Function Attrs: noinline nounwind optnone uwtable define dso_local i32 @main() #0 { %1 = alloca i32, align 4 %2 = alloca %struct.Test, align 4 %3 = alloca i32*, align 8 %4 = alloca i32*, align 8 store i32 0, i32* %1, align 4 %5 = getelementptr inbounds %struct.Test, %struct.Test* %2, i32 0, i32 0 store i32* %5, i32** %3, align 8 %6 = getelementptr inbounds %struct.Test, %struct.Test* %2, i32 0, i32 1 store i32* %6, i32** %4, align 8 %7 = load i32*, i32** %3, align 8 %8 = load i32*, i32** %4, align 8 %9 = icmp eq i32* %7, %8 %10 = zext i1 %9 to i32 ret i32 %10 }
> 
> attributes #0 = { noinline nounwind optnone uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
> 
> !llvm.module.flags = !{!0, !1, !2} !llvm.ident = !{!3}
> 
> !0 = !{i32 1, !"wchar_size", i32 4} !1 = !{i32 7, !"uwtable", i32 1} !2 = !{i32 7, !"frame-pointer", i32 2} !3 = !{!"clang version 13.0.0"}
> 
> **I cannot find the allocation site id 26 in PAG**

![image](https://user-images.githubusercontent.com/16433413/148364900-725ae36d-d061-41a3-89a1-2cf0d8e9f420.png)

**node 26 is not in constaint graph either.. :(**

**Comment by czcq** [comment]
digraph "ConstraintG" {
	label="ConstraintG";

	Node0x56506255ecf0 [shape=record,shape=box,label="{11:}"];
	Node0x56506255ecf0 -> Node0x56506255bf70[color=red];
	Node0x56506255e9b0 [shape=record,shape=box,label="{9:}"];
	Node0x56506255e9b0 -> Node0x56506255e330[color=purple];
	Node0x56506255e9b0 -> Node0x56506255c590[color=purple];
	Node0x56506255e670 [shape=record,shape=box,label="{7:}"];
	Node0x56506255e330 [shape=record,shape=box,label="{17:}"];
	Node0x56506255e330 -> Node0x56506255a6f0[color=black];
	Node0x56506255e330 -> Node0x56506255ecf0[color=blue];
	Node0x56506255dff0 [shape=record,shape=box,label="{4:main}"];
	Node0x56506255d970 [shape=record,shape=diamond,label="{3:dummyVal}"];
	Node0x56506255d970 -> Node0x56506255d2f0[color=black];
	Node0x56506255d2f0 [shape=record,shape=diamond,label="{2:dummyVal}"];
	Node0x56506255cca0 [shape=record,shape=box,label="{13:}"];
	Node0x56506255cca0 -> Node0x56506255bc60[color=red];
	Node0x56506255c590 [shape=record,shape=box,label="{19:}"];
	Node0x56506255c590 -> Node0x56506255a3e0[color=black];
	Node0x56506255c590 -> Node0x56506255cca0[color=blue];
	Node0x56506255a3e0 [shape=record,shape=box3d,label="{14}"];
	Node0x56506255a3e0 -> Node0x56506255cca0[color=green];
	Node0x56506255a3e0 -> Node0x56506255bc60[color=black];
	Node0x56506255a6f0 [shape=record,shape=box3d,label="{12}"];
	Node0x56506255a6f0 -> Node0x56506255ecf0[color=green];
	Node0x56506255a6f0 -> Node0x56506255bf70[color=black];
	Node0x56506255aa00 [shape=record,shape=box3d,label="{10}"];
	Node0x56506255aa00 -> Node0x56506255e9b0[color=green];
	Node0x56506255ad10 [shape=record,shape=box3d,label="{8}"];
	Node0x56506255ad10 -> Node0x56506255e670[color=green];
	Node0x56506255bf70 [shape=record,shape=box,label="{21:}"];
	Node0x56506255b020 [shape=record,shape=box3d,label="{5}"];
	Node0x56506255b020 -> Node0x56506255dff0[color=green];
	Node0x56506255bc60 [shape=record,shape=box,label="{22:}"];
}

**Comment by yuleisui** [comment]
I see. This is because isolated nodes (node without incoming and outgoing edges) are not shown on the DOTGraph by default. Node 26 is an isolated gepObjNode. I have added an option `-show-hidden-nodes` in the latest patch.

https://github.com/SVF-tools/SVF/commit/6efb5ab7e8b2d9bdd253ad8930b5fe2cc84833fc#diff-f52f02b5ff627c3f489f4fe4988d016460244a4c3c7eb5eb4a246f96f5ec637eR631

You can turn it on and dump both PAG and ConsG. 26 is on both of them.

**Comment by czcq** [comment]
![image](https://user-images.githubusercontent.com/16433413/148382487-fa6b9b01-243a-42e6-9a52-f9e70eb93037.png)
I do see id 26 ! thanks for your really quick reply, very helpful!!!   :)
