### ISSUE TITLE
NodeIDAllocator  is not be released correctly

### ISSUE THREAD

**Issue by chenyang2022morecode** [SVF-tools/SVF#600]
I guess we need set ```allocator``` to ```nullptr``` after ```delete allocator```, otherwise ```*NodeIDAllocator::get(void)``` will return the allocator that has been free which leads to an UAF.

an [problem](https://github.com/SVF-tools/SVF-Teaching/issues/34) is related into this bug.

```
    NodeIDAllocator *NodeIDAllocator::get(void)
    {
        if (allocator == nullptr)
        {
            allocator = new NodeIDAllocator();
        }

        return allocator;
    }

    void NodeIDAllocator::unset(void)
    {
        if (allocator != nullptr)
        {
            delete allocator;
        }
    }
```

**Comment by czcq** [comment]
#601
