### ISSUE TITLE
Call run on module from an other pass

### ISSUE THREAD

**Issue by v4lt** [SVF-tools/SVF#61]
Hello again,

I create a pass to use your tool, so i integrate your tools in llvm and i can't figure out how to call WPAPass::runOnModule().

I want to call this function to get PTDataTy for flow sensitive pointer analysis.

But this function requires an svfModule and i have no idea how to instanciate it.

Any ideas?..

**Comment by yuleisui** [comment]
Take a look at this file to know how to run a pointer analysis.
https://github.com/SVF-tools/SVF/blob/master/lib/WPA/WPAPass.cpp

How to dump and use points-to info:
https://github.com/SVF-tools/SVF/blob/f6d9758675e6bb31e61e13c33503ab90242fcb25/lib/MemoryModel/PointerAnalysis.cpp#L494

**Comment by v4lt** [comment]
The fact is wish to do something like this:
`bool runOnFunction(Function &F) override {
      std::vector<std::string> moduleNameVec;
      moduleNameVec.push_back(F.getParent()->getName())
      //SVFModule svfModule(moduleNameVec); ? 
      getAnalysis<WPAPass>().runOnModule(svfModule);`

This code is write in an other pass, is it possible to construct an svfModule myself?

**Comment by yuleisui** [comment]
LLVM pass design has know issues. As SVF evolves, we don’t implement LLVM passes, rather, you can simply create an analysis instance for your purpose. SVFModule is a wrapper for LLVM module to support multiple module analysis. You can create an SVF module with an LLVM one as its parameter.

**Comment by v4lt** [comment]
Ok i succeed even if i have an error, it apperas at the very end of the pass so i can attack the API before.

`LLVMSymbolizer: error reading file: No such file or directory
#0 0x0000000003b8e609 (opt+0x3b8e609)
#1 0x0000000003b8e69c (opt+0x3b8e69c)
#2 0x0000000003b8c885 (opt+0x3b8c885)
`

I have a last question, if i want a pointsTo information for a precise instruction of a program (flow-sensitive). The easiet way to obtains this information is with DFPTData or IncDFPTData?

**Comment by yuleisui** [comment]
Please refer the following API to get the points-to information at a statement (SVFGNode):
https://github.com/SVF-tools/SVF/blob/f6d9758675e6bb31e61e13c33503ab90242fcb25/include/WPA/FlowSensitive.h#L217
