### ISSUE TITLE
LPA a part of SVF

### ISSUE THREAD

**Issue by anilavakundu** [SVF-tools/SVF#613]
Hi 

I was wondering if LPA (read:https://yuleisui.github.io/publications/lctes16.pdf) is still a part of SVF or if it was removed.

Regards

**Comment by yuleisui** [comment]
Unfortunately, not available in SVF yet.

**Comment by anilavakundu** [comment]
Hi 

Thanks for the reply. 
Is it at all possible to get an implementation of it considering it to be an open-source work? Or any plans to integrate it with SVF perhaps?

Regards

**Comment by yuleisui** [comment]
We are currently working on array-based analysis and might release the code in due course.
