### ISSUE TITLE
Flow-sensitivity and def-use on SVFG

### ISSUE THREAD

**Issue by teozoia** [SVF-tools/SVF#620]
I'm building a simple algorithm that takes an alloca instruction and finds all its use (filtered by `store` use only).
For doing that I've used the
```cpp
// An example to query/collect all the uses of a definition of a value along value-flow graph (VFG)
void traverseOnVFG(const SVFG* vfg, Value* val)
```
from the example file `svf-ex.cpp` with an alloca instruction as parameeter.
In particular I'm working on 2 different examples:

Example 1 `traverseOnVFG(svfg, %x = alloca i8, align 1) `

```c
char x = fgetc(stdin);
char y1, y2;
int c = 10;
if(c < 5)
    y1 = x;
else
    y2 = x;
```

Example 2 `traverseOnVFG(svfg, %a = alloca i8, align 1) `

```c
char a = fgetc(stdin);
char b = 'T';
char *x = &a;
x = &b;

char *z;
z = x;
```

I've tried feeding the algorithm with different pointer analysis (Ander and FlowSensitive) to build the SVFG but the uses finded (filtered only by `store`) are the same for flow-sensitive and flow-insensitive analysis. 

Example 1 starting from `%x = alloca i8, align 1`, Ander and FlowSensitive finds: 

```
store i8 %3, i8* %y2, align 1
store i8 %2, i8* %y1, align 1
store i8 %conv, i8* %x, align 1
```

Example 2 starting from `%a = alloca i8, align 1`, Ander and FlowSensitive finds: 

```
store i8* %1, i8** %z, align 4
store i8* %b, i8** %x, align 4
store i8* %a, i8** %x, align 4
store i8 %conv, i8* %a, align 1 
```

Is it correct? I'm expecting to not find `store i8 %2, i8* %y1, align 1` in the first example with FlowSensitive and to not find `store i8* %1, i8** %z, align 4` in the second example with FlowSensitive because `x = &b` breaks the flow.

Example 1 bitcode

```
define dso_local i32 @main(i32 %argc, i8** %argv) #0 {
entry:
  %retval = alloca i32, align 4
  %argc.addr = alloca i32, align 4
  %argv.addr = alloca i8**, align 4
  %x = alloca i8, align 1
  %y1 = alloca i8, align 1
  %y2 = alloca i8, align 1
  %c = alloca i32, align 4
  store i32 0, i32* %retval, align 4
  store i32 %argc, i32* %argc.addr, align 4
  store i8** %argv, i8*** %argv.addr, align 4
  %0 = load %struct._IO_FILE*, %struct._IO_FILE** @stdin, align 4
  %call = call i32 @fgetc(%struct._IO_FILE* %0)
  %conv = trunc i32 %call to i8
  store i8 %conv, i8* %x, align 1
  store i32 10, i32* %c, align 4
  %1 = load i32, i32* %c, align 4
  %cmp = icmp slt i32 %1, 5
  br i1 %cmp, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %2 = load i8, i8* %x, align 1
  store i8 %2, i8* %y1, align 1
  br label %if.end

if.else:                                          ; preds = %entry
  %3 = load i8, i8* %x, align 1
  store i8 %3, i8* %y2, align 1
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  ret i32 0
}
```

Example 2 bitcode

```
define dso_local i32 @main(i32 %argc, i8** %argv) #0 {
entry:
  %retval = alloca i32, align 4
  %argc.addr = alloca i32, align 4
  %argv.addr = alloca i8**, align 4
  %a = alloca i8, align 1
  %b = alloca i8, align 1
  %x = alloca i8*, align 4
  %z = alloca i8*, align 4
  store i32 0, i32* %retval, align 4
  store i32 %argc, i32* %argc.addr, align 4
  store i8** %argv, i8*** %argv.addr, align 4
  %0 = load %struct._IO_FILE*, %struct._IO_FILE** @stdin, align 4
  %call = call i32 @fgetc(%struct._IO_FILE* %0)
  %conv = trunc i32 %call to i8
  store i8 %conv, i8* %a, align 1
  store i8 84, i8* %b, align 1
  store i8* %a, i8** %x, align 4
  store i8* %b, i8** %x, align 4
  %1 = load i8*, i8** %x, align 4
  store i8* %1, i8** %z, align 4
  ret i32 0
}
```

**Comment by yuleisui** [comment]
I believe you are supposed to start from `  %call = call i32 @fgetc(%struct._IO_FILE* %0)` which is the return value from `fgetc` for your purposes.

**Comment by teozoia** [comment]
Ok but I want to understand the def-use of `x` (example 1) and `a` (example 2) and why the `traverseOnVFG(svfg, %x = alloca i8, align 1)` and `traverseOnVFG(svfg, %a = alloca i8, align 1)` seems to be flow-insensitive using FlowSensitive analysis.

**Comment by teozoia** [comment]
I'm reposting the question, I'm trying to understand the `FlowSensitive` analysis.

In this snippet of code I want to find the use of `a` with `traverseOnVFG(const SVFG* vfg,  %a = alloca i8, align 1)` taken from `svf-ex.cpp`:

```c
char a = fgetc(stdin);
char b = 'T';
char *x = &a;
x = &b;

char *z;
z = x;
```

I've modified the `svf-ex.cpp` to test `Ander` analysis and `FlowSensitive` analysis. The output of `traverseOnVFG` (filtered only by `store` operations) is the same for both the analysis: 

```
store i8* %1, i8** %z, align 4
store i8* %b, i8** %x, align 4
store i8* %a, i8** %x, align 4
store i8 %conv, i8* %a, align 1 
```

Is it correct? I'm expecting not to find `store i8* %1, i8** %z, align 4` with `FlowSensitive` analysis because `x = &b` breaks the flow.

```
define dso_local i32 @main(i32 %argc, i8** %argv) #0 {
entry:
  %retval = alloca i32, align 4
  %argc.addr = alloca i32, align 4
  %argv.addr = alloca i8**, align 4
  %a = alloca i8, align 1
  %b = alloca i8, align 1
  %x = alloca i8*, align 4
  %z = alloca i8*, align 4
  store i32 0, i32* %retval, align 4
  store i32 %argc, i32* %argc.addr, align 4
  store i8** %argv, i8*** %argv.addr, align 4
  %0 = load %struct._IO_FILE*, %struct._IO_FILE** @stdin, align 4
  %call = call i32 @fgetc(%struct._IO_FILE* %0)
  %conv = trunc i32 %call to i8
  store i8 %conv, i8* %a, align 1
  store i8 84, i8* %b, align 1
  store i8* %a, i8** %x, align 4
  store i8* %b, i8** %x, align 4
  %1 = load i8*, i8** %x, align 4
  store i8* %1, i8** %z, align 4
  ret i32 0
}
```

**Comment by yuleisui** [comment]
> I'm reposting the question, I'm trying to understand the `FlowSensitive` analysis.
> 
> In this snippet of code I want to find the use of `a` with `traverseOnVFG(const SVFG* vfg, %a = alloca i8, align 1)` taken from `svf-ex.cpp`:
> 
> ```c
> char a = fgetc(stdin);
> char b = 'T';
> char *x = &a;
> x = &b;
> 
> char *z;
> z = x;
> ```
> 
> I've modified the `svf-ex.cpp` to test `Ander` analysis and `FlowSensitive` analysis. The output of `traverseOnVFG` (filtered only by `store` operations) is the same for both the analysis:
> 
> ```
> store i8* %1, i8** %z, align 4
> store i8* %b, i8** %x, align 4
> store i8* %a, i8** %x, align 4
> store i8 %conv, i8* %a, align 1 
> ```
> 
> Is it correct? I'm expecting not to find `store i8* %1, i8** %z, align 4` with `FlowSensitive` analysis because `x = &b` breaks the flow.

The above results are correct to me. Flow-insensitive and flow-sensitive analyses can yield the same results for top-level pointers. In your case, they are the same on the IR for `%x`, therefore producing the same SVFG. For strong updates during traversal, you may wish to take a look at page 16 in these slides to understand a bit more:
https://github.com/SVF-tools/Teaching-Software-Analysis/blob/slides/slides/Interprocedural-Value-Flow-Graph.pdf

> 
> ```
> define dso_local i32 @main(i32 %argc, i8** %argv) #0 {
> entry:
>   %retval = alloca i32, align 4
>   %argc.addr = alloca i32, align 4
>   %argv.addr = alloca i8**, align 4
>   %a = alloca i8, align 1
>   %b = alloca i8, align 1
>   %x = alloca i8*, align 4
>   %z = alloca i8*, align 4
>   store i32 0, i32* %retval, align 4
>   store i32 %argc, i32* %argc.addr, align 4
>   store i8** %argv, i8*** %argv.addr, align 4
>   %0 = load %struct._IO_FILE*, %struct._IO_FILE** @stdin, align 4
>   %call = call i32 @fgetc(%struct._IO_FILE* %0)
>   %conv = trunc i32 %call to i8
>   store i8 %conv, i8* %a, align 1
>   store i8 84, i8* %b, align 1
>   store i8* %a, i8** %x, align 4
>   store i8* %b, i8** %x, align 4
>   %1 = load i8*, i8** %x, align 4
>   store i8* %1, i8** %z, align 4
>   ret i32 0
> }
> ```

**Comment by teozoia** [comment]
I was reading about demand-driven analysis and SUPA following the paper Demand-Driven Pointer Analysis with Strong Updates via Value-Flow Refinement, but how is it possible to implement DDA in my own analysis to get the traversal doing what I need to do?

I could not find any example of DDA used inside the analysis, so I've copy-paste some code from DDAPass:

```
PAGBuilder builder;
PAG* pag = builder.build(svfModule);

// Create pointer analysis
// Andersen* ander = AndersenWaveDiff::createAndersenWaveDiff(pag);
// FlowSensitive *fs = FlowSensitive::createFSWPA(pag);
DDAClient *client = new DDAClient(svfModule);
client->initialise(svfModule);
FlowDDA *dda = new FlowDDA(pag, client);

// initialize
dda->initialize();
// compute points-to
client->answerQueries(dda);
// finalize
dda->finalize();

// Call Graph
// PTACallGraph* callgraph = ander->getPTACallGraph();
// PTACallGraph* callgraph = fs->getPTACallGraph();
PTACallGraph* callgraph = dda->getPTACallGraph();

// ICFG
ICFG* icfg = pag->getICFG();

// Value-Flow Graph (VFG)
VFG* vfg = new VFG(callgraph);

// Sparse value-flow graph (SVFG)
SVFGBuilder svfBuilder;
// SVFG* svfg = svfBuilder.buildFullSVFG(fs);
// SVFG* svfg = svfBuilder.buildFullSVFG(ander);
SVFG* svfg = svfBuilder.buildFullSVFG(dda);

```

Then I call the `traverseOnVFG(svfg, %a = alloca i8, align 1)`. Is that the right way to use it inside my own analysis?

**Comment by esaurimentocronico** [comment]
@yuleisui  I am also interested in implementing demand-driven analysis in my own analysis as in the svf-ex example
