### ISSUE TITLE
Incorrect FSPTA  results?

### ISSUE THREAD

**Issue by atharvavk** [SVF-tools/SVF#621]
I am currently studying SFS. I have studied Flow-sensitive pointer analysis. Please forgive my silly mistakes.

I was trying to print FSPTA results for the following C++ file.
``` 
class A {
  public:
  int a;
  virtual void f() { }
};

class B : public A {
  public:
  virtual void f() { }
};

int main()
{
  int a = 3, b = 2;
  A* ptr;
  if (a > b) {
    ptr = new A();
    ptr->f();
  } else {
    ptr = new B();
    ptr->f();
  }
}
```

I have attached the corresponding .ll file for reference (changing format to txt )
[test.txt](https://github.com/SVF-tools/SVF/files/8038547/test.txt)

My issue is, in the else part of the code:
(line 79 and 80)
`  %vtable2 = load void (%class.A*)**, void (%class.A*)*** %11, align 8
  %vfn3 = getelementptr inbounds void (%class.A*)*, void (%class.A*)** %vtable2, i64 0` 
  points-to set of vtable2 contains Vtables of class A & class B i.e. $_ZTV1A and $_ZTV1B
  
  But (line 116):
  ` store i32 (...)** bitcast (i8** getelementptr inbounds ({ [3 x i8*] }, { [3 x i8*] }* @_ZTV1B, i32 0, inrange i32 0, i32 2) to i32 (...)**), i32 (...)*** %1, align 8
`
should cause a strong update. Hence, points to set of vtable2 should contain $_ZTV1B only. Please help.

**Comment by yuleisui** [comment]
Is that a heap strong update? Flow-sensitive analysis alone can not perform strong updates for heap and its fields.

**Comment by atharvavk** [comment]
Thanks for the answer. I failed to consider it as a Heap allocation.
