### ISSUE TITLE
transform from llvm IR to  SVFGNode

### ISSUE THREAD

**Issue by macromachine** [SVF-tools/SVF#63]
Hi, yulei,
Is there any way that we can transform llvm IR (Instruction) to SVFGNode?
I have found that:  “pag->getValueNode”, and “pag->getPAGNode“
we can obtain PAGNode from llvm IR.
But I don't know how to obtain SVFGNode.

Besides, the NodeID in PAG and SVFG is different?

thanks

**Comment by macromachine** [comment]
I have tried getDefSVFGNode, but I found some errors.
For example, the function call instruction CallInst, if the called function has no return (e.g., free), it will report error.

**Comment by yuleisui** [comment]
Yes, we will throw an assertion if an instruction (e.g., free callsite in your case) does not define or return any variable.

You can use the following function before knowing whether "getDefSVFGNode" is eligible
https://github.com/SVF-tools/SVF/blob/f6d9758675e6bb31e61e13c33503ab90242fcb25/include/MSSA/SVFG.h#L409

SVFGNode was designed for def-use analysis. In fact, there is no such mapping from a call instruction to an SVFGNode, especially in your case, you can't find an SVFGNode given a "free" instruction on SVFG. However, we will break down the call instruction to create SVFGNodes for all its parameters and return variables, e.g., for a callsite "foo (p, q)", we will create two SVFGNodes for "p" and "q" with their type called "ActualParmSVFGNode". For all other SVFGNode types you can refer the following code:

https://github.com/SVF-tools/SVF/blob/f6d9758675e6bb31e61e13c33503ab90242fcb25/include/MSSA/SVFGNode.h#L47

To improve the performance of analysis on top of SVFG,  an optimized SVFG is used as a default option (see https://github.com/SVF-tools/SVF/wiki/Technical-documentation#323-svfg-optimization). Therefore, you may see some redundant SVFGNode can be removed (e.g., actual parameters). Of course, you are also free to choose to use the unoptimized version to see all nodes with their def-use chains untouched.

**Comment by macromachine** [comment]
thanks
