### ISSUE TITLE
For the statement p = malloc(v), there is no def edge for v in SVFG

### ISSUE THREAD

**Issue by jmp0x7c00** [SVF-tools/SVF#631]
![image](https://user-images.githubusercontent.com/16433413/154027843-eddb3d08-c904-492f-b709-347b4cee4b00.png)
The definition node of %15 is not connected to the malloc statement, which is confusing

**Comment by jmp0x7c00** [comment]
There is also no def-use edge between `%index = ... `and `%arrayIndex = Gep %base, %index`

**Comment by jmp0x7c00** [comment]
Any help to this issue is helpful!

**Comment by yuleisui** [comment]
Sorry for the late reply. Yes, these two types of def-use have not been added to SVFG since SVFG was designed mainly for memory error detection and pointer analysis purposes. We will take a look at the issue in due course.

**Comment by jmp0x7c00** [comment]
so I have to implement this by myself , I Got it , thanks for your reply. ❤️

**Comment by yuleisui** [comment]
> so I have to implement this by myself , I Got it , thanks for your reply. ❤️

Yes, welcome to contribute or share your implementation with a pull request.
