### ISSUE TITLE
crashed when I use wpa to parse large IR file

### ISSUE THREAD

**Issue by jmp0x7c00** [SVF-tools/SVF#639]
```bash
SVFModuleLoader: talos.ll:8837:56: error: expected '('
  call void @create_pool(%struct.mempool* nonnull sret %1, i64 104, i32 250) #4, !dbg !87661
                                                       ^
wpa: /home/yang/SVF/include/SVF-FE/LLVMModule.h:200: SVF::LLVMContext& SVF::LLVMModuleSet::getContext() const: Assertion `!empty() && "empty LLVM module!!"' failed.
已放弃 (核心已转储)
```

**Comment by jmp0x7c00** [comment]
[talos.zip](https://github.com/SVF-tools/SVF/files/8159043/talos.zip)

**Comment by yuleisui** [comment]
Could you also report the stack and a bit more information?

**Comment by jmp0x7c00** [comment]
libc.so.6!__GI_raise(int sig) (\build\glibc-eX1tMB\glibc-2.31\sysdeps\unix\sysv\linux\raise.c:50)
libc.so.6!__GI_abort() (\build\glibc-eX1tMB\glibc-2.31\stdlib\abort.c:79)
libc.so.6!__assert_fail_base(const char * fmt, const char * assertion, const char * file, unsigned int line, const char * function) (\build\glibc-eX1tMB\glibc-2.31\assert\assert.c:92)
libc.so.6!__GI___assert_fail(const char * assertion, const char * file, unsigned int line, const char * function) (\build\glibc-eX1tMB\glibc-2.31\assert\assert.c:101)
SVF::LLVMModuleSet::getContext(const SVF::LLVMModuleSet * const this) (\home\yang\SVF\include\SVF-FE\LLVMModule.h:200)
SVF::SVFIRBuilder::addNullPtrNode(SVF::SVFIRBuilder * const this) (\home\yang\SVF\include\SVF-FE\SVFIRBuilder.h:263)
SVF::SVFIRBuilder::initialiseNodes(SVF::SVFIRBuilder * const this) (\home\yang\SVF\lib\SVF-FE\SVFIRBuilder.cpp:137)
SVF::SVFIRBuilder::build(SVF::SVFIRBuilder * const this, SVF::SVFModule * svfModule) (\home\yang\SVF\lib\SVF-FE\SVFIRBuilder.cpp:64)
ELA::ELA(ELA * this, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > & mnv, std::string configFile) (\home\yang\ELA\src\main.cpp:32)
test() (\home\yang\ELA\src\main.cpp:356)
main(int argc, char ** argv) (\home\yang\ELA\src\main.cpp:429)

**Comment by yuleisui** [comment]
The bc file seems broken: This is when parsing the LLVM IR using LLVM's `parseIRFile` method.

```
SVFModuleLoader: talos.ll:8837:56: error: expected '('
  call void @create_pool(%struct.mempool* nonnull sret %1, i64 104, i32 250) #4, !dbg !8766
```

**Comment by jmp0x7c00** [comment]
It may be because of  `sret` in `call void @create_pool(%struct.mempool* nonnull sret %1, i64 104, i32 250) #4, !dbg !87661`
After I delete the definition and call of `create_pool`, there is no problem

**Comment by jmp0x7c00** [comment]
My fault，it's due to my IR is generated by clang 8 but I use svf with clang13
