### ISSUE TITLE
Completeness of SVF Points-to analysis?

### ISSUE THREAD

**Issue by Arslan8** [SVF-tools/SVF#644]
Hi,

I have a question about the completeness of SVF Points-To analysis in case I don't have any dynamic allocation in a program: would the points to analysis results from SVF field-sensitive and context-sensitive points-to analysis will be complete, i.e. would it result in zero false negatives. In other words, would it be able to get all pointers aliased?

Thanks,
Arslan

**Comment by Arslan8** [comment]
Also related question: If I remove all the indirect calls from a program, does this achieve completeness using SVF?

I am basically looking for the subset of programs in which SVF points-to analysis is complete..

**Comment by yuleisui** [comment]
The soundness is based on SVFIR and SVF's MemoryModel, but not the LLVM IR since some llvm instructions may not be handled in points-to analysis (https://github.com/svf-tools/SVF/wiki/Technical-documentation#123-svfirbuilder-or-pagbuilder)

**Comment by Arslan8** [comment]
Thanks for the prompt response! Does that mean if I restrict my program to these instructions the alias analysis will be sound?

**Comment by yuleisui** [comment]
Yes

**Comment by Arslan8** [comment]
Perfect! Thank you so much!!
