### ISSUE TITLE
Pointer analysis query!

### ISSUE THREAD

**Issue by Machiry** [SVF-tools/SVF#65]
Is there any way to get all the pointers that are aliases to a given pointer or object (ex: alloca).

The way I can think of is..get all the pointers in the IR, do `getPts` and compute the intersection.

Is there any other easier or recommended way?

**Comment by yuleisui** [comment]
Two ways for your query:

1) Iterate all other pointers and use "alias" interface.
```
        for (NodeBS::iterator nIter = pta->getAllValidPtrs().begin(); nIter != pta->getAllValidPtrs().end(); ++nIter) {
            pta->alias(*nIter, your_pointer);
        }
```

2) Retrieving reverse points-to "getRevPts" of an object that your pointer points to
```
        PointsTo& objs = getPts(your_pointer);
        PointsTo aliases;
        for (NodeBS::iterator nIter = objs.begin(); nIter != objs.end(); ++nIter) {
             aliases |= getRevPts(*niter);
        }
```

**Comment by yuleisui** [comment]
A PAGNode represents a pointer or an object which refers to an LLVM value. A NodeID on a PAG denotes a uniquely identified PAGNode. See https://github.com/SVF-tools/SVF/wiki/Technical-documentation#121-pagnode.

For a store instruction e.g., *p = q, there are two pointers at this instruction, the pointer operand "p" and the value operand "q". To get the NodeID of "p", you can use `pag-> getValueNode(storeInst->getPointerOperand())`

**Comment by Machiry** [comment]
Perfect. Thank You. This is a great project!!
