### ISSUE TITLE
SVF::Andersen::mergeNodeToRep: invalid read

### ISSUE THREAD

**Issue by 251** [SVF-tools/SVF#659]
`mergeNodeToRep()` gets a `node` pointer from `consCG` via `nodeId`:
https://github.com/SVF-tools/SVF/blob/e582c56522c1115a3b8fb01b58c98d0a6b697197/lib/WPA/Andersen.cpp#L803

The subsequent call to `mergeSrcToTgt` seems to do the same but removes `node` via `removeConstraintNode(node)`:
https://github.com/SVF-tools/SVF/blob/e582c56522c1115a3b8fb01b58c98d0a6b697197/lib/WPA/Andersen.cpp#L779

`mergeNodeToRep()` than dereferences node in the `if` statement and accesses invalid memory.

**Comment by yuleisui** [comment]
That is a good catch! Thanks and the condition check `node->isPWCNode()` should be made as a flag (or `gepInsideScc`) before passing back from `mergeSrcToTgt `.

**Comment by yuleisui** [comment]
Just fixed https://github.com/SVF-tools/SVF/commit/10ea3d147fb9afa4b44da3c56784ec6d9ef3ecf1

**Comment by 251** [comment]
Thanks!
