### ISSUE TITLE
Annoying clean.sh

### ISSUE THREAD

**Issue by AminoACID123** [SVF-tools/SVF#666]
Running `build.sh` will install LLVM inside SVF's root directory. However, after running `clean.sh`, some files in the LLVM directory also got removed, such as `include/llvm/Support/Debug.h`. This is clearly not what we want.
Hope someone can fix this.

**Comment by yuleisui** [comment]
Just fixed https://github.com/SVF-tools/SVF/commit/e782295b25249911fe73cec399e2b8a3d0995900

**Comment by AminoACID123** [comment]
Thanks!
