### ISSUE TITLE
call graph and icfg not complete version2.4

### ISSUE THREAD

**Issue by Frankenstein-bit** [SVF-tools/SVF#672]
here is the C code 
#include<stdio.h>
 
   char** readBuf() {
        char** mBuf = malloc(20); //o
         *mBuf = malloc(20); //o1
         *(*mBuf) = 'A';
         return mBuf;
  }
  void freeBuf1(char** fBuf){
         char* z =*fBuf;
         free(z);
         free(fBuf);
  }
  void main(){
        for(int n=0;n<100;n++){
               char** buf = readbuf();
	char* tmp = *buf;
	if(*tmp != '\n')
	          printf("%s",*tmp);
	else
	          continue;
	freeBuf1(buf);
        }
  }

here are callgraph
![image](https://user-images.githubusercontent.com/59007647/161267019-926b6efb-0cc1-4987-9bd8-0140717fe57b.png)

**Comment by yuleisui** [comment]
Can you also put the bc code and your command line to dump the graph?

**Comment by yuleisui** [comment]
I believe ‘readbuf’ and ‘readBuf’ are two different methods

**Comment by Frankenstein-bit** [comment]
> I believe ‘readbuf’ and ‘readBuf’ are two different methods

yes,thank you
