### ISSUE TITLE
class `FunExitBlockNode` member `fun` shadows its base class `ICFGNode` member `fun`

### ISSUE THREAD

**Issue by comphsics** [SVF-tools/SVF#679]
The class `FunExitBlockNode` laid in directory `Graphs/ICFGNode.h`
has a memeber:``const SVFFunction* fun``
```c++
class FunExitBlockNode : public InterBlockNode
{

private:
    const SVFFunction* fun;
    const PAGNode *formalRet;
public:
    FunExitBlockNode(NodeID id, const SVFFunction* f);
```
However,its base class `ICFGNode` has also a member:`const SVFFunction* fun`
```c++
class ICFGNode : public GenericICFGNodeTy
{
...
...
protected:
    const SVFFunction* fun;
    const BasicBlock* bb;
    VFGNodeList VFGNodes; //< a list of VFGNodes
    PAGEdgeList pagEdges; //< a list of PAGEdges

```
Therefore, the latter will shadows the former,
So when I print these two fields and I see the former will always be null
if the node is a `FunExitBlockNode`.
Is the former has a special usage?
#### Class hierarchy
```c++
class FunExitBlockNode:public InterBlockNode{......};
class InterBlockNode:public ICFGNode{......};
```

**Comment by yuleisui** [comment]
No special usage. That is a good catch! Just fixed https://github.com/SVF-tools/SVF/commit/7dfa08869cc1e871d0d1d6aab67af392658246b5.
