### ISSUE TITLE
 algorithm for data race detection

### ISSUE THREAD

**Issue by mengjianwei12345** [SVF-tools/SVF#681]
Hello, I'm working on a SVF based data race detection tool recently，so I would like to ask what the data_race detection algorithm in MTA is like

**Comment by yuleisui** [comment]
In MTA, A pair of memory accesses (l1: *p, l2: *q) is a data race pair if (1) at least one is store operation, (2) alias(p,q) = MAYALIAS, and (3) MHP(l1, l2) is true 

For (3), refer to https://yuleisui.github.io/publications/cgo16.pdf

**Comment by mengjianwei12345** [comment]
Thank you very much for your quick reply, I will go back and study this article

**Comment by mengjianwei12345** [comment]
Thanks again, I have another question, for(2), I don't know where I got this alias, because svf itself has alias analysis, whether it comes from this alias analysis or from value flow

**Comment by yuleisui** [comment]
Any type of analysis inherited from [PointerAnalysis](https://github.com/SVF-tools/SVF/blob/master/include/MemoryModel/PointerAnalysis.h#L65-L91) with [alias interface](https://github.com/SVF-tools/SVF/blob/master/include/MemoryModel/PointerAnalysis.h#L243-L247)

**Comment by mengjianwei12345** [comment]
Thanks again for the tip！

**Comment by mengjianwei12345** [comment]
Hello, may I ask if there is an algorithm for detecting shared variables in MTA?

**Comment by yuleisui** [comment]
Shared variable by threads? If so, you can use MHP + alias.

**Comment by mengjianwei12345** [comment]
Ok, thank you so much for the guide, I'll try it!
