### ISSUE TITLE
Inconsistencies in Points to information

### ISSUE THREAD

**Issue by Machiry** [SVF-tools/SVF#69]
I am trying to get points to information of a dynamically created object.

Source code:

```
void indirect_allocator(char **ptr, int s) {
    if(*ptr == NULL) {
        *ptr = malloc(s);
    }
}
int main() {
    int h;
    static char *global_ptr;
    scanf("%d", &h);
    if(h < 4) {
        indirect_allocator(&global_ptr, h*3);
    } else {
        indirect_allocator(&global_ptr, h*5);
    }
    
    global_ptr[0] = 'f';
    global_ptr[1] = 'q';
    global_ptr[2] = 'a' + h;
    global_ptr[3] = '\0';
    printf("%s", global_ptr);
} 
```
Here the goal is to identify that `global_ptr[*]` instructions in the `main` function are aliases to the object allocated by the `malloc` call of `indirect_allocator` function.

I am using the following code:
```
PointerAnalysis* currPta = new AndersenWaveDiffWithType();
currPta->analyze(svfModule);
// get the PAG
PAG *currentPAG = currPta->getPAG();
// Get the top-level variable
GlobalVariable *targetGlobVar = targetModule->getGlobalVariable("main.global_ptr", true);

// get points_to
NodeID targetNode = currentPAG->getValueNode(targetGlobVar);
PointsTo& objs = currPta->getPts(targetNode);
// here objs contains only one node, which is right i.e., @main.global_ptr = internal global i8* null, align 8

// Now, let's get objects pointed by this node.
PointsTo& objs2 = currPta->getPts(objs.find_first());
// here objs2 contains only one node, which is correct i.e., %call = call i8* @malloc(i64 %conv)

// Now, when I try to get all aliases to the malloced object i.e., (the above %call..)
std::set<NodeID> targetAliases;
targetAliases.clear();
for (NodeBS::iterator nIter = currPta->getAllValidPtrs().begin();
                nIter != currPta->getAllValidPtrs().end();
                ++nIter) {
            if(currPta->alias(*nIter, objs2.find_first()) != NoAlias) {
                if(targetAliases.find(*nIter) == targetAliases.end()) {
                    targetAliases.insert(*nIter);
                }
            }
        }

// I get NO aliases..
```

I expect to see the `load` and `getelementptr` instructions of the main function..but I do not see anything.

Am I missing something here?

Attached is the source file `global_ptr_head_obj.c` and the corresponding bitcode file (`global_ptr_head_obj.mem2reg.bc`) on which I am trying to run the analysis.

[global_ptr_example.zip](https://github.com/SVF-tools/SVF/files/2154145/global_ptr_example.zip)

**Comment by yuleisui** [comment]
Machiry,

It is good that you have read the code in a good depth. 

Almost all of your code snippets are correct except the alias part.

In pointer analysis, aliases usually refer to two deferences or two pointers.  In your "currPta->alias(xx,yy)", xx and yy are suppose to be two pointers instead of objects. The object "%call = call i8* @malloc(i64 %conv)" is not aliased with any other nodes/variables. On the contrary, there are multiple pointers in your code are aliased with each other since they point to this object.

You will get what you want if you use pointers as parameters for your alias query.

**Comment by Machiry** [comment]
Thank You @yuleisui 
Is there any way to get all the pointers whose points_to set contains a particular memory object. (of course, Other than iterating through the points to of all the pointers)?

**Comment by Machiry** [comment]
Another general doubt: 

Let's say If I want to find all instructions that can access a memory object (say `obj`)

My idea is to first find the top-level node (say `topNode`)  that points to the `obj` and then find all aliases (say `totalAliases`)  to `topNode`.  This should give me all instructions (along with other values) that can point to `obj`. 
Am I right?

Now, in the `totalAliases`, I can safely ignore all address taken nodes right? Reason: Since, all address taken nodes should be accessed by memory instructions i.e., `load`,  `store`  or `getelementptr` etc.
Any instruction that accesses the corresponding address taken node. It will anyway be present in the aliases, i.e., `totalAliases` set because it will appear as a top-level node accessing `obj.`  Am i right?

**Comment by Machiry** [comment]
@yuleisui, Question 3: Does `getAllValidPtrs` return only Top-Level pointers or all Nodes (including Address taken) that have points to?

**Comment by yuleisui** [comment]
Yes, a pointer or object either has at least one incoming or outgoing edge. Please see the implementation of `getAllValidPtrs` :
https://github.com/SVF-tools/SVF/blob/f6d9758675e6bb31e61e13c33503ab90242fcb25/lib/MemoryModel/PAG.cpp#L542

**Comment by yuleisui** [comment]
See this thread to get all pointers point to an object via `getRevPts`

https://github.com/SVF-tools/SVF/issues/65

BTW: what you said about `totalAliases` seems correct to me.
