### ISSUE TITLE
Can we use SVF for implicit taint analysis?

### ISSUE THREAD

**Issue by NICE994** [SVF-tools/SVF#706]
Hi, sir
SVF does a lot of work on both Control-flow and Value-flow analysis, which is brilliant.
Now, I want to use it for taint analysis, but I run into some problems:
1. Can SVF report implicit taint propagation?
for example:
```
void foo(){
  String X = source();
  String Y = new String();
  for (int i = 0; i < X.length(); i++){
    int x = (int)X.chatAt(i);
    int y = 0;
    for (int j = 0; j < x; j++){
      y = y + 1;
    }
    Y = Y + (char)y;
  }
  sink(Y);
}
```
Variable Y is tainted by variable X implicitly, as X.length be used as a constraint at line 4.
For now, using cmd
`wpa -ander -svfg --dump-vfg -opt-svfg=false swap.ll`
Variable Y is not tainted by Variable X.
Are there any other options that can be added  to combine Control-flow and Value-flow and complete implicit taint analysis?

2. In SVFG, with option '-opt-svfg=false', wap suppose to remove some nodes like FormalRet and FormalOut.
But the output graphs with cmd:
`wpa -ander -svfg -dump-vfg swap.ll` and `wpa -ander -svfg --dump-vfg -opt-svfg=false swap.ll`
are the same.
Is there something I'm missing?

Thank you for great tools and it will be very helpful if you give me comments.

**Comment by yuleisui** [comment]
Unfortunately not supported by SVF. However, it can be implemented if you know the bounds of the loop using llvm scalar evolution for example.

**Comment by NICE994** [comment]
Ok, thank you so much for the guide, I'll try it.
