### ISSUE TITLE
Assertion Error: `fields.size() >= 4 && "_Rb_t least 4 fields.\n"' failed.

### ISSUE THREAD

**Issue by NICE994** [SVF-tools/SVF#715]
Hi, sir:
I try to use SVF for large program analysis.

But while analyzing 'Exiv2', I encountered this assertion failure.
`wpa: /home/SVF/lib/SVF-FE/SVFIRBuilder.cpp:1353: virtual void SVF::SVFIRBuilder::handleExtCall(SVF::CallSite, const SVF::SVFFunction*): Assertion 'fields.size() >= 4 && "_Rb_t least 4 fields.\n"' failed.`

The command line is:
`wpa -ander -svfg --dump-vfg -opt-svfg=false bin/exiv2.bc`

The Exiv2 compile command line is:
```
git checkout b9f9d041e
mkdir -p build
cd build
cmake ..
make clean;make -j $(nproc)
```

I used `gclang` & `gclang++` to compile exiv2, and `get-bc` to get the exiv2.bc.
[exiv2.zip](https://github.com/SVF-tools/SVF/files/8791293/exiv2.zip)

I know this might be a tricky question, but I sincerely hope you can give me some advice.

**Comment by yuleisui** [comment]
Thanks for reporting. This is due to an incorrect assertion for `_Rb_tree_insert_and_rebalance` in C++ lib. 
Just fixed. https://github.com/SVF-tools/SVF/commit/a270d58f6a54ff4049543c7c4db57a8306ff771f

**Comment by NICE994** [comment]
Hi, sir:
In another program, I encountered this assertion failure:
`wpa: /home/SVF/include/MemoryModel/SVFIR.h:453: void SVF::SVFIR::addToStmt2TypeMap(SVF::SVFStmt*): Assertion 'added && "duplicated edge, not added!!!"' failed.
Aborted`

The command line is:
`wpa -ander -svfg --dump-vfg -opt-svfg=false xmllint.bc`

I used gclang & gclang++ to compile exiv2, and get-bc to get the xmllint.bc.
[xmllint.zip](https://github.com/SVF-tools/SVF/files/8935021/xmllint.zip)

**Comment by yuleisui** [comment]
Thanks and fixed https://github.com/SVF-tools/SVF/commit/5b396999765e66ed4a335f0f2c61e77c79d3c656

**Comment by yuleisui** [comment]
It works ok on my side and try the latest version of SVF

**Comment by yuleisui** [comment]
I see. The assertion fails due to llvm's opaque struct type. Just fixed https://github.com/SVF-tools/SVF/commit/dc88e782337976f44c3ecb2cac45006995c2cdc3

**Comment by NICE994** [comment]
Hi, sir:
With the latest version of SVF, I encountered this assertion failure:
`wpa: /home/SVF/lib/MemoryModel/SymbolTableInfo.cpp:417: const SVF::Type *SVF::SymbolTableInfo::getFlatternedElemType(const SVF::Type *, SVF::u32_t): Assertion 'flatten_idx < so.size() && !so.empty() && "element index out of bounds or struct opaque type, can't get element type!"' failed.
Aborted`

The command line is:
wpa -ander -svfg --dump-vfg -opt-svfg=false xmllint.bc

I used gclang & gclang++ to compile exiv2, and get-bc to get the xmllint.bc.
[xmllint.zip](https://github.com/SVF-tools/SVF/files/9218018/xmllint.zip)

I have tried https://github.com/SVF-tools/SVF/commit/5b396999765e66ed4a335f0f2c61e77c79d3c656 but still failed.

**Comment by yuleisui** [comment]
Thanks for reporting. This https://github.com/SVF-tools/SVF/commit/b97270664063108e78b2466ebbc9ad53d64483e5 should fix the issue.

**Comment by NICE994** [comment]
Hi, sir:
With the latest version of SVF, I encountered this assertion failure:
`cbi: /home/SVF/include/MemoryModel/SymbolTableInfo.h:241: SVF::SymID SVF::SymbolTableInfo::getObjSym(const Value*) const: Assertion 'iter!=objSymMap.end() && "obj sym not found"' failed.`

I use SVF as a lib. In test.c I try to build ICFG and SVFG of xmllint.bc.

[test.c](https://github.com/NICE994/test/blob/main/test.c) [xmllint.bc](https://github.com/NICE994/test/blob/main/xmllint.bc)
