### ISSUE TITLE
Tainted analysis of std::string using PAG

### ISSUE THREAD

**Issue by tandf** [SVF-tools/SVF#716]
Hello,

I'm trying to use PAG to do backward tainted analysis on a variable of type std::string. I follow the instructions in #13 and use `-model-consts=true` to model string functions. It works well in most cases, but there are some cases it's not working. Here are some examples:

```cpp
void sinkfunc(std::string sink_str)
{
    std::string sink k= sink_str;
}

int main()
{
    // Example 1. This one works
    sinkfunc("secret 1");

    // Example 2. This one doesn't work
    const char secret[] = "secret 2";
    std::string secretStr(secret);
    sinkfunc(secretStr);
}
```
For example 1, I can search the PAG from the argument of `sinkfunc` to the string constant.
But for example 2, I can only reach the node `%secret = alloca [14 x i8], align` but not `@__const.main.secret = private unnamed_addr constant [14 x i8] c"source string\00", align 1 { Glob }`.

I dumped the PAG for example 2:

<img width="1274" alt="svfir" src="https://user-images.githubusercontent.com/25607777/171342974-e673bfa2-b1d2-4f92-8d23-755230b76f63.png">

Part of the .ll file is listed below, which corresponds to the highlighted part in the figure. 
```llvm
%0 = bitcast [9 x i8]* %secret to i8*
call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 1 %0, i8* align 1 getelementptr inbounds ([9 x i8], [9 x i8]* @__const.main.secret, i32 0, i32 0), i64 9, i1 false)
```

It seems `%secret` cannot be connected to `@const.main.secret` because of the `bitcast` instruction breaks the graph.

Could you tell me what I should do to fix this? Thank you!

**Comment by yuleisui** [comment]
The PAG graph looks ok to me. The memcpy method in fact allows value passing from `@const.main.secret` to `%0 = bitcast xxx` through a gep, to a load then to a store, finally a reverse gep, also highlighted in your red box.

Regarding the constant, `@const.main.secret` should points to a unique constant. You can also enable `-model-arrays=true` to have a try.

**Comment by tandf** [comment]
I look into the `memcpy` and the `bitcast` part, and now I understand what's happening. Previously, I was expecting that I can do the analysis by tracking `%agg.tmp` in the graph all the way to `@__const.main.secret` by following the in-edges, but I could only get `%secret`. Now I realize I only need to deal with the copy edge and the reverse edge to achieve my goal. Thank you for developing SVF, it's really helpful.
