### ISSUE TITLE
Question about InDirectSVFGEdge::mrs

### ISSUE THREAD

**Issue by comphsics** [SVF-tools/SVF#721]
Hello, I found a member `mrs` in class `InDirectSVFGEdge`:
```c++
class IndirectSVFGEdge:public VFGEdge{
  typedef Set<const MRVer*> MRVerSet;
  MRVerSet mrs;
  inline MRVerSet& getMRVer()
  {
      return mrs;
  }
  inline bool addMrVer(const MRVer* mr)
  {
      // collect memory regions' pts to edge;
      cpts |= mr->getMR()->getPointsTo();
      return mrs.insert(mr).second;
  }
};
```
the member `mrs` has a getter method `getMRVer` and a setter method `addMrVer`,
only these two methods can access this field, however these methods are never called
in SVF neither in outside functions nor in the initialization of `IndirectSVFGEdge`, therefore this field `mrs` would never be set.
So what is the field `mrs` usage?

**Comment by yuleisui** [comment]
That is a good catch! Just fixed https://github.com/SVF-tools/SVF/commit/249d819598ee5cc2226c73177e13a342bfa97198
