### ISSUE TITLE
Question about PTACallGraph

### ISSUE THREAD

**Issue by comphsics** [SVF-tools/SVF#722]
In PTACallgraphEdge,
```c++
/*
 * Call Graph edge representing a calling relation between two functions
 * Multiple calls from function A to B are merged into one call edge
 * Each call edge has a set of direct callsites and a set of indirect callsites
 */
class PTACallGraphEdge:...
```
The comment says multiple calls are merged into one call edge, however, when I printed
the call graph of the following code:
```c++
void a();
void b();

int main(){
    a();
    b();
    a();
}
```
And I got :
![cg](https://user-images.githubusercontent.com/48786665/172922078-8cdb9f64-7553-4e5a-865d-0767a63df66b.png)
 So there exits multi-edges in one pair of nodes.

If SVF allows multi-edges in PTACallGraph, then the field
```c++
class PTACallGraphEdge : public GenericCallGraphEdgeTy
{

public:
    typedef Set<const CallBlockNode*> CallInstSet;
    enum CEDGEK
    {
        CallRetEdge,TDForkEdge,TDJoinEdge,HareParForEdge
    };


private:
    CallInstSet directCalls;
    CallInstSet indirectCalls;
    CallSiteID csId;

```
`directCalls` and `indirectCalls` shall not be a `set`.

**Comment by comphsics** [comment]
![cg](https://user-images.githubusercontent.com/48786665/172923340-b2263f21-e2d9-429d-9375-18f2a60401d4.png)

**Comment by yuleisui** [comment]
directCalls and indirectCalls are sets and one edge per calling relation (the comments were made a few years ago and could be based on the previous implementation.

**Comment by yuleisui** [comment]
A better refactoring could remove the two sets (`directCalls` and `indirectCalls `), and maintain only a single callsite (`const CallICFGNode*`) as the field of `PTACallGraphEdge`. Would you like to help with this refactoring?
