### ISSUE TITLE
Point-to results inconsistencies

### ISSUE THREAD

**Issue by Machiry** [SVF-tools/SVF#76]
I have following points to information at the following load instruction:
```
%7 = load i8*, i8** @auth_check2.authpath, align 8, !dbg !1478, !tbaa !1470
##<> Source Loc: ln: 1047 fl: libhttpd.c
Ptr 12954         PointsTo: { 11314 11334 }

!!Target NodeID 11314     [<call> Source Loc: ln: 716 fl: libhttpd.c] 
!!Target NodeID 11334     [<call19> Source Loc: ln: 724 fl: libhttpd.c] 
```
This implies that, `@auth_check2.authpath` is a top level pointer that points to some objects which in turn should **atleast** point to the nodes `11314` and  `11334` am I right?

So, I checked the points to of the pointer operand, I get the following:
```
##<auth_check2.authpath> Source Loc: Glob 
Ptr 1474         PointsTo: { 1475 }

!!Target NodeID 1475     [<auth_check2.authpath> Source Loc: Glob ] 
```
Ok, this is the first level object, seems to be valid.

Now, when I check the points to objects of the node `1475`, I get:

```
##<auth_check2.authpath> Source Loc: Glob 
Ptr 1475         PointsTo: {empty}
```
I expect to see `11314` and  `11334`. 

How is this possible that the points to are empty whereas the `load` instruction points to is not? I am baffled.

**Comment by Machiry** [comment]
Just to add, This only happens using `FlowSensitive` pointer analysis.

Using anderson analysis (`AndersenWave_WPA`), The results are fine.
```
%3 = load i8*, i8** @auth_check2.authpath, align 8, !dbg !1469, !tbaa !1470
##<> Source Loc: ln: 1044 fl: libhttpd.c
Ptr 12949         PointsTo: { 11314 11334 }

!!Target NodeID 11314     [<call> Source Loc: ln: 716 fl: libhttpd.c] 
!!Target NodeID 11334     [<call19> Source Loc: ln: 724 fl: libhttpd.c] 
```
Pointer operand:
```
##<auth_check2.authpath> Source Loc: Glob 
Ptr 1474         PointsTo: { 1475 }

!!Target NodeID 1475     [<auth_check2.authpath> Source Loc: Glob ] 
```
The second level points to information:
```
##<auth_check2.authpath> Source Loc: Glob 
Ptr 1475         PointsTo: { 11314 11334 }

!!Target NodeID 11314     [<call> Source Loc: ln: 716 fl: libhttpd.c] 
!!Target NodeID 11334     [<call19> Source Loc: ln: 724 fl: libhttpd.c] 
```

This is valid and what I would expect to see with the FlowSensitive Pointer analysis too.

**Comment by yuleisui** [comment]
If the results of Andersen's analysis are correct, I guess there might be two possibilities

1) For standard flow-sensitive analysis, all global variables are initialized at the entry of main function:
https://github.com/SVF-tools/SVF/blob/3038078e90eb037ea43aa28ff3a28c05d631be5d/lib/MSSA/SVFG.cpp#L438
`11314 11334` may not be stored properly into global object `auth_check2.authpath` at the entry of the main function.

2) overlooking of external calls (functions do not have definitions) missing the side-effects of those functions in our function summary (https://github.com/SVF-tools/SVF/blob/master/lib/Util/ExtAPI.cpp) may lead to missed points-to target. See https://github.com/SVF-tools/SVF/blob/b7ddf981ae1e3be79eab691f6cf844313ee66b77/lib/MSSA/SVFG.cpp#L161

I guess the first case might be the reason. Could you take a look?

**Comment by Machiry** [comment]
This is not a global store. The `store` happens in a function.

The part I am unable to understand is:

The load instruction has the following points-to information:

```
%7 = load i8*, i8** @auth_check2.authpath, align 8, !dbg !1478, !tbaa !1470
##<> Source Loc: ln: 1047 fl: libhttpd.c
Ptr 12954         PointsTo: { 11314 11334 }

!!Target NodeID 11314     [<call> Source Loc: ln: 716 fl: libhttpd.c] 
!!Target NodeID 11334     [<call19> Source Loc: ln: 724 fl: libhttpd.c] 
```

**Assumption 1**: This means, `@auth_check2.authpath` (i.e., the `ptrOperand`) should point to some object(s), which in turn should point to `11314` and `11334`. Am I right?

So, the points-to set of `@auth_check2.authpath` contains only `1475`:
```
##<auth_check2.authpath> Source Loc: Glob 
Ptr 1474         PointsTo: { 1475 }

!!Target NodeID 1475     [<auth_check2.authpath> Source Loc: Glob ] 
```

**Conclusion 1**: Now, the `1475` should point to `11314` and `11334`. Am I right? (According to Assumption 1).

When I check the points-to information of `1475` I get **empty set**:

```
##<auth_check2.authpath> Source Loc: Glob 
Ptr 1475         PointsTo: {empty}
```
If Assumption 1 is valid, How can this be ever possible?

**Comment by Machiry** [comment]
I think I might have found the issue, before explaining, I want to ask a simpler question: How to get the points-to results of `FlowSensitive` analysis?

The problem I am facing is:

I am using PAG to get the points-to results of `FlowSensitive` analysis. This may be fine for Top-Level pointers, but to get the points-to results of memory objects this will not work.

Because `FlowSensitive` analysis is updating the points-to results in the `SVFG` node.

In `processStore`:

`unionPtsFromTop(store, store->getPAGSrcNodeID(), ptd)` -> `getDFPTDataTy()->updateATVPts(srcVar,stmt->getId(),dstVar)` -> `this->unionPts(this->getDFOutPtsSet(dstLoc, dstVar), this->getPts(srcVar))`

It is getting the points-to results from PAG but updating the results into the corresponding memory region, which will not be updated in the points-to results of the corresponding PAG node.

So, if we are using `FlowSensitive` analysis, then the standard method of `getPts` (of `PAG`) will not work for non-top level nodes.

**Comment by yuleisui** [comment]
Machiry,

You are perfectly correct!

For top level pointers, you can still query their points-to values via `getPts()` since they are defined uniquely (only once) in LLVM IR.

Address-taken objects can be defined multiple times indirectly via dereferences, so flow-sensitive analysis distinguishes points-to values at different program points. Querying `getPts` does not make sense in this setting.

Please use the following to query the points-to values of an object at a particular program point (before or after an SVFG node).

https://github.com/SVF-tools/SVF/blob/3038078e90eb037ea43aa28ff3a28c05d631be5d/include/WPA/FlowSensitive.h#L219

https://github.com/SVF-tools/SVF/blob/3038078e90eb037ea43aa28ff3a28c05d631be5d/include/WPA/FlowSensitive.h#L222

We should make this clear in the interface or documentation/wiki about this. I almost didn't realize it until after you pointed out.

Thanks,

**Comment by Machiry** [comment]
So, If I am using `FlowSensitive` analysis and I want to get the final points-to set of a memory object (`objid`).
  
Ideally, I should be using `getDFOutPtsSet` of the memory object i.e., `objid` by using the last statement in the `main` function.  right?

**Comment by yuleisui** [comment]
It depends on where you want to query the points-to value of an object. It can be queried at a particular program point and may not at the end of a program.

In SVF, objects are abstract, LLVM IR only has value nodes (i.e., pointers or registers). A client (e.g., aliases and callgraph) normally uses the values of a pointer by loading the value from their interested object.
