### ISSUE TITLE
Analyzing global variable

### ISSUE THREAD

**Issue by tandf** [SVF-tools/SVF#760]
Hi,

I'm analyzing this program using VFG
```c++
#include <string>

void sinkfunc(std::string sink_str)
{
    std::string sink = sink_str;
}

const std::string str = "foobar";

int main()
{
    sinkfunc(str);
    return 0;
}
```
The `str` global variable part in the VFG graph is quite different from its local variable counterpart below. 

```c++
#include <string>

void sinkfunc(std::string sink_str)
{
    std::string sink = sink_str;
}

int main()
{
    const std::string str = "foobar";
    sinkfunc(str);
    return 0;
}

```

Here are the graphs for the two programs: [svfg.zip](https://github.com/SVF-tools/SVF/files/9088343/svfg.zip)
I think in the global variable version, there is a missing link from *StoreVFGNode ID: 74* to *LoadVFGNode ID: 57*, which corresponds to the edge from *StoreVFGNode ID: 59* to *LoadVFGNode ID: 47* in the local variable version.

Here is my guess of the reason: In the global variable version, the store node ID 74 has in node *FormalINSVFGNode ID 112* with CHI(MR_2V_1), and the load node ID 57 has in node *FormalINSVFGNode ID 109* with CHI(MR_2V_1). The two *FormalINSVFGNode* should be used to connect the load and the store node, but somehow they are not connected.

Could you tell me if VFG is behaving correctly, and if not, how can I fix it? Thanks a lot.

**Comment by yuleisui** [comment]
Can you send us your bcs and indicate you commend liine options?

**Comment by tandf** [comment]
Here are the bcs: [bc.zip](https://github.com/SVF-tools/SVF/files/9088432/bc.zip)
The command line options are `-stat=false -model-consts=true -model-arrays=true --dwarn=false --dump-vfg`

**Comment by yuleisui** [comment]
From my understanding, the global value-flows should be connected. It is a bit messy to examine for this one. Would you be able to try a C code in the same pattern first?

**Comment by yuleisui** [comment]
[svfg_final.dot.zip](https://github.com/SVF-tools/SVF/files/9088729/svfg_final.dot.zip)
In case, I have uploaded the svfg dumpped on my local machine for your comparison.

**Comment by yuleisui** [comment]
It works fine for C which has the same pattern.  LoadVFGNode ID 26 is connected from FormalINSVFGNode from the StoreVFGNode ID 35. Will have to take a look at whether it is because of some string APIs in C++
[C-ex.zip](https://github.com/SVF-tools/SVF/files/9089997/C-ex.zip)
.

**Comment by tandf** [comment]
Thanks for the reply. I also tried on C code and it behaves normally. I also agree that this problem might originate from string APIs in C++.
I tried to debug the C++ string APIs, but I was previously building my code upon an early branch (a13a0ca), so I merged the new commits to see if this helps. However I found that with new commits on the string APIs (from commit e20fe860), my previous working code misbehaves. I need to debug that first, and then I'll come back to this issue.

**Comment by tandf** [comment]
I found #738 leads to my problems. I analysis the program below using commit 5b396999 (the commit right before #738) and commit 2e2fed50 (after merging #738). The dumped vfg and the bc file are here [svfg.zip](https://github.com/SVF-tools/SVF/files/9097594/svfg.zip).
 
```cpp
#include <string>

void sinkfunc(std::string sink_str)
{
    std::string sink = sink_str;
}

int main()
{
    const std::string str = "foobar";
    sinkfunc(str);
    return 0;
}
```

The key difference in the two graphs is: `StoreVFGNode ID: 59` from the older commit (5b396999) is connected to `LoadVFGNode ID: 47` using a dashed line, but not in the newer commit (2e2fed50). The missing link in the newer version is a similar edge from `StoreVFGNode ID: 59` to `LoadVFGNode ID: 49`.

**Comment by yuleisui** [comment]
Thanks for reporting. @shuangxiangkan can you take a look at this issue?

**Comment by yuleisui** [comment]
@tandf should be fixed by https://github.com/SVF-tools/SVF/pull/766. Have a try and let us know if any problem.

**Comment by tandf** [comment]
@yuleisui @shuangxiangkan Thank you so much for the help! I also include a missing c++ string api in #769. Now I'll try to sovle the problem of global variable that I mentioned at the beginning.

**Comment by tandf** [comment]
I think I find the root cause. It seems SVF is working correctly, and the mssa is generated correctly. The key is that the global variable initialization (using a cpp str api to initialize the cpp string) is called in `@__cxx_global_var_init()`, which is called by `@_GLOBAL__sub_I_globalStrTest.cpp()`, which is later stored in `@llvm.global_ctors`. See the ll file [globalStrTest.zip](https://github.com/SVF-tools/SVF/files/9115888/globalStrTest.zip).

According to [llvm language reference](https://llvm.org/docs/LangRef.html#the-llvm-global-ctors-global-variable), 
> The @llvm.global_ctors array contains a list of constructor functions, priorities, and an associated global or function. The functions referenced by this array will be called in ascending order of priority (i.e. lowest first) when the module is loaded.

This means the function call as well as the cpp string initialization is done implicitly, which requires special handling.

Do you have any plan on supporting this? I can also help if you could tell me how to support it in SVF. Thanks!

**Comment by yuleisui** [comment]
I see, thanks for digging up. We can add the function call to `__cxx_global_var_init` at the begging of the main function or an artificial svf_main function: https://github.com/SVF-tools/SVF/blob/master/lib/SVF-FE/LLVMModule.cpp#L200

Would be great if you could help with this implementation.

**Comment by tandf** [comment]
Thanks a lot! I realize that svf_main function solves my problem and there isn't actually much I need to do.

I implemented the priority according to the reference in #774. I also support destroy functions as specified in the llvm language reference. I did some simple tests by manually creating `@llvm.global_ctors` variable with several function entries and it seems to be working correctly. I encountered another problem on `getFlatternedElemTpe()` though, which I'll open another issue to discuss since it's not relevant to this one.

Please tell me if there is anything I can improve on my code.
