### ISSUE TITLE
Memory Leak Example

### ISSUE THREAD

**Issue by HowToNamene** [SVF-tools/SVF#763]
Hi, I am learning about the SVF recently!
When I use Saber to run the memory leak, a false negative appeared. Example is:
`#include <stdlib.h>
 void test()
{
int *x; 
int *b=(int *)malloc(5);
 x=b; 
int *c=(int *)malloc(5); 
x=c; free(x);
} 
int main()
{
test2();
}`
Pointer b does not report a memory leak . It is found that the two store instructions related to x are connected because they operate  the same region. As a result, allocations of b and c reach free() in the VFG. 

Could you please tell me if the VFG is behaving correctly, and if not, how can I fix it? Thanks a lot.

**Comment by yuleisui** [comment]
It looks to me that this is because lack of the strong updates in current saber. If the pointer dereference refers to a singleton at a StoreVFGNode, the traversal on VFG from one memory allocation can be stopped hence can avoid this false negative.

**Comment by jumormt** [comment]
Hi @HowToNamene ,

saber works fine on my side by reporting line 4 as a memory leak:
![image](https://user-images.githubusercontent.com/44386076/178633030-42a5bea6-703f-4676-89eb-9bf5688ac930.png)
![image](https://user-images.githubusercontent.com/44386076/178633188-6566fac6-3e32-413e-8dac-adb7bb1be464.png)

Do you use the latest SVF?

Regards

**Comment by jumormt** [comment]
We have removed the Incoming Edge for strong-update (SU) store instruction. Please kindly refer to https://github.com/SVF-tools/SVF/blob/3f1a76999b404502f66b5b9783fc2830b0b4d139/lib/SABER/SaberSVFGBuilder.cpp#L224

**Comment by HowToNamene** [comment]
Thanks a lot,  I'll try a new SVF right away.
