### ISSUE TITLE
Alias queries always return no alias

### ISSUE THREAD

**Issue by muke101** [SVF-tools/SVF#765]
I'm trying to use SVF to make alias queries on LLVM values. I'm using the following code:

```c++

Andersen *ander;
Steensgaard *steens;
VersionedFlowSensitive *VFS;

void init_SVF(llvm::Module *mod)
{
    SVF::SVFModule* svfModule = LLVMModuleSet::getLLVMModuleSet()->buildSVFModule(*mod);
    svfModule->buildSymbolTableInfo();

    SVFIRBuilder builder;
    SVFIR* pag = builder.build(svfModule);

    ander = AndersenWaveDiff::createAndersenWaveDiff(pag);
    VFS = VersionedFlowSensitive::createVFSWPA(pag);
    steens = Steensgaard::createSteensgaard(pag);
}

AliasResult SVF_query(Value *p, Value *q){
    AliasResult result = AliasResult::MayAlias;
    if ((result=ander->alias(p, q)) != AliasResult::MayAlias) return result;
    if ((result=VFS->alias(p, q)) != AliasResult::MayAlias) return result;
    if ((result=steens->alias(p, q)) != AliasResult::MayAlias) return result;
    return result;
}
```

But `ander->alias(p,q)` will always return no alias regardless of if the pointers really could alias or not. I haven't tested the others but as they're set up in the same way presumably they will too, but let me know if it would be helpful to confirm this. 

What am I doing wrong and how can I use SVF properly for this?

**Comment by yuleisui** [comment]
What is your analysed program? Does your target program has proper memory allocations? SVF’s Alias analysis relies on points to results and make sure your program does not have null pointers when querying aliases.

**Comment by muke101** [comment]
Ah, yes sorry this was the problem - with full programs instead of isolated functions it works.

**Comment by muke101** [comment]
Ah, I have actually just found that using SVF with the same code I posted above will give no alias results in places LLVM marks as either must or partial alias. This is obviously concerning - should I open a new issue for this or is it possible I've made a simple mistake again? I do now have SVF giving both may alias and no alias results, but never must or partial.

**Comment by yuleisui** [comment]
Which c or llvm bc code do you post (never saw them)? 

Note that SVF does not support must or partial aliases.

**Comment by muke101** [comment]
I found the specific C file and function these pointers occur in if that's helpful - md5.c (https://github.com/eembc/coremark-pro/blob/main/mith/src/md5.c) in the function DigestToBase16 (line 277). It's a short function so maybe you can catch why SVF thinks there are pointers here that don't alias which LLVM think they must.

**Comment by muke101** [comment]
I've looked more into this myself and isolated the problem. The specific function in the C code where these pointers come from is DigestToBase16 and is found in this file in the coremark codebase: https://github.com/eembc/coremark-pro/blob/main/mith/src/md5.c

I've tried running LLVM and SVF analysis on just this function by itself and found what causes SVF to mark the pointers as no alias:

SVF marks as may alias: https://gist.github.com/muke101/47f0cf6fab7d84f43d8c47be465930a6
SVF marks as no alias: https://gist.github.com/muke101/8a9657767e268b75c87a95e05aea5503

So, if `zBuf` comes from `argv[2]` instead of a malloc (of constant or variable size), SVF marks the `zBuf[j] = 0` and one of the `zBuf[j++]` pointers as no alias when LLVM marks them as must alias. Is this a bug or a 'feature' of how SVF does WPA?

**Comment by yuleisui** [comment]
One more thing to add even though you have closed this issue. SVF relies on points-to analysis for aliases. If a pointer has no points-to target, dereferencing that pointer will not be aliasing with any other memory accesses. Points-to analysis requires explicit memory allocation to be added in the points-to set.

**Comment by muke101** [comment]
Yes I see now. Thanks. 

Is there a way to easily catch cases that trivially no alias in points-to analysis from LLVM that you know of? Or perhaps a way to plug into SVF to differentiate when it marks pointers as no alias due to lack of memory allocation/the program never reaching that point? It would make my comparison between SVF and LLVM much easier.
