### ISSUE TITLE
Options: positional command line argument breaks user applications

### ISSUE THREAD

**Issue by 251** [SVF-tools/SVF#778]
Recently some options were moved to Options.cpp:
https://github.com/SVF-tools/SVF/blob/37d37cd773fa435e7936c5d0e0ae0841d98463b2/lib/Util/Options.cpp#L787

Unfortunately, when one links SVF now against an application that uses positional arguments as well, LLVM exits with:
```Bash
<input bytecode> option: error - this positional option will never be matched, because it does not Require a value, and a cl::ConsumeAfter option is active!
```

In my branch I use a setter: https://github.com/251/SVF/commit/ad70f860ee2431523b5478e3186fef44f531baeb to prevent it. Any ideas how to fix it properly (a library should not have positional options imho)? Modifying ctor or changing the signature of `analyze()` seem to be worse alternatives.

**Comment by yuleisui** [comment]
How about changing the name `Options::InputFilename` in your application or in SVF? Once linked, it should allow multiple positional options?

**Comment by 251** [comment]
It's not about the names (which are distinct), it's the combination with a cl::ConsumeAfter flag. In short, LLVM can't create a proper parser for it anymore. IMHO it's bad design when a library dictates the command-line argument layout of an application esp. when the flag is not used in the library or the application.

**Comment by yuleisui** [comment]
Yes, separating tool and lib option headers is a better idea since a few tools in svf use that positional option. Would you be able to help us with this separation?

**Comment by 251** [comment]
I can try but that might complicate the build setup. Easiest solution would be to put the tool flags back into the tools.

**Comment by yuleisui** [comment]
@TalbenXu could you help remove `Options::InputFilename` flag and move this flag to each the tool (SVF/tools/*.cpp)?

**Comment by yuleisui** [comment]
Fixed https://github.com/SVF-tools/SVF/pull/782

**Comment by 251** [comment]
Seems to work for me, thanks a lot!
