### ISSUE TITLE
Questions about warning messages

### ISSUE THREAD

**Issue by HowToNamene** [SVF-tools/SVF#785]
Hi，
I ran the MemoryLeak with two cases, but got two same warning messages. The cases and their warning messages are as follows:
Case1：
![image](https://user-images.githubusercontent.com/47890019/179692993-a110858c-d572-4fdf-857c-f4377eb7852d.png)
Warning Message1:
![image](https://user-images.githubusercontent.com/47890019/179694872-88a1e367-4390-4c01-be42-0b2b71785479.png)
Case2:
![image](https://user-images.githubusercontent.com/47890019/179695332-056a84c6-93ec-4d03-b54f-912f4693628e.png)
Warning Message2:
![image](https://user-images.githubusercontent.com/47890019/179695124-1b8e2e38-4118-4671-bf4d-d7c136bf259e.png)
Could you please tell me what the warning message indicate and why they are same?

**Comment by jumormt** [comment]
Hi @HowToNamene,

The current saber does not distinguish between true/false branches because of the solver (CUDD). We are replacing CUDD with Z3, and saber will support this feature in the future :-)

Kind regards

**Comment by yuleisui** [comment]
Try again with the latest SVF. This patch https://github.com/SVF-tools/SVF/commit/b380f46b9621123baf30f2482d411868aa62f584 should fix your issue @HowToNamene
