### ISSUE TITLE
Regression test cases?

### ISSUE THREAD

**Issue by rainoftime** [SVF-tools/SVF#79]
I noticed there is repo (https://github.com/SVF-tools/PTABen) containing a micro-benchmark suite 

Is it possible to provide a set of real-world projects (maybe just bitcode files) for regression testing?
For example, the cclyzer project (https://github.com/plast-lab/cclyzer) includes some bitcodes from coreutils  and postgresql (https://github.com/plast-lab/cclyzer/tree/master/tests/)

**Comment by yuleisui** [comment]
The aim of PTABen is to validate the correctness of our pointer analysis. Every test contains both the c/c++ source code and one or more stub function (or true answers, e.g., MAYALIAS and NOALIAS) for developers to compare the analysis results again the true answers for validation purpose. The project you pointed out does not have this functionality. I am not quite sure whether it can be seen as regression tests.

For compiling an open source project, please refer to our gold plugin in the wiki.
