### ISSUE TITLE
case of err "vcall gep idx not constantint"

### ISSUE THREAD

**Issue by lcy8047** [SVF-tools/SVF#804]
I made svf example( next code ), 
``` C++
int arg_num = 0;
char **arg_value = new char*[argc];
std::vector<std::string> moduleNameVec;
SVF::LLVMUtil::processArguments(argc, argv, arg_num, arg_value, moduleNameVec);
llvm::cl::ParseCommandLineOptions(arg_num, arg_value,
                            "Whole Program Points-to Analysis\n");

if (SVF::Options::WriteAnder == "ir_annotator")
{
    SVF::LLVMModuleSet::getLLVMModuleSet()->preProcessBCs(moduleNameVec);
}

SVF::SVFModule* svfModule = SVF::LLVMModuleSet::getLLVMModuleSet()->buildSVFModule(moduleNameVec);
svfModule->buildSymbolTableInfo();

SVF::SVFIRBuilder builder;
SVF::SVFIR* pag = builder.build(svfModule);

SVF::FlowSensitive *pta = new SVF::FlowSensitive( pag );
pta->analyze();
```

and I used my IR code that include below code.
```
%call101.sink114 = phi %class.testclass* [ %call101, %if.then99 ], [ %call94, %if.end89 ]
%.sink = phi i64 [ 4, %if.then99 ], [ 5, %if.end89 ]
%29 = bitcast %class.testclass* %call101.sink114 to void (%class.testclass*), !dbg !254329
%vtable102 = load void (%class.testclass), void (%class.testclass*)*** %29, align 8, !dbg !254329
%vfn103 = getelementptr inbounds void (%class.testclass*), void (%class.testclass)** %vtable102, i64 %.sink, !dbg !254329
%30 = load void (%class.testclass*), void (%class.testclass)** %vfn103, align 8, !dbg !254329
tail call void %30(%class.testclass* nonnull align 8 dereferenceable(376) %call101.sink114) #55, !dbg !254329
```
However, when I was running `pta->analyze()`, error occur.
Because of `%vfn103 = getelementptr inbounds void (%class.testclass*), void (%class.testclass)** %vtable102, i64 %.sink, !dbg !254329`, this instruction has index as "phi" ( `%.sink = phi i64 [ 4, %if.then99 ], [ 5, %if.end89 ]` ).
So, error occur in `cppUtil::getVCallIdx(CallSite cs)` function. ( `lib/SVF-FE/CPPUtil.cpp` )
``` C++
u64_t cppUtil::getVCallIdx(CallSite cs)
{
    const LoadInst *vfuncloadinst = SVFUtil::dyn_cast<LoadInst>(cs.getCalledValue());
    assert(vfuncloadinst != nullptr);
    const Value *vfuncptr = vfuncloadinst->getPointerOperand();
    const GetElementPtrInst *vfuncptrgepinst =
        SVFUtil::dyn_cast<GetElementPtrInst>(vfuncptr);
    User::const_op_iterator oi = vfuncptrgepinst->idx_begin();
    const ConstantInt *idx = SVFUtil::dyn_cast<ConstantInt>(&(*oi));
    u64_t idx_value;
    if (idx == nullptr)
    {
        SVFUtil::errs() << "vcall gep idx not constantint\n"; // this line!
        idx_value = 0;
    }
    else
        idx_value = idx->getSExtValue();
    return idx_value;
}
```

**Comment by yuleisui** [comment]
What do you mean by an error occurs, Is that an assertion or incorrect idx_value? Any idea how to fix it?

**Comment by lcy8047** [comment]
I can't think of how to fix it right now...
But, since the `getVCallIdx` function is used inside the function that gets virtual functions list (ex. `void CHGraph::getVFnsFromVtbls (CallSites, constVTableSet&vtbls, VFunSet&virtualFunctions)`), isn't it possible to analyze the previous instructions and fix the function(`getVFnsFromVtbls`) to processing all of the index?

Please let me know if there's anything I don't understand.

**Comment by yuleisui** [comment]
Can you send us the bc? From your case, the function pointer `%30` is from a load instruction. I didn't see any problem.

**Comment by lcy8047** [comment]
`%30` is from `%vfn103` in load instruction, but `%vfn103` is defined by index `%.sink` ( 4 or 5 ). I think this is the problem.
And I attached test.ll file.
Thank you for reply :)
[test.ll.zip](https://github.com/SVF-tools/SVF/files/9238338/test.ll.zip)

**Comment by yuleisui** [comment]
I had a look at the bc. The reason seems to be that your vtable retrieval has a non-constant index due to `phi`. Does it return  `idx_value = 0` on your side?

**Comment by lcy8047** [comment]
Yes, but doesn't it occur any future problems? My example with my bc does not work successfully and takes too many times so, I can't figure out the root cause.

**Comment by yuleisui** [comment]
What do you mean by `does not work successfully`? Any crash or unexpected results?

From my understanding of your bc code, it is not constant index hence the vtable retrieve can only be determined during runtime. Your case is indeed a good one. I am unsure in what scenarios the vtable offset is a variable.

For performance, your program is quite large so it may take minutes or even hours to finish Andersen's pointer analysis.

If you want to obtain a callgraph in a faster way, you can use `wpa -type test.bc`

**Comment by lcy8047** [comment]
I need pointer analysis, but it takes more than 3-4 hours as you commented.
So I tried to save result to file. However, when I check the result, shell is killed and there is nothing.

``` C++
SVF::FlowSensitive *pta = new SVF::FlowSensitive( pag );
pta->analyze();
pta->writeToFile( "savefile" );
```

Then, I'll try to figure out the cause. Thank you very much for your reply :)

**Comment by lcy8047** [comment]
I found the cause that is the memory issue. It takes almost 45GB. So close the issue.
