### ISSUE TITLE
Using reference as function arg

### ISSUE THREAD

**Issue by tandf** [SVF-tools/SVF#805]
Hi,

When I use SVF to analyze code using reference function arguments, I notice that there seems to be a missing link. Take the code below for example. In the dumped VFG, the constant is connected from GepVFGNode ID: 29 (on the right of the figure) to StoreVFGNode ID: 44. I expect a link from StoreVFGNode ID: 44 to LoadVFGNode ID: 34, but there isn't. Could you help me take a look at whether this is expected behavior? Thanks!

[code and graph](https://github.com/SVF-tools/SVF/files/9238020/test.zip)

```cpp
// Release-build/bin/svf-ex -model-arrays -model-consts -dump-vfg
#include <string>
void foo(const std::string &str)
{
    return;
}
void bar(const std::string &str)
{
    foo(str);
}
int main()
{
    bar("abc");
    return 0;
}
```

![pic](https://user-images.githubusercontent.com/25607777/182263802-57a89353-3384-4153-ad77-d5fcac7f8087.png)

**Comment by yuleisui** [comment]
I suspect that this is related to the missing handling of some std::string API?

**Comment by tandf** [comment]
I don't think this is the cause. The std::string APIs used here are already supported in SVF. Another reason is that I found that if I add `std::string a = str;` in foo(), I can find the link from the constant to `std::string a`. See the figure below (the graph is left and right mirrored. The part in the red box is the additional link to `std::string a`).

My guess is that because it's a reference arg, llvm adds a `%str.addr = alloca %"...basic_string"*, ...`, which is a pointer pointing to the arg. So this is the part I'm not sure: should the pointer to the string also be linked in the graph?

![fig](https://user-images.githubusercontent.com/25607777/182285357-bd31681e-db18-4d33-81be-b6893540387f.jpg)

```cpp
#include <string>
void foo(const std::string &str)
{
    // Add a line below
    std::string a = str;
    return;
}
void bar(const std::string &str)
{
    foo(str);
}
int main()
{
    bar("abc");
    return 0;
}
```

**Comment by yuleisui** [comment]
For your example before adding ‘a=str’, do we have a load for ‘str’ since it is never used?

Do you suggest the reference is not handled by SVF?

**Comment by tandf** [comment]
Before adding `a=str`, the ir is like
```
define ...foo...(%str) {
    %str.addr = ... basic_string *
    store .. basic_string * %str, ... basic_string ** %str.addr
    ret
}
```
so there isn't a load.

I think the reference is handled because `a=str` can lead to a link. But I feel there should be a link from the string constant to %str.addr if my understanding is correct

**Comment by yuleisui** [comment]
I see. Do the two pointers Var40 at StoreVFGNode ID: 44 and Var 29 at LoadVFGNode ID: 34 point to the same object?

**Comment by tandf** [comment]
Could you tell me how to figure out whether two pointers in the vfg point to the same object? I can see a series of assignments: Var40 <- 54, 40 <- 41, 29 <- 28, and 40 and 28 are a pair of actual/formal params.

**Comment by yuleisui** [comment]
You can print out their points-to sets using getPts to see whether two pointers have overlapping pointees

**Comment by yuleisui** [comment]
I just had a chance to have a look at your bc and the SVFG (without adding `a = str`.  There shouldn't be an edge from StoreVFGNode ID: 44 to LoadVFGNode ID: 34 since the load and store are accessing different memory objects (object pointed by `%ref.tmp` and object pointed by `%str.addr`). These two non-aliasing objects are stack objects allocated in `bar` and `foo` functions.

In fact, `%ref.tmp`, `%str`, `%0 = load %"class.std::__cxx11::basic_string"*` point to the same object. If we continue to load something from `%0`, say %something = load %0, then this load statement will have an incoming value flow from StoreVFGNode ID: 44.

`_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_` represents a store edge stores `@.str` to `%ref.tmp`

**Comment by tandf** [comment]
Thanks for the reply! It helps me understand SVF better.
