### ISSUE TITLE
Redundant ConstantExpr after running BreakConstantGEPs

### ISSUE THREAD

**Issue by AminoACID123** [SVF-tools/SVF#825]
I notice that SVF runs `BreakConstantGEPs` to convert those constant gep expressions into instructions. Below is a simple C program I tested: 
```
#include <stdio.h>
int main()
{
    FILE *fp = fopen("out.txt", "w");
    fclose(fp);
    return 0;
}
``` 
The original IR looks like this:
```
  %3 = call noalias %struct._IO_FILE* @fopen(i8* getelementptr inbounds ([8 x i8], [8 x i8]* @.str, i64 0, i64 0), i8* getelementptr inbounds ([2 x i8], [2 x i8]* @.str.1, i64 0, i64 0)), !dbg !18
```
And the IR after running `BreakConstantGEPs`:
```
  %3 = getelementptr inbounds [8 x i8], [8 x i8]* @.str, i64 0, i64 0
  %4 = getelementptr inbounds [2 x i8], [2 x i8]* @.str.1, i64 0, i64 0
  %5 = call noalias %struct._IO_FILE* @fopen(i8* %3, i8* %4), !dbg !18
```
Seems ok. However, when I print all the `valSyms` in SymbolTable, I notice that there are two constant geps:
```
i8* getelementptr inbounds ([8 x i8], [8 x i8]* @.str, i64 0, i64 0)
i8* getelementptr inbounds ([2 x i8], [2 x i8]* @.str.1, i64 0, i64 0)
```
That's what confuses me here. Given that `BreakConstantGEPs` runs before SymbolTable is built, why are these two constant geps still present? When are they actually added into SymbolTable?

**Comment by yuleisui** [comment]
`BreakConstantGEPs` runs before SymbolTable is built.
