### ISSUE TITLE
strange memory leak warning when using Saber

### ISSUE THREAD

**Issue by mobsceneZ** [SVF-tools/SVF#834]
Lately I have been trying to use Saber for memory leak detection. I started with an example illustrated in Saber's paper: 
```C
#include <stdio.h>
#include <stdlib.h>

char** readBuf() {
    char** mBuf = malloc(sizeof(char*));
    *mBuf = malloc(sizeof(char) * 2);
    return mBuf;
}

void freeBuf(char** fBuf) {
    char* z = *fBuf;
    free(z);
    free(fBuf);
}

void SerialReadBuf() {
    for(int n = 0; n < 100; n++) {
        char** buf = readBuf();
        char*  tmp = *buf;
        if(*tmp != '\n')
            printf("%c", *tmp);
        else
            continue;
        freeBuf(buf); 
    }
}

int main(void) {
    SerialReadBuf();
}
```
Following SVF's wiki document, I compiled above code using following command:
```sh
clang -c -emit-llvm -g test.c -o test.bc
```
At last, I ran following command to detect memory leak:
```sh
saber -leak -valid-tests -mem-par=inter-disjoint -saber-full-svfg -stat=false test.bc
```
Resulted in strange ouput below:
```
         PartialLeak : memory allocation at : ({ ln: 6  cl: 13  fl: test.c })
                 conditional free path:
                  --> ({ ln: 20  cl: 12  fl: test.c }|True)
```
I can't interpret this output since it seems like address-taken variable `*mBuf`'s leak is detected, but the conditional free path lead to the actual benign path. Meanwhile, top-level pointer `mBuf`'s leak is not detected.

As far as I know, I am using rather new version of SVF equipped with LLVM 13.0.0.

**Comment by jumormt** [comment]
Hi @mobsceneZ,

Can you double-check these command lines cos saber works fine on my side regarding this example by reporting Line 18 as partial free as well. Regarding the conditional free path, the true branch of Line 20 is indeed the conditional free path that leads to `freeBuf` which releases the memory allocated.

Kind regards,
Xiao

**Comment by mobsceneZ** [comment]
Hi @jumormt, 

It looks good to me now somehow ;P. By the way, Is there any possible way to report conditional not-free path?

**Comment by jumormt** [comment]
Replacing [`finalCond`](https://github.com/SVF-tools/SVF/blob/master/lib/SABER/ProgSlice.cpp#L164) with `!finalCond` should report the leaked path.

**Comment by mobsceneZ** [comment]
@jumormt Thanks a lot !
