### ISSUE TITLE
value flow of switch instruction

### ISSUE THREAD

**Issue by Sanghoon-Jung** [SVF-tools/SVF#842]
Hello, I always thank you for giving updates in SVF.

I'm using SVF to trace a value in source code IR.
Yet, I found that SVF value flow doesn't trace the SwitchInst in LLVM IR.

For example,
```%2 = call i32 @some_func
store i32 %2, i32* %1, align 4
%3 = load i32, i32* %1, align 4
switch i32 %3, label %8 [
  i32 -1, label %4
  i32 0, label %6
]
```

I expected the result instrunctions from VFG with %2 reg as:
1. `store i32 %2, i32* %1, align 4`
2. `%3 = load i32, i32* %1, align 4`
3. 
```
switch i32 %3, label %8 [
  i32 -1, label %4
  i32 0, label %6
]
```

However, the output is only:
1. `store i32 %2, i32* %1, align 4`
2. `%3 = load i32, i32* %1, align 4`

How can I trace the switch instruction in value flow?

**Comment by yuleisui** [comment]
Thanks for reporting this. Branches and control-flow conditions were not considered for value-flows before.

We have just fixed it for your case. Could you try the code in this pull request? If you confirm back it is correct, I will merge it.

https://github.com/SVF-tools/SVF/pull/843

**Comment by Sanghoon-Jung** [comment]
Hello, thanks for your comment.

I tried to add the code on lib/Graphs/VFG.cpp as you described in the [pull request](https://github.com/SVF-tools/SVF/pull/843/commits/8fc59c93a036f7e0953483763159ab98e47b3454).

However, it seems not working well.
Here is my example.

my test IR is this function.
```
define dso_local void @_Z4sub2v() #4 {
  %1 = alloca i32, align 4
  %2 = call i32 @fork() #3
  store i32 %2, i32* %1, align 4
  %3 = load i32, i32* %1, align 4
  switch i32 %3, label %8 [
    i32 -1, label %4
    i32 0, label %6
  ]

4:                                                ; preds = %0
  %5 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([16 x i8], [16 x i8]* @.str, i64 0, i64 0))
  call void @exit(i32 -1) #7
  unreachable

6:                                                ; preds = %0
  %7 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([13 x i8], [13 x i8]* @.str.1, i64 0, i64 0))
  br label %11

8:                                                ; preds = %0
  %9 = call i32 @getpid() #3
  %10 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([18 x i8], [18 x i8]* @.str.2, i64 0, i64 0), i32 %9)
  br label %11

11:                                               ; preds = %8, %6
  ret void
}
```

And I tried to trace the returned value from calling @fork().
I printed the visited node when traversing VFG from the value to check if the change works.
The output was actually, like this:
```
fork caller: CallICFGNode46 {fun: _Z4sub2v}

value flow:
ActualRetVFGNode ID: 172 CS[]ValVar ID: 126
   %2 = call i32 @fork() #3 
StoreVFGNode ID: 105 StoreStmt: [Var124 <-- Var126]
   store i32 %2, i32* %1, align 4 
FormalOUTSVFGNode ID: 246 {fun: _Z4sub2v}RETMU(10V_2)
pts{125 }

LoadVFGNode ID: 86 LoadStmt: [Var130 <-- Var124]
   %3 = load i32, i32* %1, align 4 
```

The output was same as the one that I didn't add the code as the pull request. (Doesn't seem to trace the Branch)
Could you check it once more?

Thank you.

**Comment by yuleisui** [comment]
can you try to debug to see whether the following code in your VFG.cpp actually executed or not?
Try to see whether the edge is connected between the LoadVFGNode ID: 86 to the switch SVFGNode.
```
            const SVFVar* cond = branchNode->getBranchStmt()->getCondition();
            if (cond->isConstantData() == false)
                addIntraDirectVFEdge(getDef(cond), nodeId);
```

**Comment by Sanghoon-Jung** [comment]
Sorry for bothering you.
I debugged the VFG.cpp and found that it doesn't reach the code,
But It actually works after I re-building libSVF.a and tried again.

The result I get is:
```
fork caller: CallICFGNode46 {fun: _Z4sub2v}

value flow:
ActualRetVFGNode ID: 176 CS[]ValVar ID: 126
   %2 = call i32 @fork() 
StoreVFGNode ID: 105 StoreStmt: [Var124 <-- Var126]
   store i32 %2, i32* %1, align 4 
FormalOUTSVFGNode ID: 245 {fun: _Z4sub2v}RETMU(8V_2)
pts{125 }

LoadVFGNode ID: 86 LoadStmt: [Var130 <-- Var124]
   %3 = load i32, i32* %1, align 4 
BranchVFGNode ID: 216 PAGEdge: [BranchStmt: [Condition Var130]
Successor 0 ICFGNode51   Successor 1 ICFGNode53   Successor 2 ICFGNode54   
   switch i32 %3, label %10 [
    i32 -1, label %4
    i32 0, label %7
  ]
```

It goes well.
Thank you for your comment.
