### ISSUE TITLE
Questions About Saber's Memory Leak Detector

### ISSUE THREAD

**Issue by mobsceneZ** [SVF-tools/SVF#848]
When browsing through Saber's implementation for static memory leak detector, I found that in `LeakChecker.cpp:reportBug(ProgSlice* slice)`, Saber will call `slice->evalFinalCond()` if Saber reports a `PartialLeak` for current `slice`:

```C++
void LeakChecker::reportBug(ProgSlice* slice)
{
    ...
    else if (isAllPathReachable() == false && isSomePathReachable() == true)
    {
        reportPartialLeak(slice->getSource());
        SVFUtil::errs() << "\t\t conditional free path: \n" << slice->evalFinalCond() << "\n"; // <- here
        slice->annotatePaths();
    }
    ...
}
``` 
In `ProgSlice::evalFinalCond()`, it will retrieve all the propositional variables in evaluated `FinalCond`, and prints out one feasible conditional free path to `rawstr`:
```C++
std::string ProgSlice::evalFinalCond() const
{
    std::string str;
    raw_string_ostream rawstr(str);
    NodeBS elems = pathAllocator->exactCondElem(finalCond); // get all condition variables into llvm::SparseBitVector<>
    Set<std::string> locations;
    for(NodeBS::iterator it = elems.begin(), eit = elems.end(); it!=eit; ++it)
    {
        Condition* atom = pathAllocator->getCond(*it);
        const Instruction* tinst = pathAllocator->getCondInst(atom);
        if(pathAllocator->isNegCond(atom)) // <- here
            locations.insert(getSourceLoc(tinst)+"|False");
        else
            locations.insert(getSourceLoc(tinst)+"|True");
    }
    for(Set<std::string>::iterator iter = locations.begin(), eiter = locations.end();
            iter!=eiter; ++iter)
    {
        rawstr << "\t\t  --> (" << *iter << ") \n";
    }

    return rawstr.str();
}
```
At lines commented `<- here`, Saber determines whether the true successor or false successor is traversed in `FinalCond` by querying to `PathAllocator`, which further invokes following function:
```C++
bool PathCondAllocator::isNegCond(const Condition *condition)
{
    return condMgr->isNegCond(condition);
}

virtual bool BDDExprManager::isNegCond(const BDDExpr *cond)
{
    return false;
}
```
This means Saber by default considers True successor only, which is incorrect. Take following code snippet as an example: 
```C
#include <stdio.h>
#include <stdlib.h>

char** readBuf() {
    char** mBuf = malloc(sizeof(char*));
    *mBuf = malloc(sizeof(char) * 2);
    return mBuf;
}

void freeBuf(char** fBuf) {
    char* z = *fBuf;
    free(z);
    free(fBuf);
}

void SerialReadBuf() {
    for(int n = 0; n < 100; n++) {
        char** buf = readBuf();
        char*  tmp = *buf;
        if(*tmp != '\n')
            continue;
        else
            printf("%c", *tmp);
        freeBuf(buf); 
    }
}

int main(void) {
    SerialReadBuf();
}
``` 
Compile above example with following command line options:
```sh
clang -c -emit-llvm -g test.c -o test.bc
```
Run saber for `test.bc` to detect memory leaks: 
```
$ saber -leak -valid-tests -mem-par=inter-disjoint -stat=false test.bc
         PartialLeak : memory allocation at : ({ ln: 18  cl: 22  fl: test.c })
                 conditional free path:
                  --> ({ ln: 20  cl: 12  fl: test.c }|True)

         PartialLeak : memory allocation at : ({ ln: 6  cl: 13  fl: test.c })
                 conditional free path:
                  --> ({ ln: 20  cl: 12  fl: test.c }|True)
```
Here the True branch at `test.c:20` is exactlly the non-free path instead of conditional free path, which is incorrect.

**PS:**
In `BDDExprManager::createFreshBranchCond(const Instruction *inst)` below, which creates new condition variable and maps it to corresponding instruction, `negCond` is not added to `indexToBddCondMap` unlike `bddCond`. I dont know why `negCond` is not treated equally as `bddCond` but this would definitely lead to the situation where we can't index the `negCond` of `bddCond` by querying `indexToBddCondMap` so that `atom` in the second code snippet will never return a NEG condition. That's weird :/
```C++
BDDExprManager::BDDExpr *BDDExprManager::createFreshBranchCond(const Instruction *inst)
{
    u32_t condCountIdx = totalCondNum++;
    BDDExpr *bddCond = createCond(condCountIdx);
    setCondInst(bddCond, inst);
    auto *negCond = NEG(bddCond);
    setCondInst(negCond, inst);
    return bddCond;
}
```

**Comment by yuleisui** [comment]
@jumormt could you help answer this?

**Comment by jumormt** [comment]
@mobsceneZ Which version of SVF are you using? BDDExpr is no longer supported and has been replaced with Z3Expr.

**Comment by mobsceneZ** [comment]
@jumormt I don't know how to get SVF print its current version but I believe it's SVF-2.4.

**Comment by jumormt** [comment]
@mobsceneZ SVF-2.4 does not support Z3Expr. You should fetch the latest version of SVF.

**Comment by mobsceneZ** [comment]
@jumormt alright, thanks~

**Comment by mobsceneZ** [comment]
@jumormt Just a reminder: a moment ago I re-installed SVF to version 2.5 (wchich is the newest AFAIK), I found SVF-2.5 is still using BDDExpr instead of Z3Expr.

**Comment by jumormt** [comment]
@mobsceneZ Use `git clone https://github.com/SVF-tools/SVF` to get the latest SVF.

**Comment by jumormt** [comment]
Alternatively, you can use the mirror `https://gitee.com/naiive/SVF` in gitee.
