### ISSUE TITLE
Cannot analyse `mutt` anymore

### ISSUE THREAD

**Issue by mbarbar** [SVF-tools/SVF#853]
Mutt, attached, used to be analysable but not anymore.
```
mbarbar@cedar ~/git/svf-upstream/Release-build % ./bin/wpa -ander bitcode/mutt.bc 
Assertion failed: (iter!=objSymMap.end() && "obj sym not found"), function getObjSym, file SymbolTableInfo.h, line 241.
```
[mutt.txt](https://github.com/SVF-tools/SVF/files/9437938/mutt.txt)

**Comment by yuleisui** [comment]
@shuangxiangkan Could you take a look at this assertion. I found that it is because of your recent commit at lines 1153-1154 in SVFIRBuilder.cpp. The cs intruction is not an object.

````
     else if (nodeIDType == -3)
           operandID = getObjectNode(cs.getInstruction());   // "   call void @safe_realloc(i8* nonnull %1, i64 %mul) #41 "
```

**Comment by yuleisui** [comment]
It has been fixed by https://github.com/SVF-tools/SVF/pull/855
