### ISSUE TITLE
Question about indrect call icfg

### ISSUE THREAD

**Issue by NICE994** [SVF-tools/SVF#863]
When the program has indirect calls, a **CallICFGNode** may have multiple **RetICFGNode**.
But the public function **getRetICFGNode** of class CallICFGNode only returns **one** RetICFGNode.
```
/// Return callsite
    inline const RetICFGNode* getRetICFGNode() const
    {
        assert(ret && "RetICFGNode not set?");
        return ret;
    }
```
With the function call, I get the icfg_final.dot of a-2.c.
```
  SVFIRBuilder builder_svfir;
  SVFIR *svfir = builder_svfir.build(svfModule);
  AndersenWaveDiff *ander = AndersenWaveDiff::createAndersenWaveDiff(svfir);
  PTACallGraph* callgraph = ander->getPTACallGraph();
  builder_svfir.updateCallGraph(callgraph);
  icfg->dump("icfg_initial");
  icfg->updateCallGraph(callgraph);
  callgraph->dump("callgraph_final");
  icfg->dump("icfg_final");
```
a-2.c and icfg_final.dot are attached in code.zip.
[code.zip](https://github.com/SVF-tools/SVF/files/9547236/code.zip)
![image](https://user-images.githubusercontent.com/32596610/189635198-a15bf812-ed6e-42ea-8ea8-8ac26d6de504.png)
![image](https://user-images.githubusercontent.com/32596610/189635938-2d59a774-0987-4664-909e-e992c3bf5ac1.png)

My Questions are:

1.Can I get **all** the RetICFGNodes of a CallICFGNode with some function I missed?
2. I noticed that `0x555556045510` in CallICFGNode84 is also present in FunExitICFGNode12 and FunExitICFGNode24 which are the predecessors of the corresponding RetICFGNodes. What does '0x555556045510' mean? Can I use it to solve the Q1 problem?

**Comment by yuleisui** [comment]
Only one RetICFGNode per callsite. The indirect edges returned from different function exists can be used to differentiate them
