### ISSUE TITLE
Index out of range for getContainedType()

### ISSUE THREAD

**Issue by bernardnongpoh** [SVF-tools/SVF#864]
I got the following error while running on a simple C program. 

`llvm::Type* llvm::Type::getContainedType(unsigned int) const: Assertion `i < NumContainedTys && "Index out of range!"' failed.`

With **gdb**, the assertion failed at the following line 

https://github.com/SVF-tools/SVF/blob/master/lib/SVF-FE/SymbolTableBuilder.cpp: Line 478
```
void SymbolTableBuilder::handleGlobalCE(const GlobalVariable *G)
{
    assert(G);

    //The type this global points to
    **const Type *T = G->getType()->getContainedType(0);**
..
..
}
```
Is there anything I am missing. I did compile the llvm bitcode by following the tutorial in the SVF website. 

Thanks

**Comment by yuleisui** [comment]
This is an assertion inside llvm. Which clang you were using and the compiled bc?

**Comment by bernardnongpoh** [comment]
clang version 15.0.0 (https://github.com/llvm/llvm-project.git 35fc666877e04321129e8d701f0e6f4f28fb8848)
Thank you very much for your reply Yulei

**Comment by bernardnongpoh** [comment]
I plan to do a check before accessing the index 
```
if(G->getType()->getNumContainedTypes()>0){
T=G->getType()->getContainedType(0);
}
else
T=G->getType();
```
Will this introduced any issues in the analysis?

**Comment by yuleisui** [comment]
Can you try clang 13? It might be a version issue

**Comment by yuleisui** [comment]
> I plan to do a check before accessing the index
> 
> ```
> if(G->getType()->getNumContainedTypes()>0){
> T=G->getType()->getContainedType(0);
> }
> else
> T=G->getType();
> ```
> 
> Will this introduced any issues in the analysis?

This fix might be incorrect. Could you attach your bc?

**Comment by yuleisui** [comment]
This looks to be a clang version issue. It should work if you compile it under clang 13.

**Comment by bernardnongpoh** [comment]
Yes, it works with clang 14. Is there any plan to support newer version of clang in the future?

**Comment by bernardnongpoh** [comment]
Thank you very much for your time.

**Comment by bernardnongpoh** [comment]
compile with clang 14 works
