### ISSUE TITLE
Why "Sparse" in SVFG?

### ISSUE THREAD

**Issue by tregua87** [SVF-tools/SVF#870]
Hi!
I am trying to understand the difference between VFG and SFVG in the context of this framework, lemme explain.

VFG is Value-Flow Graph is a graph that describes how variables' values move inside the program.

SVFG is Sparse Value-Flow Graph, what does "Sparse" intend in this context?

They are just synonymous or there is a difference?

My doubt comes from the base example (https://github.com/SVF-tools/SVF/wiki/A-simple-driver-example-of-SVF).
In the function:
```
void traverseOnVFG(const SVFG* vfg, Value* val)
```
The object is type `SVFG`, but the variable is just `vfg`. I found similar confusion in the doxygen too where some classes are `VFGxx`, but then there is a `SVFG`.

Is there any reason of the two names? 
For sure it is written somewhere, can you point me to the correct direction, please?

**Comment by yuleisui** [comment]
VFG: def-uses for top-level variables (built from llvm IR)
SVFG: def-uses for both top-level and address-taken variables (built from llvm IR + points-to analysis)

**Comment by tregua87** [comment]
Thanks :)
