### ISSUE TITLE
Failed to generate SVFG for a huge bitcode file

### ISSUE THREAD

**Issue by WhitishZ** [SVF-tools/SVF#878]
Greetings,

I'm new to SVF tools and I'm trying to generate SVFG for a huge bitcode file (size: 32.1MB) with SVF. However, I got the following error from the console:

$ wpa -ander -svfg -dump-vfg px4.bc
wpa: /home/whitish/Projects/SVF/lib/Graphs/SVFG.cpp:1040: static std::string llvm::DOTGraphTraits<SVF::SVFG*>::getNodeAttributes(llvm::DOTGraphTraits<SVF::SVFG*>::NodeType*, SVF::SVFG*): Assertion `false && "no such kind of node!!"' failed.
已放弃 (核心已转储) # In English: Aborted (core dumped)

I've tried to dump other types of graphs including callgraph, PAG and constraint graph. These graphs were all successfully dumped, but SVFG failed.

I'm wondering how to fix this problem. Here are my thoughts at this point:
1. Is the bc file that I'm using broken? I generated it with wllvm and it can be used to dump other graphs with no errors.
2. Is it caused by an out-of-memory issue? I'm running this command on a machine with 64GB memory. SVF reported the error above and exited when the output .dot file grew to around 1.83GB.
3. Or is there a bug in SVF that led to this error?

Could you please help me with this?

P.S. The bitcode file is attached here: 
[px4.zip](https://github.com/SVF-tools/SVF/files/9738281/px4.zip)

**Comment by yuleisui** [comment]
Can you make sure you are using the latest version of SVF?  This assertion looks to be an older version. The new one does not have it at line SVFG.cpp1040.

**Comment by WhitishZ** [comment]
Thank you for your reply. I'm using an old version in early September. I'll try again with the latest SVF.

**Comment by WhitishZ** [comment]
I have tried again with the latest version of SVF, and it worked this time. Seems like there was a bug in the previous version. Thank you very much!
