### ISSUE TITLE
incorrect alias result

### ISSUE THREAD

**Issue by mengjianwei12345** [SVF-tools/SVF#882]
Hello, when I tested alias analysis in FSPTA, I found that sp in the *ip->sp = 1 statement in the thread1() method and the *sst1->sp = 1 statement and sp in the *(sst1->sp) = *pi statement in the thread1() method are noalias, but in fact they have aliases.
#include<pthread.h>
#include<unistd.h>
#include<stdio.h>
#include<stdlib.h>

pthread_t t_g;

void *thread1(void*);
void *thread2(void*);
void *thread3(void*);

int i = 1; 
int *pi = NULL; //global

typedef struct SS{
    int *sp;
    pthread_t tt;
    int si;
} SST;

void* thread1(void* p)
{
    SST *ip = (SST*)p;
    *ip->sp = 1;
    return NULL;
}

SST* myfree(SST*p)
{
    pthread_create(&p->tt, NULL, thread1, (void*)p);
    pthread_detach (p->tt);
    return p;
}

int test(SST *sst1){
    pi = (int*)malloc(10);
    int *qq = (int*)malloc(10);
    SST sst;
    int q;

    myfree(sst1);
    *sst1->sp = 1;

    //2 races.
    *(sst1->sp) = *pi;
    *pi = 1;
}

int main()
{
    SST *newsst;
    test(newsst);
    return 0;
}

**Comment by yuleisui** [comment]
SVF says no alias because newsst is a null pointer

**Comment by mengjianwei12345** [comment]
But when I change the main function as shown below, the result is still noalias.
int main()
{
    SST newsst;SST *sst=&newsst;
    test(sst);
    return 0;
}

**Comment by mengjianwei12345** [comment]
OK，thanks.

**Comment by mengjianwei12345** [comment]
yes，i have confirmed，the result is correct when I change the main function to the following.
int main()
{
SST sst;
SST *newsst=&sst;
newsst->sp=&i;
test(newsst);
return 0;
}
