### ISSUE TITLE
SUPA context-sensitive analysis doesn't seem to isolate simple calling contexts

### ISSUE THREAD

**Issue by taptipalit** [SVF-tools/SVF#891]
I used the test program attached below. The function `copy` is invoked from two callsites, with different arguments to update the pointers `objA->qtr` and `objB->qtr`. Without context sensitivity, it would lose precision. But even running with SUPA doesn't seem to help.

```
#include <stdio.h>

typedef struct Object {
    int id;
    int *ptr;
    int *qtr;
} Object;

void copy(int**a, int**b) {
    *a = *b;
}

int main(void) {
    int a, b, c, d;
    Object* objA = malloc(sizeof(Object));
    Object* objB = malloc(sizeof(Object));

    objA->ptr = &a;
    copy(&(objA->qtr), &(objA->ptr));

    objB->ptr = &c;
    copy(&(objB->qtr), &(objB->ptr));

    int* p = objA->ptr;
    int* q = objA->qtr;
    int* r = objB->ptr;
    int* s = objB->qtr;
    printf("%d %d %d %d", objA->ptr, objA->qtr, objB->ptr, objB->qtr);
    return 0;
}
```

I invoked SUPA using the following command:

` ./Debug-build/bin/dvf  -cxt -query=all -max-cxt=3000 -flow-bg=1000 -cxt-bg=1000 -print-all-pts -ander test.bc`

However, in pts-to log, it shows that `q` can still point to both `a` and `c`. But if the call to `copy` was analyzed in a context-sensitive manner, `q` should only point to `a`. In fact when I create two functions `copy1` and `copy2` and replace the first and second invocations of `copy` with them, the analysis can indeed correctly derive the precise results.

Are there any limitations to the context-sensitive analysis, or maybe I'm invoking it incorrectly?

The points-to log: 

```
// -- clip --
----------------------------------------------
##<q> Source Loc: { ln: 27 fl: test.c }
Ptr 50      PointsTo: { 51 }

!!Target NodeID 51   [<q> Source Loc: { ln: 27 fl: test.c }]
----------------------------------------------
##<q> Source Loc: { ln: 27 fl: test.c }
Ptr 51      PointsTo: { 37 41 }

!!Target NodeID 37   [<a> Source Loc: { ln: 14 fl: test.c }]
!!Target NodeID 41   [<c> Source Loc: { ln: 14 fl: test.c }]
----------------------------------------------
// -- clip --
```

**Comment by taptipalit** [comment]
It looks like I should be using `-print-query-pts` and not `-print-all-pts`. If I do that, then the output is correct.

**Comment by yuleisui** [comment]
-print-all-pts is not for dda only, but will print all the pts results for all pointer analysis which has been run before. For dfs, Andersen will be run first as a pre-analysis, it will print the pts for Andersen.

**Comment by taptipalit** [comment]
I see, thanks for the clarification. Closing this.
