### ISSUE TITLE
SVFIRBuilder: Boostrapping can fail with SIGSEGV

### ISSUE THREAD

**Issue by gerion0** [SVF-tools/SVF#896]
As partly suggested in the [library example](https://github.com/SVF-tools/SVF-example/blob/master/src/svf-ex.cpp#L164) I try to use the SVF as library and build an SVFIR externally.

The code for that should be (as I thought):
```
SVFModule* svfModule = LLVMModuleSet::getLLVMModuleSet()->buildSVFModule(llvm_module);

SVFIRBuilder builder;
SVFIR* pag = builder.build(svfModule);
```
with a previously built svfModule. However, that does not work, because the constructor for the `SVFIRBuilder` internally already needs the module:
```
SVFIRBuilder(): pag(SVFIR::getPAG()), svfMod(nullptr), curBB(nullptr),curVal(nullptr) { }
```
The call to `SVFIR::getPAG()` resolves to this:
```
    static inline SVFIR* getPAG(bool buildFromFile = false)
    {
        if (pag == nullptr)
        {
            pag = new SVFIR(buildFromFile);
        }
        return pag;
    }
```
The SVFIR constructor is defined as:
```
SVFIR::SVFIR(bool buildFromFile) : IRGraph(buildFromFile)
{
    icfg = new ICFG();
    ICFGBuilder builder(icfg);
    builder.build(getModule());
}
```
`getModule()` obviously returns `nullptr`. However, the ICFGBuilder cannot handle this thus the program crashes with SIGSEGV.

As also suggested by the example, I found out that the instruction `svfModule->buildSymbolTableInfo();` has the side effect to tell the SVFIR constructor where the svfModule is. I find this highly misleading. It is not clear that `svfModule->buildSymbolTableInfo()` _actually_ initializes the svfModule singleton, so the rest of SVF can use it. It is also not clear, why the module should be given as argument to `SVFIRBuilder::build()` when the construction of this class already needs the module. Why doesn't use `SVFIRBuilder::build()` the already provided module? What happens, if I pass another module to `SVFIRBuilder::build()` as the one used for the SVFIR construction?

**Comment by yuleisui** [comment]
I am not sure why `getModule()` will crash. It calls `SymbolTableInfo::SymbolInfo()->getModule();` and should return the built svfModule by `LLVMModuleSet::getLLVMModuleSet()->buildSVFModule(moduleNameVec)`?

Do you want something like this?
```
SVFIRBuilder builder(svfModule);
SVFIR* pag = builder.build();
```

**Comment by gerion0** [comment]
It is not `getModule()` that crashes. `getModule()` returns a `nullptr` here, which leads to a crash in `ICFGbuiler::build()`.

> Do you want something like this?
> ```
> SVFIRBuilder builder(svfModule);
> SVFIR* pag = builder.build();
> ```

Yes that would be more consistent since the constructor of `SVFIRBuilder` already neads the module.

**Comment by yuleisui** [comment]
Just fixed. Let me know if there any problem.

**Comment by gerion0** [comment]
Yes, it's better now. Thanks!
