### ISSUE TITLE
Disabling dynamic call-graph update in FlowSensitive analysis.

### ISSUE THREAD

**Issue by Machiry** [SVF-tools/SVF#93]
Hi @yuleisui ,

I was evaluating something and want to know..if there is some way to disable dynamic call-graph update in `FlowSensitive` analysis? Basically, I want the `FlowSensitive` analysis to use a prebuild call-graph.

**Comment by rainoftime** [comment]
Intuitively, FlowSensitive analysis may improve the precision of call graphs prebuilt with Andersen's analysis. 
I am not sure about the motivation of disabling dynamic call-graph update.

**Comment by yuleisui** [comment]
@Machiry 
If you want a pre-computed callgraph by Andersen, you may wish to take a look at 
https://github.com/SVF-tools/SVF/blob/31c86b143fc6796bb7f9c51645217f1c09d7e8a5/lib/MSSA/SVFGBuilder.cpp#L38

Then manually disable `onTheFlyCallGraphSolve ` when doing `flow-sensitive analysis`
https://github.com/SVF-tools/SVF/blob/36c9311ca744d89528c6e0190f26cf43036c6190/lib/MemoryModel/PointerAnalysis.cpp#L609

**Comment by Machiry** [comment]
I just want to see how much does the on the fly callgraph construction helps in improving the precision of the flow-sensitive analysis.

**Comment by Machiry** [comment]
Just to add, I tested on 29 large programs, Looks like it affects precision a bit, but not that much. Thank You all.
