### ISSUE TITLE
Fedora Build SVF failed

### ISSUE THREAD

**Issue by xiaoyuwang0** [SVF-tools/SVF#932]
Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 

CMake Error at llvm-13.0.0.obj/lib/cmake/llvm/LLVMExports.cmake:59 (set_target_properties):
  The link interface of target "LLVMSupport" contains:

    ZLIB::ZLIB

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  llvm-13.0.0.obj/lib/cmake/llvm/LLVMConfig.cmake:292 (include)
  CMakeLists.txt:27 (find_package)

I have installed zlib,but still can't build
OS is fedora37

**Comment by xiaoyuwang0** [comment]
I have installed zlib,but still can't build

**Comment by yuleisui** [comment]
https://stackoverflow.com/questions/24808150/how-to-point-cmake-to-zlib-include-path

https://gist.github.com/davidcorbin/0b13604900089b8fcb28

https://discourse.cmake.org/t/cant-find-zlib-missing-zlib-library-ubuntu-20-cmake/2610

**Comment by xiaoyuwang0** [comment]
Thanks!!!   In fedora37, please install "zlib-static"

**Comment by yuleisui** [comment]
Can you make a note in the wiki?

**Comment by xiaoyuwang0** [comment]
ohhh,I would very much like to, bu I'm a rookie level player
