### ISSUE TITLE
help for using svf

### ISSUE THREAD

**Issue by ash1852** [SVF-tools/SVF#940]
Hi, I tried to conduct a pointer analysis on a million line item, however in less than 1 minute svf finished the analysis, I believe I probably did not use svf correctly, I ran svf like the example in the user guide. What command do I need to enter in terminal if I want to analyze the inter-procedural pointer analysis for all function in llvm-bitcode? thank you for your patience and effort.

**Comment by yuleisui** [comment]
Many optimisations and data structure opt happened during the past five years

**Comment by ash1852** [comment]
thanks, so if I want to perform a thorough and precise inter-procedural pointer analysis, which options of wpa should I focus on?

**Comment by yuleisui** [comment]
Would be good to refer to here https://github.com/svf-tools/SVF/wiki/Analyze-a-Simple-C-Program

for Andersen and flow-sensitive analysis

**Comment by ash1852** [comment]
thank you
