### ISSUE TITLE
do svf support multi-thread analysis?

### ISSUE THREAD

**Issue by ash1852** [SVF-tools/SVF#944]
hello, I wander if svf support analyze project with multi-thread to accelerate analysis? Thank you for your effort.

**Comment by ash1852** [comment]
If it is supported, how do I need to enable it? I didn't find a clear answer in help-list-hidden.

**Comment by yuleisui** [comment]
MTA would be something of your interest

**Comment by ash1852** [comment]
How can I control the number of threads? I still haven't found such an option.

**Comment by yuleisui** [comment]
MTA is to analyse multithreaded programs not for analysing programs using multiple threads (parallelisation)

**Comment by ash1852** [comment]
so "analysing programs using multiple threads" is not supported?

**Comment by yuleisui** [comment]
No

**Comment by ash1852** [comment]
ok, thanks.
