### ISSUE TITLE
Value Flow of an address Taken variable

### ISSUE THREAD

**Issue by usama54321** [SVF-tools/SVF#95]
Hi,

I hope this is the right place to ask this question.

I am hoping to capture the uses of an address taken variable throughout a program, in terms of LLVM values, and then any corresponding Allocations in case of any stores. What I am doing right now is to get the SVFGNode of the variable, and traverse over all outgoing edges. If it's an StmtSVFGNode, I can get the corresponding LLVM value/instruction easily, and I have done that already. However, I'm unable to follow the value inter-procedurally. I'm not sure how to get CallSites where there is a use for this address taken variable as a parameter. Can you please guide me about how to follow the value inter-procedurally?

Thanks

**Comment by usama54321** [comment]
Oops, seems like it's tracking values correctly inter-procedurally. My bad!

**Comment by yuleisui** [comment]
Hi Usama,

The uses of address taken variables at a callsite are represented by `ActualINSVFGNode `s.  
see https://github.com/SVF-tools/SVF/wiki/Technical-documentation#321-svfgnode and 
https://github.com/SVF-tools/SVF/blob/73851ecc110637be48338c648561f77100af9c8a/include/MSSA/SVFG.h#L252.

An `ActualINSVFGNode ` denotes a set of (address-taken) objects. You may wish to use the following to retrieve the corresponding object set to determine whether an object is in this set at a particular callsite.
https://github.com/SVF-tools/SVF/blob/f6d9758675e6bb31e61e13c33503ab90242fcb25/include/MSSA/SVFGNode.h#L340

**Comment by yuleisui** [comment]
You were too quick though:)

**Comment by usama54321** [comment]
Hi Yulei,

Thanks a lot :) So the problem I thought I was facing was that there was no SVFGNode for the Function Argument, which should have been in the use chain of the address taken variable. Seems like I was wrong. I was trying to print the instructions for the StmtSVFGNode, and trying to see a CallSite in the def chain. Seems like my concepts are a bit wrong about this at the moment

**Comment by usama54321** [comment]
I have a small question if you don't mind. In terms of SVFGNodes, if there's something like this in code
%2 = call i32 func(i8 ** %6)

and then in the definition of func there is something like
%1 = getelementptr inbounds i8*, i8** %a, 1

where %6 is a use of an address taken variable, will there directly be a PAGEdge between %2 and %1?

**Comment by yuleisui** [comment]
PAGEdge? Can you show me your bit code?

**Comment by usama54321** [comment]
Ahh my bad, I meant SVFGEdge*. Really sorry. My code is something like this.
```
define void @increment(i32* %a) #0 {
entry:
  %0 = load i32, i32* %a, align 4
  %add = add nsw i32 %0, 1
  store i32 %add, i32* %a, align 4
  ret void
}

; Function Attrs: noinline nounwind uwtable
define i32 @main() #0 {
entry:
  %call = call noalias i8* @malloc(i64 16) #2
  %0 = bitcast i8* %call to i32*
  %add.ptr = getelementptr inbounds i32, i32* %0, i64 1
  call void @increment(i32* %add.ptr)
  ret i32 0
}
```
What I wanted to clear up was, in terms of SVFGNodes, will there be an SVFGEdge between %add.ptr and the %a in the increment function?

Thanks, and sorry for the confusion

**Comment by yuleisui** [comment]
Yes, there will be.

**Comment by usama54321** [comment]
Thank you so much :)
