### ISSUE TITLE
Question: how to retrieve SVFGNode from LLVM instruction

### ISSUE THREAD

**Issue by 251** [SVF-tools/SVF#963]
Hi,

What is the intended way to get an SVFGNode from a load/store/... LLVM instruction? From the ModuleSet I can get an SVF::Instruction and via `svfg->getPAG()->getICFG()->getICFGNode(svfInstruction)` I can retrieve an ICFGNode and maybe via `svfg->getPAG()->getSVFStmtList(svfICFGNode)` an SVF::Stmt that I can cast e.g. to a SVF::LoadStmt. But then I get stuck... or miss something.

**Comment by yuleisui** [comment]
1. Iterate every svfgnode and map each to an svfinstruction, or the other way around.
2. Get an svfinstruction from an llvminstruction  via https://github.com/SVF-tools/SVF/blob/6c65593269babfce69e50acc7276271f4aaaa4bc/svf-llvm/include/SVF-LLVM/LLVMModule.h#L209

**Comment by yuleisui** [comment]
Svfvalue—>svfgnode (create this map by iterating nodes on svfg)
llvmvalue —> svfvalue (via getSVFValue in LLVMModule.h)

**Comment by 251** [comment]
That's something I had in mind as a last resort and thought I'd missed a mapping in one of the graph data structures. Thanks a lot!
